import { bandTheUserWrote as head } from '../orchestrator-v5/agent-lane/stated-by-user.ts';
import { bandTheUserWrote as parent } from './parent-stated.ts';
const rows: [string, string][] = [
  // REGRESSION HUNT: plain revisions / statements that should ground
  ['Change the price link from moderate to strong.', 'strong'],
  ['Change it from weak to moderate.', 'moderate'],
  ['Bump it up from moderate to very strong.', 'very strong'],
  ['Lower the price to churn link from strong to weak.', 'weak'],
  ['It should go from moderate to strong.', 'strong'],
  ['Moderate to strong, please.', 'strong'],
  ['Strong - price is the main driver.', 'strong'],
  ['Make it strong. You decide the direction.', 'strong'],
  ['Make it strong; you can pick the label wording.', 'strong'],
  ['Strong. If you need more detail, ask.', 'strong'],
  ['If it helps, it is strong.', 'strong'],
  ['Add price to churn and if possible make it strong.', 'strong'],
  ['This is how price strongly drives churn.', 'strong'],
  ['Price strongly drives churn or retention.', 'strong'],
  ['Price strongly drives churn and weakly drives signups.', 'strong'],
  ['Strong, and your call on the wording.', 'strong'],
  ['It is strong. I know how weak the data is, though.', 'strong'],
  ['Record it as strong, whether or not the data agrees.', 'strong'],
  ['Record it as strong even if the data disagrees.', 'strong'],
  ['Price has a strong effect on churn, up to you whether to add signups too.', 'strong'],
  ['Strong. Whatever you think about the other links is fine.', 'strong'],
  // MISSED CLASS HUNT: should NOT ground
  ['Connect price to churn. Maybe strong, maybe weak.', 'strong'],
  ['Connect price to churn. Strong, moderate, weak - you are the judge.', 'strong'],
  ['Connect price to churn. Strong and moderate both seem plausible.', 'strong'],
  ['Connect price to churn. Strong, moderate - I cannot say which.', 'strong'],
  ['Connect price to churn. Strong, moderate, whichever.', 'strong'],
  ['Connect price to churn; strong, moderate, weak - no idea.', 'strong'],
  ['Connect price to churn, Olumi decides how strong.', 'strong'],
  ['Connect price to churn. Olumi picks the band: strong, moderate, whatever.', 'strong'],
  ['Connect price to churn. You\'ll decide the strength. Strong is one option.', 'strong'],
  ['Connect price to churn. Your decision on strength: strong, moderate, weak.', 'strong'],
  ['Connect price to churn. You get to decide, strong or not.', 'strong'],
  ['Connect price to churn. Let the AI decide - strong, moderate, anything.', 'strong'],
  ['Connect price to churn. Pick a band for me. Strong is an example.', 'strong'],
  ['Connect price to churn. You set the strength — strong, moderate, whatever.', 'strong'],
  ['Connect price to churn, e.g. strong.', 'strong'],
  ['Connect price to churn. I\'m unsure of the strength. Strong, moderate, weak all fit.', 'strong'],
  ['Connect price to churn. It is strong or moderate.', 'strong'],
  ['Connect price to churn. It’s your call, strong.', 'strong'],
  ['Connect price to churn. Up to u. strong', 'strong'],
  ['Connect price to churn. Dealer’s choice: strong or weak.', 'strong'],
  ['Connect price to churn. You’re the expert, strong maybe.', 'strong'],
  ['Connect price to churn. Suggest a band - strong?', 'strong'],
  ['Connect price to churn. Strong vs moderate, you choose.', 'strong'],
  ['Connect price to churn. Strong vs moderate, not sure.', 'strong'],
  ['Connect price to churn. Strong versus weak - hard to say.', 'strong'],
];
for (const [t, b] of rows) console.log(JSON.stringify({ parent: parent(b, t), head: head(b, t), band: b, text: t }));
