/**
 * GuidanceItem Types
 *
 * Structured coaching items generated by CEE from existing V2RunResponse
 * and graph state data. Included in OrchestratorResponseEnvelopeV2 as
 * `guidance_items: GuidanceItem[]` — always present, defaults to [].
 *
 * item_id: deterministic hash of (signal_code + target_object?.id ?? 'global' + source)
 * Deduplication key: (signal_code + target_object?.id)
 *
 * UI rendering treatment is derived from primary_action.type:
 * - approve_patch  → confirmation friction (accept/dismiss buttons)
 * - open_inspector / navigate → low friction (single click)
 * - discuss / run_exercise → dialogue (sends to chat)
 *
 * Priority bands:
 * - must_fix:   80–100
 * - should_fix: 50–79
 * - could_fix:  20–49
 * - technique:  10–29
 */

import { createHash } from "node:crypto";
import { stableStringify } from "../context/stable-stringify.js";
import type { PatchOperation } from "../types.js";

// ============================================================================
// Signal Codes
// ============================================================================

export const SIGNAL_CODES = {
  // Structural
  STRUCTURAL_CYCLE: 'STRUCTURAL_CYCLE',
  STRUCTURAL_VALIDATION_ERROR: 'STRUCTURAL_VALIDATION_ERROR',
  // Defaults
  DEFAULT_EDGE_STRENGTH: 'DEFAULT_EDGE_STRENGTH',
  DEFAULT_NODE_CONFIDENCE: 'DEFAULT_NODE_CONFIDENCE',
  // Framing / options
  LOW_OPTION_COUNT: 'LOW_OPTION_COUNT',
  MISSING_FRAMING_ELEMENT: 'MISSING_FRAMING_ELEMENT',
  // Analysis-derived
  HIGH_INFLUENCE_LOW_CONFIDENCE: 'HIGH_INFLUENCE_LOW_CONFIDENCE',
  FRAGILE_RESULT: 'FRAGILE_RESULT',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  // ProposalCard conversions
  PROPOSAL_CARD_CRITICAL: 'PROPOSAL_CARD_CRITICAL',
  PROPOSAL_CARD_HIGH: 'PROPOSAL_CARD_HIGH',
  PROPOSAL_CARD_MEDIUM: 'PROPOSAL_CARD_MEDIUM',
  PROPOSAL_CARD_LOW: 'PROPOSAL_CARD_LOW',
  // Technique offers
  TECHNIQUE_PRE_MORTEM: 'TECHNIQUE_PRE_MORTEM',
  TECHNIQUE_DEVIL_ADVOCATE: 'TECHNIQUE_DEVIL_ADVOCATE',
  TECHNIQUE_DISCONFIRMATION: 'TECHNIQUE_DISCONFIRMATION',
  // Analysis-derived (v2)
  DOMINANT_FACTOR: 'DOMINANT_FACTOR',
  CTA_LITE: 'CTA_LITE',
  // Structural (v2)
  COMPLEXITY_CHECK: 'COMPLEXITY_CHECK',
} as const;

export type SignalCode = typeof SIGNAL_CODES[keyof typeof SIGNAL_CODES];

// ============================================================================
// Action Types
// ============================================================================

export type ExerciseType = 'pre_mortem' | 'devil_advocate' | 'disconfirmation';

export type GuidanceAction =
  | { type: 'approve_patch'; operations: PatchOperation[] }
  | { type: 'open_inspector'; node_id: string }
  | { type: 'discuss'; prompt: string }
  | { type: 'run_exercise'; exercise: ExerciseType }
  | { type: 'navigate'; target: string };

// ============================================================================
// GuidanceItem Interface
// ============================================================================

export type GuidanceCategory = 'must_fix' | 'should_fix' | 'could_fix' | 'technique';
export type GuidanceSource = 'analysis' | 'structural' | 'prompt';

export interface GuidanceItem {
  /** Deterministic: hash of (signal_code + target_object.id + source) */
  item_id: string;
  /** Stable identity key */
  signal_code: SignalCode | string;
  category: GuidanceCategory;
  source: GuidanceSource;
  /** One line, user-facing */
  title: string;
  /** 1–2 sentences, user-facing */
  detail?: string;
  primary_action: GuidanceAction;
  target_object?: {
    type: 'node' | 'edge' | 'option' | 'graph' | 'framing';
    /** Absent when type is 'graph' or 'framing' */
    id?: string;
    /** User-facing label for display */
    label?: string;
  };
  valid_while?: {
    /** Expires when analysis changes */
    analysis_hash?: string;
    /** Expires when graph changes */
    graph_hash?: string;
  };
  /** Populated only when IDs verified against response fact_objects */
  fact_ids?: string[];
  /** ProposalCardV1 citation refs when fact_ids not verifiable */
  citations?: string[];
  /** 0–100, higher = more urgent */
  priority: number;
  /** Populated when DSK is active (ENABLE_DSK_V0) */
  dsk_claim_id?: string;
  evidence_strength?: 'strong' | 'medium' | 'weak' | 'mixed';
}

// ============================================================================
// ID Generation
// ============================================================================

/**
 * Compute a deterministic item_id for a GuidanceItem.
 *
 * Hash input: signal_code + (target_object?.id ?? 'global') + source
 * Format: 'gi_' + first 16 hex chars of SHA-256
 */
export function computeGuidanceItemId(
  signal_code: string,
  target_id: string | undefined,
  source: GuidanceSource,
): string {
  const target = target_id ?? 'global';
  const hash = createHash('sha256')
    .update(stableStringify({ signal_code, target, source }))
    .digest('hex')
    .slice(0, 16);
  return `gi_${hash}`;
}

// ============================================================================
// Merge/Sort Helpers
// ============================================================================

/**
 * Deduplicate GuidanceItems on (signal_code + target_object?.id).
 * When duplicates exist, keep the higher-priority one.
 */
export function deduplicateGuidanceItems(items: GuidanceItem[]): GuidanceItem[] {
  const map = new Map<string, GuidanceItem>();
  for (const item of items) {
    const key = `${item.signal_code}:${item.target_object?.id ?? 'global'}`;
    const existing = map.get(key);
    if (!existing || item.priority > existing.priority) {
      map.set(key, item);
    }
  }
  return Array.from(map.values());
}

/**
 * Sort GuidanceItems: priority desc, then target_object.id asc, then signal_code asc (lexicographic).
 */
export function sortGuidanceItems(items: GuidanceItem[]): GuidanceItem[] {
  return [...items].sort((a, b) => {
    const priorityDiff = b.priority - a.priority;
    if (priorityDiff !== 0) return priorityDiff;
    const aTargetId = a.target_object?.id ?? '';
    const bTargetId = b.target_object?.id ?? '';
    const targetDiff = aTargetId.localeCompare(bTargetId);
    if (targetDiff !== 0) return targetDiff;
    return String(a.signal_code).localeCompare(String(b.signal_code));
  });
}
