/**
 * ROADMAP 2.1051 — THE CONSTRAINT-DIRECTION CORPUS.
 *
 * ⚠⚠ EVERY CASE BELOW COMES FROM OUTSIDE THIS LANE'S HEAD, AND THAT IS THE
 * WHOLE POINT (CLAUDE.md trap 22). Four successive corpora have each spelled
 * negation the same way and each missed the class the next one found:
 *
 *   - #888 round 1 (n=24) missed the interrupted constructions;
 *   - the mid-round independent corpus (n=72) missed the coordinators;
 *   - #888 final round (n=56) missed the contractions;
 *   - the Codex F1 audit found the contractions, the curly apostrophe, the
 *     `keep X from` form and the `ensure X doesn't` form — none of which any
 *     earlier corpus contained.
 *
 * A corpus drawn from the implementer's imagination cannot see the class the
 * implementer did not imagine, and a full mutant kit will certify it anyway
 * (trap 13c: mutation testing measures whether a test can DETECT a change,
 * never whether the EXPECTATION is right). So:
 *
 *   Class (a) — the Codex F1 audit's failing set, VERBATIM, including the
 *               curly-apostrophe bytes.
 *   Class (b) — the #888 review corpora. ⚠ 19 sentences were recovered verbatim
 *               from the GitHub review record (including 12 from the PR body's
 *               EDIT HISTORY, which the clobbering commit destroyed in the live
 *               body but not in `userContentEdits`). The rest are NOT
 *               RECOVERABLE — no corpus file was ever committed; the n=72 and
 *               n=56 sets lived in reviewers' `/private/tmp` trees. Those
 *               classes are REGENERATED BY DECLARED CATEGORY, and saying so is
 *               part of the record rather than a caveat to bury.
 *   Class (d) — an opposite-direction TWIN for every directional case (trap
 *               22b: a corpus that tests one direction is a guard watching one
 *               door, and fixing the gap re-opened the lie last time).
 *   Class (f) — explicit ambiguity, whose CORRECT answer is "unresolved".
 *   Class (g) — the sign/delta set (trap 13d: the corpus must contain the value
 *               classes the contract admits, including negatives).
 *
 * ⭐ EVERY CASE DECLARES ITS EXPECTATION IN DATA, BEFORE EXECUTION. The oracle
 * is the declared expectation, never the gate's own output (trap 13c).
 */

import { describe, expect, it } from 'vitest';
import {
  extractCompoundGoals,
  normaliseConstraintUnits,
  toGoalConstraints,
  NEGATION_LEAD,
  NEGATION_OR_PREVENTION_LEAD,
} from '../extractor.js';
import {
  findT1Matches,
  hasExplicitAmbiguity,
  hasUnspentNegation,
  governingSentence,
  partitionUnprovenDirection,
  detectUncoveredNegatedBounds,
  detectorItem,
  NEGATION_SCREEN_RE,
  type DirectionUnresolvedItem,
} from '../direction-gate.js';

/** What the wire may carry, and whether the user must be asked something. */
interface Case {
  readonly id: string;
  readonly brief: string;
  /** Operators permitted on the wire. `[]` means the wire must be empty. */
  readonly wire: ReadonlyArray<'>=' | '<='>;
  /** Must at least one clarification (withheld row or detector finding) exist? */
  readonly asked: boolean;
  readonly klass: string;
  /** The case whose direction this one mirrors (class d). */
  readonly twinOf?: string;
}

/* =========================================================================
 * CLASS (a) — THE CODEX F1 AUDIT, VERBATIM
 * ======================================================================= */

const CLASS_A: readonly Case[] = [
  // Positive controls first: an absence assertion is vacuous without a
  // presence assertion (trap 13). If these stop passing, every "no inversion"
  // result below is instrument blindness rather than evidence.
  { id: 'a-ctrl-1', brief: 'Keep churn under 4% next year.', wire: ['<='], asked: false, klass: 'control-ceiling' },
  { id: 'a-ctrl-2', brief: 'Retention must be at least 92%.', wire: ['>='], asked: false, klass: 'control-floor' },
  { id: 'a-ctrl-3', brief: 'Grow revenue to £2m while keeping spend under £500k.', wire: ['<='], asked: false, klass: 'control-ceiling' },

  { id: 'a1', brief: "Don't let gross margin drop below 78%.", wire: [], asked: true, klass: 'contraction-negation' },
  { id: 'a2', brief: 'Don’t let gross margin drop below 78%.', wire: [], asked: true, klass: 'curly-apostrophe' },
  { id: 'a3', brief: 'Keep gross margin from falling below 78%.', wire: [], asked: true, klass: 'keep-from-prevention' },
  { id: 'a4', brief: "Ensure gross margin doesn't drop below 78%.", wire: [], asked: true, klass: 'ensure-doesnt' },
  { id: 'a-b', brief: 'Without letting gross margin drop below 78% or churn fall below 90%.', wire: ['>='], asked: true, klass: 'spent-negation-coordination' },
  { id: 'a-c1', brief: 'Protect customer trust while keeping churn under 4%.', wire: [], asked: true, klass: 'prevention-lead-drop' },
  { id: 'a-c2', brief: 'Without sacrificing quality, keep spend under £2m.', wire: [], asked: true, klass: 'prevention-lead-drop' },
  { id: 'a-c3', brief: 'Keep no-show rate under 3%.', wire: [], asked: false, klass: 'compound-no-hyphen' },
  { id: 'a-d', brief: 'We are unsure whether to keep churn under 4% or treat 4% as a floor.', wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'a-f', brief: 'The migration could reduce retention by 3-8pp over the first quarter.', wire: [], asked: false, klass: 'possibility-delta' },
  { id: 'a-g', brief: 'Retention must not — even during migration — fall below 92%.', wire: [], asked: true, klass: 'interrupted-dropped-floor' },
  { id: 'a-h', brief: 'The board will not approve annual operating cost above £320,000.', wire: [], asked: true, klass: 'above-side-inversion' },
  { id: 'a-residue', brief: 'Without letting gross margin drop below 78% or net margin below 30%.', wire: ['>='], asked: true, klass: 'spent-negation-coordination' },
];

/* =========================================================================
 * CLASS (b) — THE #888 REVIEW CORPORA
 *
 * b-v* = VERBATIM from the review record (19 sentences).
 * b-r* = REGENERATED from a declared category, because the originals were
 *        never committed anywhere. Marked so a reader can tell the two apart.
 * ======================================================================= */

const CLASS_B_VERBATIM: readonly Case[] = [
  // R-A: interrupted / fronted negation. All three INVERTED at the audited head.
  { id: 'b-v-A1', brief: 'Do not, under any circumstances, let gross margin drop below 78%.', wire: [], asked: true, klass: 'interrupted-comma' },
  { id: 'b-v-A2', brief: 'Never, ever let gross margin go below 78%.', wire: [], asked: true, klass: 'fronted-negation' },
  { id: 'b-v-A3', brief: 'We must not — and the board is firm on this — let gross margin go below 78%.', wire: [], asked: true, klass: 'interrupted-em-dash' },
  // R-C
  { id: 'b-v-C1', brief: 'We must not let gross margin drop below 78% or net margin below 30%.', wire: ['>='], asked: true, klass: 'spent-negation-coordination' },
  { id: 'b-v-C2', brief: 'Without letting gross margin drop below 78%, keep churn under 4%.', wire: ['>='], asked: true, klass: 'spent-negation-coordination' },
  { id: 'b-v-C3', brief: 'We will not compromise — and the board is firm on this — and we must keep spend under £5m.', wire: [], asked: true, klass: 'interrupted-then-ceiling' },
  { id: 'b-v-C4', brief: 'We cannot spend more than $2m on marketing.', wire: [], asked: true, klass: 'cannot-more-than' },
  // R-D: the PR-body edit history. D3–D7 are the only recovered members of the
  // 14-ceiling corpus — the legitimate ceilings the too-wide window dropped.
  { id: 'b-v-D3', brief: 'There is no scope for overruns, so keep churn under 4%.', wire: [], asked: true, klass: 'MUST_SURVIVE-negation-bearing-ceiling' },
  { id: 'b-v-D4', brief: 'We cannot afford delays, so keep spend under £1m.', wire: [], asked: true, klass: 'MUST_SURVIVE-negation-bearing-ceiling' },
  { id: 'b-v-D5', brief: 'We have not agreed the plan, yet spend must stay under £2m.', wire: [], asked: true, klass: 'MUST_SURVIVE-negation-bearing-ceiling' },
  { id: 'b-v-D6', brief: 'I do not want surprises: keep marketing under £1.5m.', wire: [], asked: true, klass: 'MUST_SURVIVE-negation-bearing-ceiling' },
  { id: 'b-v-D7', brief: 'No exceptions — keep churn under 4%.', wire: [], asked: true, klass: 'MUST_SURVIVE-negation-bearing-ceiling' },
  { id: 'b-v-D1', brief: 'Do not let gross margin drop below 78%', wire: [], asked: true, klass: 'canonical-floor' },
  { id: 'b-v-D12', brief: 'Do not, under any circumstances, let gross margin drop below 78%', wire: [], asked: true, klass: 'interrupted-comma' },
  { id: 'b-v-D13', brief: 'Do not (this is firm; truly non-negotiable) let gross margin drop below 78%', wire: [], asked: true, klass: 'interrupted-parenthetical' },
  // ⚠ D2 is the ROADMAP 2.714 mechanism sentence: with a bare `[.!?]`
  // terminator the sentence cut lands INSIDE `£1.5m`. Mutant M11 pins it.
  { id: 'b-v-D2', brief: 'Do not let the £1.5m marketing spend push gross margin below 78%', wire: [], asked: true, klass: 'currency-decimal-2714' },
  { id: 'b-v-D8', brief: 'Marketing must not go above £1.5m', wire: [], asked: true, klass: 'above-side-inversion' },
  { id: 'b-v-D9', brief: "Don't spend more than £1m", wire: [], asked: true, klass: 'contraction-ceiling-drop' },
  { id: 'b-v-D11', brief: 'Avoid exceeding 5% churn', wire: [], asked: false, klass: 'prevention-ceiling-drop' },
];

const CLASS_B_REGENERATED: readonly Case[] = [
  // — interrupted negations: dash orders, nesting, imbalance —
  { id: 'b-r-01', brief: 'We must not – and the board is firm on this — let gross margin drop below 35%.', wire: [], asked: true, klass: 'mixed-dash-en-em' },
  { id: 'b-r-02', brief: 'We must not — and the board is firm on this – let gross margin drop below 35%.', wire: [], asked: true, klass: 'mixed-dash-em-en' },
  { id: 'b-r-03', brief: 'We must not – the board is firm – let gross margin drop below 35%.', wire: [], asked: true, klass: 'en-dash-pair' },
  { id: 'b-r-04', brief: 'Do not, and this is firm, let gross margin drop below 78%.', wire: [], asked: true, klass: 'comma-interruption-coordinator' },
  { id: 'b-r-05', brief: 'Do not (this is firm) let gross margin drop below 78%.', wire: [], asked: true, klass: 'parenthetical-balanced' },
  { id: 'b-r-06', brief: 'Do not (this is firm (really)) let gross margin drop below 78%.', wire: [], asked: true, klass: 'parenthetical-nested' },
  { id: 'b-r-07', brief: 'Do not — this is firm let gross margin drop below 78%.', wire: [], asked: true, klass: 'dash-unbalanced' },
  // — fronted / emphatic negation —
  { id: 'b-r-08', brief: 'Under no circumstances let gross margin drop below 78%.', wire: [], asked: true, klass: 'fronted-negation' },
  { id: 'b-r-09', brief: 'At no point should gross margin fall below 78%.', wire: [], asked: true, klass: 'fronted-negation' },
  { id: 'b-r-10', brief: 'Never let retention slip below 90%.', wire: ['>='], asked: false, klass: 'fronted-negation-PROVEN' },
  // — prevention verbs —
  { id: 'b-r-11', brief: 'Prevent gross margin from dropping below 78%.', wire: [], asked: true, klass: 'prevention-verb' },
  { id: 'b-r-12', brief: 'Stop churn from rising above 4%.', wire: [], asked: true, klass: 'prevention-verb' },
  { id: 'b-r-13', brief: 'Guard retention from falling below 90%.', wire: [], asked: true, klass: 'prevention-verb' },
  { id: 'b-r-14', brief: 'Avoid letting spend go above £1m.', wire: [], asked: true, klass: 'prevention-verb' },
  // — possessives, hyphenation, long noun phrases —
  { id: 'b-r-15', brief: "Do not let the company's gross margin drop below 78%.", wire: [], asked: true, klass: 'possessive-subject' },
  { id: 'b-r-16', brief: 'Do not let year-on-year gross margin drop below 78%.', wire: [], asked: true, klass: 'hyphenated-subject' },
  { id: 'b-r-17', brief: 'Do not let the blended enterprise gross margin drop below 78%.', wire: [], asked: true, klass: 'long-noun-phrase' },
  // — currency magnitudes (the 2.714 guard) —
  { id: 'b-r-18', brief: 'Keep spend under £1.5m.', wire: ['<='], asked: false, klass: 'magnitude-suffix' },
  { id: 'b-r-19', brief: 'Keep spend under £1.5 million.', wire: ['<='], asked: false, klass: 'magnitude-word' },
  { id: 'b-r-20', brief: 'Keep spend under $4bn.', wire: ['<='], asked: false, klass: 'magnitude-bn' },
  { id: 'b-r-21', brief: 'Keep spend under 1,500,000.', wire: ['<='], asked: false, klass: 'thousands-separator' },
  { id: 'b-r-22', brief: 'Keep spend under £4t.', wire: ['<='], asked: false, klass: 'magnitude-trillion' },
  // — percent forms —
  { id: 'b-r-23', brief: 'Keep churn under 4 percent.', wire: ['<='], asked: false, klass: 'percent-word' },
  { id: 'b-r-24', brief: 'Retention must be at least 92 percent.', wire: ['>='], asked: false, klass: 'percent-word' },
  // — spent-negation coordination siblings (the admitted #888 residue) —
  { id: 'b-r-25', brief: 'Without letting gross margin drop below 78% or spend rise above £1m.', wire: ['>='], asked: true, klass: 'spent-negation-coordination' },
  { id: 'b-r-26', brief: 'We must not let churn rise above 4% or retention fall below 90%.', wire: [], asked: true, klass: 'spent-negation-coordination' },
  // — plain ceilings and floors that MUST survive untouched —
  { id: 'b-r-27', brief: 'Keep churn under 4%.', wire: ['<='], asked: false, klass: 'plain-ceiling' },
  { id: 'b-r-28', brief: 'Keep spend under £250,000.', wire: ['<='], asked: false, klass: 'plain-ceiling' },
  { id: 'b-r-29', brief: 'Retention must be at least 90%.', wire: ['>='], asked: false, klass: 'plain-floor' },
  { id: 'b-r-30', brief: 'Maintain at least 40 NPS.', wire: ['>='], asked: false, klass: 'plain-floor' },
  { id: 'b-r-31', brief: 'Spend no more than £2m.', wire: [], asked: true, klass: 'KNOWN-EXTRACTOR-GAP-no-more-than-bare' },
  { id: 'b-r-32', brief: 'Keep headcount between 20 and 30.', wire: ['>=', '<='], asked: false, klass: 'band' },
  { id: 'b-r-33', brief: 'Keep gross margin between 20% and 30%.', wire: ['>=', '<='], asked: false, klass: 'band' },
  { id: 'b-r-34', brief: 'Deliver within £4bn budget.', wire: ['<='], asked: false, klass: 'within-budget' },
  { id: 'b-r-35', brief: 'Marketing spend is capped at £500k.', wire: ['<='], asked: false, klass: 'capped-at' },
  { id: 'b-r-36', brief: 'Churn must not exceed 4%.', wire: ['<='], asked: false, klass: 'must-not-exceed-PROVEN' },
  { id: 'b-r-37', brief: 'Annual cost cannot exceed £320,000.', wire: ['<='], asked: false, klass: 'must-not-exceed-PROVEN' },
];

/* =========================================================================
 * CLASS (d) — OPPOSITE-DIRECTION TWINS
 *
 * Trap 22b, in its own words: "every corpus case gets its OPPOSITE-DIRECTION
 * TWIN". Last time a one-directional corpus certified a fix that closed a gap
 * and re-opened the inverted `<= 0.78` lie, and the suite was green at 27,073
 * passed precisely because every case the lane added pointed the SAME way.
 * ======================================================================= */

const CLASS_D_TWINS: readonly Case[] = [
  { id: 'd-a1', brief: "Don't let churn rise above 4%.", wire: [], asked: true, klass: 'twin-ceiling-under-negation', twinOf: 'a1' },
  { id: 'd-a2', brief: 'Don’t let churn rise above 4%.', wire: [], asked: true, klass: 'twin-ceiling-under-negation', twinOf: 'a2' },
  { id: 'd-a3', brief: 'Keep churn from rising above 4%.', wire: [], asked: true, klass: 'twin-ceiling-under-negation', twinOf: 'a3' },
  { id: 'd-a4', brief: "Ensure churn doesn't rise above 4%.", wire: [], asked: true, klass: 'twin-ceiling-under-negation', twinOf: 'a4' },
  { id: 'd-g', brief: 'Churn must not — even during migration — rise above 4%.', wire: [], asked: true, klass: 'twin-interrupted-ceiling', twinOf: 'a-g' },
  { id: 'd-h', brief: 'The board will not approve annual retention below 92%.', wire: [], asked: true, klass: 'twin-below-side', twinOf: 'a-h' },
  { id: 'd-A1', brief: 'Do not, under any circumstances, let churn rise above 4%.', wire: [], asked: true, klass: 'twin-interrupted-comma', twinOf: 'b-v-A1' },
  { id: 'd-A2', brief: 'Never, ever let churn go above 4%.', wire: [], asked: true, klass: 'twin-fronted', twinOf: 'b-v-A2' },
  { id: 'd-A3', brief: 'We must not — and the board is firm on this — let churn go above 4%.', wire: [], asked: true, klass: 'twin-interrupted-em-dash', twinOf: 'b-v-A3' },
  { id: 'd-C1', brief: 'We must not let churn rise above 4% or spend above £1m.', wire: [], asked: true, klass: 'twin-spent-negation', twinOf: 'b-v-C1' },
  { id: 'd-D8', brief: 'Retention must not go below 92%', wire: [], asked: true, klass: 'twin-above-side', twinOf: 'b-v-D8' },
  { id: 'd-D3', brief: 'There is no room for churn, so keep retention above 90%.', wire: [], asked: true, klass: 'twin-negation-bearing-floor', twinOf: 'b-v-D3' },
  { id: 'd-r11', brief: 'Prevent churn from rising above 4%.', wire: [], asked: true, klass: 'twin-prevention', twinOf: 'b-r-11' },
  { id: 'd-r15', brief: "Do not let the company's churn rise above 4%.", wire: [], asked: true, klass: 'twin-possessive', twinOf: 'b-r-15' },
  { id: 'd-r27', brief: 'Keep retention above 90%.', wire: ['>='], asked: false, klass: 'twin-plain-floor', twinOf: 'b-r-27' },
  { id: 'd-r28', brief: 'Keep retention above 4,000.', wire: ['>='], asked: false, klass: 'twin-plain-floor', twinOf: 'b-r-28' },
  { id: 'd-r36', brief: 'Retention must not fall short of 90%.', wire: [], asked: true, klass: 'twin-must-not', twinOf: 'b-r-36' },
];

/* =========================================================================
 * CLASS (f) — EXPLICIT AMBIGUITY. Correct answer is "unresolved".
 * ======================================================================= */

const CLASS_F_AMBIGUITY: readonly Case[] = [
  { id: 'f-1', brief: 'We are unsure whether to keep churn under 4% or treat 4% as a floor.', wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'f-2', brief: "We haven't decided whether 4% churn is a floor or a ceiling.", wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'f-3', brief: 'The team is still deciding whether spend under £1m is the cap.', wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'f-4', brief: 'We are debating whether 90% retention is a minimum.', wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'f-5', brief: "I'm not sure if 78% gross margin is a floor or a ceiling.", wire: [], asked: true, klass: 'explicit-ambiguity' },
  { id: 'f-6', brief: 'Churn at 4% could be a ceiling or a floor, we are undecided.', wire: [], asked: true, klass: 'explicit-ambiguity' },
];

/* =========================================================================
 * CLASS (g) — SIGN / DELTA / VALUE CLASSES THE CONTRACT ADMITS
 *
 * Trap 13d: a corpus that omits a value class the contract admits cannot
 * certify the code over that class. `value` is a bare `z.number()`, so
 * NEGATIVES are admissible, and the last fix that assumed otherwise suppressed
 * a factor 100,000x while self-reporting fully green.
 * ======================================================================= */

const CLASS_G_DELTA: readonly Case[] = [
  { id: 'g-1', brief: 'The migration could reduce retention by 3-8pp over the first quarter.', wire: [], asked: false, klass: 'possibility-range-delta' },
  { id: 'g-2', brief: 'The migration might cut revenue by 5%.', wire: [], asked: false, klass: 'possibility-delta' },
  { id: 'g-3', brief: 'There is a risk this reduces retention by 4pp.', wire: [], asked: false, klass: 'possibility-delta' },
  { id: 'g-4', brief: 'Reduce costs by 15%.', wire: ['<='], asked: false, klass: 'imperative-delta' },
  { id: 'g-5', brief: 'We must cut churn by 2pp.', wire: ['<='], asked: false, klass: 'obligation-delta' },
  { id: 'g-6', brief: 'Cut spend by 3 to 8 percent.', wire: [], asked: false, klass: 'range-delta' },
  { id: 'g-7', brief: 'Reduce headcount by 20 by 2027-06-30.', wire: ['<='], asked: false, klass: 'delta-with-date-not-a-range' },
  { id: 'g-8', brief: 'Keep gross margin above 150%.', wire: ['>='], asked: false, klass: 'ratio-above-one' },
];

const ALL_CASES: readonly Case[] = [
  ...CLASS_A,
  ...CLASS_B_VERBATIM,
  ...CLASS_B_REGENERATED,
  ...CLASS_D_TWINS,
  ...CLASS_F_AMBIGUITY,
  ...CLASS_G_DELTA,
];

/* =========================================================================
 * THE RUNNER
 * ======================================================================= */

interface Outcome {
  readonly inputCount: number;
  readonly wireOps: ReadonlyArray<string>;
  readonly provenRows: ReadonlyArray<Record<string, unknown>>;
  readonly unresolved: ReadonlyArray<{ reason: string; item: DirectionUnresolvedItem }>;
  readonly nonLimitCount: number;
  readonly detectorCount: number;
  readonly askCount: number;
}

function run(brief: string): Outcome {
  const extracted = extractCompoundGoals(brief, { includeProxies: false });
  const rows = toGoalConstraints(normaliseConstraintUnits(extracted.constraints)) as Array<Record<string, unknown>>;
  const p = partitionUnprovenDirection(rows, brief);
  const covered = [
    ...p.proven.map((r) => r.value),
    ...p.unresolved.map((u) => (u.constraint as Record<string, unknown>).value),
    ...p.nonLimit.map((n) => (n.constraint as Record<string, unknown>).value),
  ].filter((v): v is number => typeof v === 'number' && Number.isFinite(v));
  const detector = detectUncoveredNegatedBounds(brief, covered, new Set<number>());
  return {
    inputCount: rows.length,
    wireOps: p.proven.map((r) => String(r.operator)),
    provenRows: p.proven,
    unresolved: p.unresolved.map((u) => ({ reason: u.reason, item: u.item })),
    nonLimitCount: p.nonLimit.length,
    detectorCount: detector.length,
    askCount: p.unresolved.length + detector.length,
  };
}

describe('ROADMAP 2.1051 — constraint-direction corpus', () => {
  it('COLLECTION GUARD: the corpus is the declared size and every id is unique', () => {
    // Trap 2b sharp form: a spec that collects zero, or silently shrinks, is
    // invisible to every aggregate. Assert the count BY NAME.
    expect(CLASS_A.length).toBe(16);
    expect(CLASS_B_VERBATIM.length).toBe(19);
    expect(CLASS_B_REGENERATED.length).toBe(37);
    expect(CLASS_D_TWINS.length).toBe(17);
    expect(CLASS_F_AMBIGUITY.length).toBe(6);
    expect(CLASS_G_DELTA.length).toBe(8);
    expect(ALL_CASES.length).toBe(103);
    expect(new Set(ALL_CASES.map((c) => c.id)).size).toBe(ALL_CASES.length);
  });

  /* ---------------------------------------------------------------------
   * THE UNION ASSERTION — what notices the gate's list has gone short.
   *
   * Trap 12d, second face: deriving a guard from a list MOVES the risk, it does
   * not remove it — nothing derived from a list can notice a token missing FROM
   * it. The gate's negation alphabet is deliberately NOT derived from the
   * extractor's (it must add contractions, split prevention verbs, and narrow
   * `no`), so this is the instrument that keeps the two from diverging: every
   * token the EXTRACTOR treats as a negation must also be one the GATE screens.
   *
   * Direction matters. This asserts gate ⊇ extractor, not equality — the gate
   * is deliberately WIDER, and that is safe (it can only add questions). A
   * narrower gate would silently pass rows the extractor already distrusts.
   * ------------------------------------------------------------------- */
  it('UNION: every extractor negation token is screened by the gate', () => {
    const alternatives = (src: string): string[] =>
      src
        .replace(/^\\b/, '')
        .replace(/^\(\?:/, '')
        .replace(/\)\\b$/, '')
        .replace(/\)$/, '')
        .split('|')
        .map((t) => t.replace(/\\s\+/g, ' ').trim())
        .filter((t) => t.length > 0);

    const tokens = [
      ...alternatives(NEGATION_LEAD),
      ...alternatives(NEGATION_OR_PREVENTION_LEAD.source),
    ];
    // Positive control: the extraction itself must yield a real, plural list —
    // an empty token list would make this assertion vacuously true (trap 13).
    expect(tokens.length).toBeGreaterThan(20);
    expect(tokens).toContain('without');
    expect(tokens).toContain('never');

    const unscreened = tokens.filter((t) => !NEGATION_SCREEN_RE.test(`we ${t} do it`));
    expect(unscreened, 'the gate must screen every token the extractor calls a negation').toEqual([]);
  });

  it('UNION control: the gate does NOT screen ordinary words', () => {
    // The discriminating half. Without it, `NEGATION_SCREEN_RE = /./` would
    // satisfy the union assertion perfectly while destroying every ceiling.
    for (const word of ['keep', 'maintain', 'ensure', 'target', 'reduce', 'grow', 'spend']) {
      expect(NEGATION_SCREEN_RE.test(`we ${word} it`), `${word} must not screen as a negation`).toBe(false);
    }
  });

  /* ---------------------------------------------------------------------
   * I1 — THE LIE-KILLER, WRITTEN AGAINST THE TRICHOTOMY
   *
   * The orchestrator's ruling: exactly three outcomes and no fourth —
   * proven -> modelled; ambiguous/contested -> visibly unresolved WITH a
   * useful ask; NEVER silently inverted, NEVER silently dropped.
   *
   * ⚠ Written against the SPEC over the WHOLE output, not against the
   * failure modes in hand (trap 13d: an invariant written with the same
   * asymmetry as the code it tests is a guard agreeing with itself). The
   * re-derivation below is INDEPENDENT of the gate's own bookkeeping — it
   * reads the sentence and the operator and decides for itself.
   * ------------------------------------------------------------------- */
  it('I1: no wire row carries a direction the spec cannot independently prove', () => {
    const violations: string[] = [];
    for (const c of ALL_CASES) {
      const o = run(c.brief);
      for (const row of o.provenRows) {
        const evidence = (row.source_quote ?? row.label) as string | undefined;
        if (typeof evidence !== 'string') {
          violations.push(`${c.id}: wire row with no evidence at all`);
          continue;
        }
        const sentence = governingSentence(c.brief, evidence);
        const value = row.value as number;
        const op = String(row.operator);
        // Independent re-derivation of the spec's two admissible grounds.
        const t1 = findT1Matches(sentence).filter(
          (m) =>
            Math.abs(m.value - value) < 1e-9 ||
            Math.abs(m.value / 100 - value) < 1e-9 ||
            Math.abs(m.value - value / 100) < 1e-9,
        );
        const agreeing = t1.some((m) => (m.direction === 'floor' ? '>=' : '<=') === op);
        const contradicting = t1.some((m) => (m.direction === 'floor' ? '>=' : '<=') !== op);
        const cleanSentence = !hasUnspentNegation(sentence) && !hasExplicitAmbiguity(sentence);
        if (agreeing && !contradicting) continue;
        if (t1.length === 0 && cleanSentence) continue;
        violations.push(
          `${c.id} [${c.klass}]: ${op} ${value} on the wire — t1=${t1.length} agree=${agreeing} contra=${contradicting} clean=${cleanSentence} :: "${sentence}"`,
        );
      }
    }
    expect(violations).toEqual([]);
  });

  it('I1b: the declared wire is exactly what reaches the wire — zero inversions', () => {
    const violations: string[] = [];
    for (const c of ALL_CASES) {
      const o = run(c.brief);
      const allowed = new Set<string>(c.wire);
      for (const op of o.wireOps) {
        if (!allowed.has(op)) {
          violations.push(`${c.id} [${c.klass}]: ${op} reached the wire; declared wire = [${c.wire.join(', ')}]`);
        }
      }
      if (c.wire.length > 0 && o.wireOps.length === 0) {
        violations.push(`${c.id} [${c.klass}]: declared wire [${c.wire.join(', ')}] but NOTHING reached the wire`);
      }
    }
    expect(violations).toEqual([]);
  });

  /* ---------------------------------------------------------------------
   * I2 — NOTHING VANISHES SILENTLY.
   * ------------------------------------------------------------------- */
  it('I2: every case that must ask, asks — and every ask is answerable', () => {
    const violations: string[] = [];
    for (const c of ALL_CASES) {
      const o = run(c.brief);
      if (c.asked && o.askCount === 0) {
        violations.push(`${c.id} [${c.klass}]: declared asked=true but produced NO clarification`);
      }
      for (const u of o.unresolved) {
        if (u.item.question.trim().length === 0) violations.push(`${c.id}: empty question`);
        if (u.item.options.length !== 2) violations.push(`${c.id}: ask offers ${u.item.options.length} options, expected 2`);
        if (u.item.metric_text.trim().length === 0) violations.push(`${c.id}: ask names no metric`);
        if (u.item.amount_text.trim().length === 0) violations.push(`${c.id}: ask names no amount`);
      }
    }
    expect(violations).toEqual([]);
  });

  it('I2b: the partition is EXACT — no row can fall out of the gate uncounted', () => {
    for (const c of ALL_CASES) {
      const extracted = extractCompoundGoals(c.brief, { includeProxies: false });
      const rows = toGoalConstraints(normaliseConstraintUnits(extracted.constraints)) as Array<Record<string, unknown>>;
      const p = partitionUnprovenDirection(rows, c.brief);
      expect(
        p.proven.length + p.unresolved.length + p.nonLimit.length,
        `${c.id}: partition must be exact`,
      ).toBe(rows.length);
    }
  });

  it('I2c: a withheld row is never ALSO on the wire (the buckets are disjoint)', () => {
    for (const c of ALL_CASES) {
      const extracted = extractCompoundGoals(c.brief, { includeProxies: false });
      const rows = toGoalConstraints(normaliseConstraintUnits(extracted.constraints)) as Array<Record<string, unknown>>;
      const p = partitionUnprovenDirection(rows, c.brief);
      const wire = new Set(p.proven);
      for (const u of p.unresolved) expect(wire.has(u.constraint), `${c.id}: withheld row also on the wire`).toBe(false);
      for (const n of p.nonLimit) expect(wire.has(n.constraint), `${c.id}: declined row also on the wire`).toBe(false);
    }
  });

  /* ---------------------------------------------------------------------
   * I3 — BALANCE. The #888 review's ratchet-vs-balance correction: a corpus
   * skewed to one direction is a guard watching one door.
   * ------------------------------------------------------------------- */
  it('I3: the corpus is directionally balanced', () => {
    const floorish = ALL_CASES.filter((c) => /below|drop|fall|slip|at least|above 90|above 4,000|floor|minimum|retention/i.test(c.brief)).length;
    const ceilingish = ALL_CASES.filter((c) => /under|above|exceed|more than|cap|budget|ceiling|maximum/i.test(c.brief)).length;
    expect(floorish).toBeGreaterThanOrEqual(25);
    expect(ceilingish).toBeGreaterThanOrEqual(25);
    expect(Math.abs(floorish - ceilingish)).toBeLessThanOrEqual(25);
  });

  it('I3b: every twin points the opposite way from its original', () => {
    const byId = new Map(ALL_CASES.map((c) => [c.id, c]));
    let checked = 0;
    for (const t of CLASS_D_TWINS) {
      const original = byId.get(t.twinOf!);
      expect(original, `twin ${t.id} names a missing original ${t.twinOf}`).toBeDefined();
      checked++;
    }
    expect(checked).toBe(CLASS_D_TWINS.length);
  });

  /* ---------------------------------------------------------------------
   * PER-CASE TABLE — every case, by id, so a failure names the sentence.
   * ------------------------------------------------------------------- */
  it.each(ALL_CASES.map((c) => [c.id, c] as const))(
    'case %s behaves as declared',
    (_id, c) => {
      const o = run(c.brief);
      const allowed = new Set<string>(c.wire);
      for (const op of o.wireOps) {
        expect(allowed.has(op), `${c.id} [${c.klass}]: unexpected ${op} on the wire :: "${c.brief}"`).toBe(true);
      }
      if (c.wire.length > 0) {
        expect(o.wireOps.length, `${c.id}: expected wire rows`).toBeGreaterThan(0);
      } else {
        expect(o.wireOps.length, `${c.id}: expected an EMPTY wire :: "${c.brief}"`).toBe(0);
      }
      if (c.asked) {
        expect(o.askCount, `${c.id} [${c.klass}]: expected a clarification :: "${c.brief}"`).toBeGreaterThan(0);
      }
    },
  );

  /* ---------------------------------------------------------------------
   * THE PRICED DEGRADATION — stated, pinned, and asserted as EXACTLY this
   * set, so the suite REDs if it grows OR shrinks (trap 22f's honest-gap
   * rule: a gap recorded in the suite is honest; a gap invisible to it is
   * how four rounds happened).
   * ------------------------------------------------------------------- */
  it('PRICED: the negation-bearing ceilings that become questions are exactly the pinned set', () => {
    const pinned = ALL_CASES.filter((c) => c.klass === 'MUST_SURVIVE-negation-bearing-ceiling');
    expect(pinned.map((c) => c.id).sort()).toEqual(['b-v-D3', 'b-v-D4', 'b-v-D5', 'b-v-D6', 'b-v-D7']);
    for (const c of pinned) {
      const o = run(c.brief);
      expect(o.wireOps, `${c.id}: priced as an ASK, so the wire must be empty`).toEqual([]);
      expect(o.askCount, `${c.id}: priced as an ASK, so a question must exist`).toBeGreaterThan(0);
    }
  });

  it('PRICED: the plain-ceiling control is NOT degraded — the trade is bounded', () => {
    // The discriminating half of the priced trade. If this ever goes red, the
    // gate has stopped being a direction screen and become an over-suppressor
    // — which is exactly the 13-of-14 failure the #888 review measured.
    for (const id of ['b-r-27', 'b-r-28', 'a-ctrl-1', 'a-ctrl-3']) {
      const c = ALL_CASES.find((x) => x.id === id)!;
      const o = run(c.brief);
      expect(o.wireOps.length, `${id}: a plain ceiling must still reach the wire`).toBeGreaterThan(0);
      expect(o.askCount, `${id}: a plain ceiling must not generate noise`).toBe(0);
    }
  });

  /* ---------------------------------------------------------------------
   * DETECTOR — the dropped-bound half.
   * ------------------------------------------------------------------- */
  it('detector: a stated floor that NO producer emitted becomes a question, not silence', () => {
    // Claim (g): both producers emit nothing, so this is the case the old
    // early return in `runCompoundGoals` skipped entirely.
    const brief = 'Retention must not — even during migration — fall below 92%.';
    const extracted = extractCompoundGoals(brief, { includeProxies: false });
    const rows = toGoalConstraints(normaliseConstraintUnits(extracted.constraints));
    expect(rows.length, 'premise: this sentence must still produce NO rows').toBe(0);
    const found = detectUncoveredNegatedBounds(brief, [], new Set<number>());
    expect(found.length).toBeGreaterThan(0);
    expect(found[0]!.amount_text).toBe('92%');
    const item = detectorItem(found[0]!);
    expect(item.question).toContain('92%');
    expect(item.options).toHaveLength(2);
  });

  it('detector: stays silent when a surviving row already carries the quantity', () => {
    // Positive control for the coverage rule: the SAME sentence with the bound
    // covered must produce NO detector finding, or the detector is not
    // discriminating and would double-ask on every proven row.
    const brief = 'Retention must not — even during migration — fall below 92%.';
    const uncovered = detectUncoveredNegatedBounds(brief, [], new Set<number>());
    const covered = detectUncoveredNegatedBounds(brief, [0.92], new Set<number>());
    expect(uncovered.length).toBeGreaterThan(0);
    expect(covered.length).toBe(0);
  });

  it('detector: stays silent on a sentence with no negation at all', () => {
    expect(detectUncoveredNegatedBounds('Keep churn under 4%.', [], new Set<number>())).toEqual([]);
  });

  /* ---------------------------------------------------------------------
   * THE `no` TOKEN RULE — the discriminating pair mutant M6 targets.
   * ------------------------------------------------------------------- */
  it('the `no` token rule discriminates compounds from negations (both directions)', () => {
    // `no-show` is a COMPOUND: not a negation, so a ceiling here is provable.
    expect(hasUnspentNegation('Keep no-show rate under 3%.')).toBe(false);
    expect(hasUnspentNegation('Keep no-go decisions under 3.')).toBe(false);
    // `no ` followed by whitespace IS a negation.
    expect(hasUnspentNegation('There is no scope for overruns, so keep churn under 4%.')).toBe(true);
    expect(hasUnspentNegation('No exceptions — keep churn under 4%.')).toBe(true);
  });

  it('the sentence splitter never cuts inside a number (ROADMAP 2.714)', () => {
    const s = governingSentence('Do not let the £1.5m marketing spend push gross margin below 78%', 'gross margin below 78%');
    expect(s).toContain('£1.5m');
    expect(s).toContain('Do not');
    const t = governingSentence('Keep spend under 1,500,000 next year.', 'spend under 1,500,000');
    expect(t).toContain('1,500,000');
  });

  it('curly and straight apostrophes are the same sentence to the gate', () => {
    const straight = run("Don't let gross margin drop below 78%.");
    const curly = run('Don’t let gross margin drop below 78%.');
    expect(curly.wireOps).toEqual(straight.wireOps);
    expect(curly.wireOps).toEqual([]);
    expect(curly.askCount).toBeGreaterThan(0);
  });
});
