/**
 * Entity ID leak pattern + label resolution — neutral utility.
 *
 * Single source of truth for the entity-ID detection regex used across the
 * codebase. Originally lived in `../patch-summary.ts`; extracted here so that
 * V5 modules (`src/orchestrator-v5/`) can import without creating a V5→V4
 * dependency edge.
 *
 * @internal — any change to ENTITY_ID_LEAK_RE must be co-reviewed against:
 *   - 7 callsites in src/orchestrator/patch-summary.ts (use `.test()` for
 *     bail-out semantics; widening here makes them bail more aggressively).
 *   - src/orchestrator-v5/compose/output-safety.ts (uses a per-call global
 *     matcher; widening here makes egress sanitisation more aggressive).
 *
 * The regex is intentionally broad: it covers both id-naming schemes used
 * across the codebase (short `fac_/opt_/...` prefixes and full-word
 * `factor_/option_/...` prefixes generated by deterministic handlers). It
 * over-matches English compounds like `factor_analysis`; callers needing
 * precision must layer a confirmation gate (see the slug-shape heuristic in
 * output-safety.ts).
 */

import type { GraphV3T } from '../types.js';

export const ENTITY_ID_LEAK_RE =
  /\b(?:fac|opt|goal|dec|out|risk|con|factor|option|decision|outcome|constraint)[_:-][a-z0-9_:-]+\b/i;

/**
 * Resolve a node ID to its human-readable label by searching graph.nodes.
 * Returns null when the graph is missing OR the id has no matching node.
 *
 * For add_node operations, callers should resolve from `op.value.label` FIRST
 * (the new node is not in the graph yet) and only fall through to this helper
 * for existing-entity references.
 */
export function resolveLabel(graph: GraphV3T | null | undefined, id: string): string | null {
  if (!graph) return null;
  for (const node of graph.nodes) {
    if ((node as { id?: string }).id === id) {
      const label = (node as { label?: string }).label;
      return typeof label === 'string' && label.length > 0 ? label : null;
    }
  }
  return null;
}
