import { expect, it } from 'vitest';
import { figureTheUserWroteFor, type EntityScope } from '../stated-by-user.js';

type Row = { name: string; value: number; unit: string; brief: string; scope: EntityScope; expected: boolean };
const rows: Row[] = [
  { name: 'current payment: customer price is explicitly paid, not a total', value: 300, unit: 'GBP/customer/month',
    brief: '£120,000 monthly recurring revenue from 400 customers paying £300 a month.',
    scope: { target: ['Existing monthly price'], others: ['Existing customers', 'Starter monthly price', 'monthly recurring revenue'] }, expected: true },
  { name: 'NEGATIVE current payment: starter customers pay the same price', value: 300, unit: 'GBP/customer/month',
    brief: 'Starter customers are paying £300 a month; existing customers have an uncertain monthly price. We have 400 starter customers paying £300 a month.',
    scope: { target: ['Existing monthly price'], others: ['Existing customers', 'Starter monthly price', 'Starter customers'] }, expected: false },
  { name: 'NEGATIVE current payment: customer price per year is not a monthly price', value: 300, unit: 'GBP/customer/month',
    brief: 'We have 400 customers paying £300 a year; our monthly price is unknown.',
    scope: { target: ['Existing monthly price'], others: ['Existing customers', 'Starter monthly price'] }, expected: false },
  { name: 'current payment: a shared count noun still names existing paying customers', value: 400, unit: 'customers',
    brief: '£120,000 monthly recurring revenue from 400 customers paying £300 a month.',
    scope: { target: ['Existing customers'], others: ['Existing customer monthly price', 'Customers lost to price rise', 'Starter customers', 'monthly recurring revenue'] }, expected: true },
  { name: 'NEGATIVE current payment count: starter payers never count existing customers', value: 400, unit: 'customers',
    brief: 'We have 400 starter customers paying £300 a month; existing customer count is unknown.',
    scope: { target: ['Existing customers'], others: ['Starter customers', 'Existing customer monthly price'] }, expected: false },
  { name: 'unit noun: existing customers are written beside their count', value: 400, unit: 'customers',
    brief: '£120,000 monthly recurring revenue from 400 customers paying £300 a month.',
    scope: { target: ['Existing customers'], others: ['monthly recurring revenue', 'Existing monthly price', 'Starter subscribers'] }, expected: true },
  { name: 'NEGATIVE unit noun: 400 counts starter customers, never existing customers', value: 400, unit: 'customers',
    brief: 'We have 400 starter customers and existing customers pay £300 a month.',
    scope: { target: ['Existing customers'], others: ['Starter customers', 'Existing monthly price'] }, expected: false },
  { name: 'unit naming word: completes binds completed appointments', value: 920, unit: 'completed appointments per month',
    brief: 'Our clinic completes 920 appointments each month, has 18 staff.',
    scope: { target: ['completed appointments'], others: ['Missed appointments per month', 'Clinic staff'] }, expected: true },
  { name: 'NEGATIVE unit naming word: 920 missed appointments never counts completed appointments', value: 920, unit: 'completed appointments per month',
    brief: 'Our clinic misses 920 appointments each month, and completes 800 appointments.',
    scope: { target: ['completed appointments'], others: ['Missed appointments per month', 'Clinic staff'] }, expected: false },
  { name: 'shared count noun: general completed appointments are not additional appointments', value: 920, unit: 'appointments/month',
    brief: 'The clinic completes 920 appointments each month, with 18 staff.',
    scope: { target: ['Completed appointments per month'], others: ['Additional Saturday completed appointments', 'Clinic staff'] }, expected: true },
  { name: 'NEGATIVE shared count noun: Saturday appointments never count general completions', value: 920, unit: 'appointments/month',
    brief: 'Saturday sessions complete 920 additional Saturday appointments each month; general completed appointments are unknown.',
    scope: { target: ['Completed appointments per month'], others: ['Additional Saturday completed appointments', 'Clinic staff'] }, expected: false },
  { name: 'shared period count: weekly loaves are bound by each week', value: 60000, unit: 'loaves/week',
    brief: 'We sell 60,000 loaves each week at a wholesale price of £0.80 per loaf.',
    scope: { target: ['Weekly loaves sold'], others: ['Monthly loaves sold', 'Wholesale price per loaf'] }, expected: true },
  { name: 'NEGATIVE shared period count: monthly loaves never count weekly loaves', value: 60000, unit: 'loaves/week',
    brief: 'We sell 60,000 loaves each month; our weekly loaves sold are uncertain.',
    scope: { target: ['Weekly loaves sold'], others: ['Monthly loaves sold', 'Wholesale price per loaf'] }, expected: false },
  { name: 'shared money noun: unqualified revenue belongs to general revenue', value: 120000, unit: 'GBP/month',
    brief: 'We have £120,000 monthly recurring revenue from 400 customers.',
    scope: { target: ['monthly recurring revenue'], others: ['Starter tier monthly recurring revenue', 'Existing customers'] }, expected: true },
  { name: 'NEGATIVE shared money noun: starter revenue is never general revenue', value: 120000, unit: 'GBP/month',
    brief: 'The starter tier has £120,000 monthly recurring revenue; existing customers pay £300.',
    scope: { target: ['monthly recurring revenue'], others: ['Starter tier monthly recurring revenue', 'Existing customers'] }, expected: false },
  { name: 'NEGATIVE shared money noun: another cost keeps its qualifier', value: 48000, unit: 'GBP/month',
    brief: 'The clinic pays £48,000 in staffing costs per month; operating cost remains uncertain.',
    scope: { target: ['Monthly operating cost'], others: ['Additional staffing cost', 'Clinic staff'] }, expected: false },
  { name: 'money noun phrase: in monthly revenue is adjacent to the amount', value: 190000, unit: 'GBP/month',
    brief: 'Our bakery supplies independent grocers and earns about £190,000 in monthly revenue.',
    scope: { target: ['monthly revenue'], others: ['Additional stores supplied'] }, expected: true },
  { name: 'NEGATIVE money noun phrase: in monthly support cost is never revenue', value: 190000, unit: 'GBP/month',
    brief: 'Our bakery earns revenue and pays £190,000 in monthly support cost.',
    scope: { target: ['monthly revenue'], others: ['Monthly support cost'] }, expected: false },
  { name: 'per-one link: each price rise adds the stated monthly revenue', value: 1200, unit: 'GBP/month',
    brief: 'Each 1% price rise adds £1,200 a month to monthly recurring revenue before churn.',
    scope: { target: ['Price increase', 'monthly recurring revenue'], others: ['Customers lost to price rise', 'Starter subscribers'] }, expected: true },
  { name: 'NEGATIVE per-one link: the same amount acts on support cost', value: 1200, unit: 'GBP/month',
    brief: 'Each 1% price rise adds £1,200 a month to support cost before churn, while monthly recurring revenue is uncertain.',
    scope: { target: ['Price increase', 'monthly recurring revenue'], others: ['Customers lost to price rise', 'Support cost'] }, expected: false },
  { name: 'NEGATIVE per-one source: a capacity rise producing revenue never credits the price-rise link', value: 1200, unit: 'GBP/month',
    brief: 'Each 1% capacity rise adds £1,200 a month to monthly recurring revenue before churn; the price increase effect is unknown.',
    scope: { target: ['Price increase', 'monthly recurring revenue'], others: ['Capacity increase', 'Customers lost to price rise'] }, expected: false },
  { name: 'NEGATIVE per-one source: starter price effect never credits the existing price effect', value: 1200, unit: 'GBP/month',
    brief: 'Each 1% starter price rise adds £1,200 a month to monthly recurring revenue; the existing price effect is unknown.',
    scope: { target: ['Existing price increase', 'monthly recurring revenue'], others: ['Starter price rise', 'Existing customers'] }, expected: false },
  { name: 'support per subscriber: singular subscriber names the link', value: 6, unit: 'GBP/month',
    brief: 'Each starter subscriber costs about £6 a month in support.',
    scope: { target: ['Starter subscribers', 'Starter support cost'], others: ['Existing customers', 'Existing support cost'] }, expected: true },
  { name: 'NEGATIVE support per subscriber: existing support cost never credits starter support', value: 6, unit: 'GBP/month',
    brief: 'Each existing customer costs about £6 a month in support; starter support is unknown.',
    scope: { target: ['Starter subscribers', 'Starter support cost'], others: ['Existing customers', 'Existing support cost'] }, expected: false },
];
for (const row of rows) it(row.name, () => {
  expect(figureTheUserWroteFor(row.value, row.unit, row.brief, row.scope)).toBe(row.expected);
});
