/**
 * V5 Lane 2 — deterministic chip-quality finalizer.
 *
 * A PURE function applied to the FINAL `suggested_actions` list at the
 * single V5 egress chokepoint (`sanitiseOlumiResponseForEgress`, after the
 * per-string entity-id scrub). It is the comprehensive quality SSOT layered
 * on top of the existing per-branch mechanisms (`chip-generator.ts` `cap()`,
 * `validateAndFilterChips`, `applyChipFloor`, and the in-turn flip dedupe in
 * `turn-executor.ts`), which all remain intact.
 *
 * SAFE-BY-DEFAULT. Many V5 surfaces emit chips that are NOT generated by
 * `chip-generator.ts` — deterministic clarification / candidate-pick lists
 * (`edit_clarify_*`, `chip_clarify_*`, `chip_factor_affect_*`,
 * `chip_proposal_*`) and coaching prefill chips (`chip_<sha>` from
 * `chipIdForText`). These have no `action_type` and arbitrary ids, and the
 * user must be able to see and pick ALL of them. So the finalizer NEVER drops
 * a chip merely because its id is unfamiliar, NEVER collapses distinct chips
 * by `action_type`, and NEVER count-trims a candidate-pick list. The only
 * removals are genuinely safe:
 *
 *   1. UNSAFE — a leakage token (handler id / schema term / `prop_`/`chip_`/
 *      `graph_hash`/`{"`) in the visible label or message, or a non-exempt
 *      raw-decimal leak. (NOT em dash — see chip-safety.ts.)
 *   2. BLANK — empty label or message after scrub (genuinely unusable).
 *   3. EXACT or NEAR DUPLICATE — same id, or normalized-equal label, or
 *      normalized-equal message (keep first; proposals partitioned first so a
 *      generic near-duplicate can never dedupe a proposal away).
 *
 * Budget: only the SUGGESTION family (`chip_action_*` / `chip_prompt_*`) plus
 * validated proposals (`prop_`) share the ≤{@link MAX_CHIPS} budget — the
 * Lane 2 "2–3 useful suggestions" target. Proposals are kept first and
 * survive the budget unless unsafe. Candidate / clarification chips are NOT
 * counted and are never trimmed (their own composers already size them).
 *
 * Never pads: an empty safe set yields no chips. Idempotent: a second pass
 * drops/dedupes/trims nothing (the chokepoint runs this up to 4× per
 * response, so the caller guards the aggregate telemetry emit on a real
 * change). Chips are derived from structured state upstream; this layer never
 * reads model response text and never invents or rewrites a chip.
 */

import { log } from '../../utils/telemetry.js';
import type { SuggestedAction } from './types.js';
import { findChipLeakToken, findChipRawDecimalLeak } from './chip-safety.js';

/** The useful 2–3 chip budget cap for the SUGGESTION family (mirrors chip-generator). */
const MAX_CHIPS = 3;

const PROPOSAL_ID_PREFIX = 'prop_';
/** Ids emitted by `chip-generator.ts` (`executableChip`/`promptChip`). The budget applies to these. */
const SUGGESTION_ID_PREFIXES = ['chip_action_', 'chip_prompt_'];

/** Proposal / graph-mutation handler ids. */
const MUTATION_ACTION_TYPES = new Set<string>([
  'add_constraint',
  'set_factor_value',
  'adjust_edge_strength',
]);

const RERUN_RE = /rerun|re-run|re_run/i;

export type ChipCategory =
  | 'proposal'
  | 'analysis_followup'
  | 'stale_rerun'
  | 'graph_edit'
  | 'coaching'
  | 'candidate'
  | 'generic'
  | 'unsafe';

/** Budget cohort: the ≤MAX_CHIPS pool covers `proposal` + `suggestion`; `candidate` is never trimmed. */
type BudgetClass = 'proposal' | 'suggestion' | 'candidate';

export interface ChipFinalizeReport {
  readonly input: number;
  readonly output: number;
  readonly dropped_unsafe: number;
  /** Subset of `dropped_unsafe` that were dropped for a raw-decimal leak. */
  readonly dropped_raw_decimal: number;
  /** Chips dropped because their label/message was blank after scrub. */
  readonly dropped_generic: number;
  readonly deduped: number;
  readonly proposal_protected: number;
  readonly over_budget_trimmed: number;
}

export interface ChipFinalizeResult {
  readonly chips: readonly SuggestedAction[];
  readonly report: ChipFinalizeReport;
}

interface MutableReport {
  input: number;
  output: number;
  dropped_unsafe: number;
  dropped_raw_decimal: number;
  dropped_generic: number;
  deduped: number;
  proposal_protected: number;
  over_budget_trimmed: number;
}

interface ClassifiedChip {
  readonly chip: SuggestedAction;
  readonly cat: ChipCategory;
}

function strField(chip: SuggestedAction, key: 'id' | 'label' | 'message'): string {
  const v = (chip as Record<string, unknown>)[key];
  return typeof v === 'string' ? v : '';
}

function actionTypeOf(chip: SuggestedAction): string | null {
  const at = (chip as { action_type?: unknown }).action_type;
  return typeof at === 'string' && at.length > 0 ? at : null;
}

function isBlank(s: string): boolean {
  return s.trim().length === 0;
}

function normalizeText(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/[.!?,;:\s]+$/u, '');
}

/**
 * A *validated* proposal-backed chip: the `prop_` id prefix AND a proposal
 * `action_type`. Used both for the budget/protection cohort and the
 * raw-decimal exemption — never trusts the `prop_` prefix alone.
 */
function isValidatedProposalChip(chip: SuggestedAction): boolean {
  const id = strField(chip, 'id');
  const at = actionTypeOf(chip);
  return id.startsWith(PROPOSAL_ID_PREFIX) && at !== null && MUTATION_ACTION_TYPES.has(at);
}

function isSuggestionId(id: string): boolean {
  return SUGGESTION_ID_PREFIXES.some((p) => id.startsWith(p));
}

function budgetClass(chip: SuggestedAction): BudgetClass {
  if (isValidatedProposalChip(chip)) return 'proposal';
  if (isSuggestionId(strField(chip, 'id'))) return 'suggestion';
  return 'candidate';
}

function classify(chip: SuggestedAction): ChipCategory {
  const label = strField(chip, 'label');
  const message = strField(chip, 'message');
  const id = strField(chip, 'id');
  const at = actionTypeOf(chip);
  const validatedProposal = isValidatedProposalChip(chip);

  // 1. Unsafe — leakage token in visible copy (label/message only; the id is
  //    a machine field and is never scanned, else every `chip_*`/`prop_*`
  //    chip would self-flag).
  if (findChipLeakToken(label) !== null || findChipLeakToken(message) !== null) {
    return 'unsafe';
  }
  // 2. Unsafe — non-exempt raw-decimal leak in the VISIBLE button LABEL only.
  //    A bare/high-precision decimal in a label (e.g. "Re-run 0.4732") is
  //    display noise. The `message` is the submit prompt rather than a display
  //    surface and far more likely to carry a legitimately value-bearing
  //    sentence, so a decimal there does NOT drop the chip — leak tokens
  //    (handler ids / schema terms / raw ids), which are never legitimate, are
  //    still checked in both fields above.
  if (findChipRawDecimalLeak(label, '', { isValidatedProposal: validatedProposal })) {
    return 'unsafe';
  }
  // 3. Generic/noisy — blank after scrub is the ONLY drop-as-generic reason.
  //    An unfamiliar id is NOT noise: deterministic clarification / candidate
  //    and coaching chips legitimately use ids outside the chip_action_ /
  //    chip_prompt_ families and must survive.
  if (isBlank(label) || isBlank(message)) return 'generic';

  // 4. Validated proposal-backed.
  if (validatedProposal) return 'proposal';

  // 5. Executable chips — any valid action_type is grounded.
  if (at !== null) {
    if (at === 'run_analysis' && RERUN_RE.test(id)) return 'stale_rerun';
    if (
      at === 'explain_results' ||
      at === 'explain_result' ||
      at === 'what_would_flip' ||
      at === 'explain_from_structure' ||
      at === 'compare_options'
    ) {
      return 'analysis_followup';
    }
    if (MUTATION_ACTION_TYPES.has(at)) return 'graph_edit';
    return 'analysis_followup';
  }

  // 6. Prompt chips from the generator's suggestion family.
  if (isSuggestionId(id)) {
    if (RERUN_RE.test(id)) return 'stale_rerun';
    if (id.includes('explore') || id.includes('flip')) return 'analysis_followup';
    return 'coaching';
  }

  // 7. Any other non-blank, non-leaking chip — a deterministic clarification /
  //    candidate-pick or coaching chip. KEPT (never trimmed by the budget).
  return 'candidate';
}

function unsafeDropReason(chip: SuggestedAction): 'egress_leak_token' | 'raw_decimal' {
  const label = strField(chip, 'label');
  const message = strField(chip, 'message');
  if (findChipLeakToken(label) !== null || findChipLeakToken(message) !== null) {
    return 'egress_leak_token';
  }
  return 'raw_decimal';
}

/**
 * Dedupe by exact id, normalized label, and normalized message (keep first).
 * NO `action_type` collapse — two distinct chips that merely share a handler
 * id (e.g. ambiguous short-confirm candidates both routing to `run_analysis`)
 * are legitimately different choices and BOTH survive.
 */
function dedupe(items: readonly ClassifiedChip[], report: MutableReport): ClassifiedChip[] {
  const out: ClassifiedChip[] = [];
  const seenIds = new Set<string>();
  const seenLabels = new Set<string>();
  const seenMessages = new Set<string>();

  for (const item of items) {
    const id = strField(item.chip, 'id');
    const nLabel = normalizeText(strField(item.chip, 'label'));
    const nMessage = normalizeText(strField(item.chip, 'message'));

    if (id !== '' && seenIds.has(id)) {
      report.deduped++;
      continue;
    }
    if (nLabel !== '' && seenLabels.has(nLabel)) {
      report.deduped++;
      continue;
    }
    if (nMessage !== '' && seenMessages.has(nMessage)) {
      report.deduped++;
      continue;
    }

    if (id !== '') seenIds.add(id);
    if (nLabel !== '') seenLabels.add(nLabel);
    if (nMessage !== '') seenMessages.add(nMessage);
    out.push(item);
  }

  return out;
}

/**
 * Proposal-protected budget. The `proposal` + `suggestion` cohort shares a
 * pool of {@link MAX_CHIPS}; proposals (partitioned first) consume it first so
 * they survive while excess generated suggestions are trimmed. `candidate`
 * chips are never counted or trimmed — their composers size them and the user
 * must see every option.
 */
function applyBudget(items: readonly ClassifiedChip[], report: MutableReport): ClassifiedChip[] {
  const out: ClassifiedChip[] = [];
  let pooledUsed = 0;
  for (const item of items) {
    const bc = budgetClass(item.chip);
    if (bc === 'candidate') {
      out.push(item);
      continue;
    }
    if (pooledUsed < MAX_CHIPS) {
      out.push(item);
      pooledUsed++;
      if (bc === 'proposal') report.proposal_protected++;
    } else {
      report.over_budget_trimmed++;
    }
  }
  return out;
}

/** Options for {@link finalizeChips}. */
export interface FinalizeChipsOptions {
  /**
   * Emit a per-chip `v5.chip.suppressed` `log.warn` for each dropped chip.
   * Defaults to `true` for the egress call (the canonical observability
   * point). The pending-derivation pre-pass
   * (`derivePendingActionsFromFinalizedChips`) passes `false` so a chip drop
   * is logged once, at egress, not also before commit.
   */
  readonly logSuppressions?: boolean;
}

/**
 * Deterministic chip-quality finalizer. See module header for the ordered
 * guarantees. Pure: no I/O beyond a structured `log.warn` per dropped chip
 * (no user copy logged — chip ids and a reason class only), which the caller
 * can silence via `opts.logSuppressions = false`.
 */
export function finalizeChips(
  chips: readonly SuggestedAction[],
  opts: FinalizeChipsOptions = {},
): ChipFinalizeResult {
  const logSuppressions = opts.logSuppressions !== false;
  const report: MutableReport = {
    input: chips.length,
    output: 0,
    dropped_unsafe: 0,
    dropped_raw_decimal: 0,
    dropped_generic: 0,
    deduped: 0,
    proposal_protected: 0,
    over_budget_trimmed: 0,
  };

  // Phase A — classify, drop unsafe + blank (input order preserved).
  const kept: ClassifiedChip[] = [];
  for (const chip of chips) {
    const cat = classify(chip);
    if (cat === 'unsafe') {
      report.dropped_unsafe++;
      const reason = unsafeDropReason(chip);
      if (reason === 'raw_decimal') report.dropped_raw_decimal++;
      if (logSuppressions) {
        log.warn(
          { event: 'v5.chip.suppressed', reason, chip_id: strField(chip, 'id') || null },
          'V5 egress chip-finalizer: chip dropped (unsafe)',
        );
      }
      continue;
    }
    if (cat === 'generic') {
      report.dropped_generic++;
      if (logSuppressions) {
        log.warn(
          { event: 'v5.chip.suppressed', reason: 'blank', chip_id: strField(chip, 'id') || null },
          'V5 egress chip-finalizer: chip dropped (blank)',
        );
      }
      continue;
    }
    kept.push({ chip, cat });
  }

  // Phase B — partition proposals to the front (stable) so a generic
  // near-duplicate can never dedupe a proposal away, and proposals consume the
  // budget pool first.
  const proposalsFirst: ClassifiedChip[] = [
    ...kept.filter((i) => i.cat === 'proposal'),
    ...kept.filter((i) => i.cat !== 'proposal'),
  ];

  // Phase C — dedupe (exact id + near-duplicate, keep first).
  const deduped = dedupe(proposalsFirst, report);

  // Phase D — proposal-protected budget over the suggestion cohort only.
  const finalItems = applyBudget(deduped, report);

  const out = finalItems.map((i) => i.chip);
  report.output = out.length;

  return { chips: out, report };
}
