import { describe, expect, it } from 'vitest';
import type { HandlerFact } from '@talchain/schemas/orchestrator';
import { buildRunDelta, type SelectedRunIdentity, type SelectedRunPair } from '../build-run-delta.js';
import { PRESENT_PAIR, REFUSED_PAIR, runAnalysisFact } from '../../context/__tests__/run-delta-fixtures.js';
import control from './selected-pair-default-control.json';

const scenario = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const prior: SelectedRunIdentity = { scenario_id: scenario, run_id: 'recorded-prior',
  graph_hash_at_run: 'a'.repeat(16), computed_at: '2026-06-06T00:00:00.000Z' };
const current: SelectedRunIdentity = { scenario_id: scenario, run_id: 'recorded-current',
  graph_hash_at_run: 'b'.repeat(16), computed_at: '2026-06-07T00:00:00.000Z' };
function recorded(identity: SelectedRunIdentity, a: number, mayName = true): HandlerFact {
  const fact = runAnalysisFact([{ id: 'opt-a', win: a }, { id: 'opt-b', win: 1 - a }],
    identity.run_id, identity.graph_hash_at_run, identity.computed_at, mayName);
  const result = (fact as unknown as { result: Record<string, unknown> }).result;
  return { ...fact, result: { ...result, ...identity } } as unknown as HandlerFact;
}
const facts = [recorded(current, 0.45), recorded(prior, 0.62)];
const run = (selectedPair: SelectedRunPair, priorFacts = facts) =>
  buildRunDelta({ priorFacts, selectedPair, mayNameLeadingOption: true });

// Captured from the unmodified d928 builder, not generated by this implementation.
describe('selected pair preserves chronological callers and historical truth', () => {
  it('retains the default present, withheld and refused fixture bytes', () => {
    expect(control.baseline).toBe('d928fbf1ade6c5119618f87478c2da1fb4aec945');
    expect(buildRunDelta({ priorFacts: PRESENT_PAIR, mayNameLeadingOption: true })).toStrictEqual(control.present);
    expect(buildRunDelta({ priorFacts: PRESENT_PAIR, mayNameLeadingOption: false })).toStrictEqual(control.withheld);
    expect(buildRunDelta({ priorFacts: REFUSED_PAIR, mayNameLeadingOption: true })).toStrictEqual(control.refused);
  });

  it('computes FROM to TO even when that reverses chronological order', () => {
    const original = JSON.stringify(facts);
    const forward = run({ prior, current });
    const reverse = run({ prior: current, current: prior });
    expect(forward.kind).toBe('ok'); expect(reverse.kind).toBe('ok');
    if (forward.kind !== 'ok' || reverse.kind !== 'ok') return;
    expect(forward.delta.endpoints).toStrictEqual({ prior: { run_id: prior.run_id, computed_at: prior.computed_at },
      current: { run_id: current.run_id, computed_at: current.computed_at } });
    expect(reverse.delta.endpoints).toStrictEqual({ prior: { run_id: current.run_id, computed_at: current.computed_at },
      current: { run_id: prior.run_id, computed_at: prior.computed_at } });
    const a = forward.delta.win_probabilities.find(row => row.option_id === 'opt-a')!;
    const b = reverse.delta.win_probabilities.find(row => row.option_id === 'opt-a')!;
    expect(a).toMatchObject({ prior: 0.62, current: 0.45 });
    expect(b).toMatchObject({ prior: 0.45, current: 0.62 });
    expect(JSON.stringify(facts)).toBe(original);
  });

  it('ignores a newer third Run when an explicit pair is selected', () => {
    const latest = recorded({ ...current, run_id: 'unselected-newest', computed_at: '2026-06-08T00:00:00.000Z' }, 0.99);
    expect(run({ prior, current }, [latest, ...facts])).toStrictEqual(run({ prior, current }));
  });

  it.each([
    { run_id: 'unknown-run' },
    { graph_hash_at_run: 'c'.repeat(16) },
    { graph_hash_at_run: 'a'.repeat(64) },
    { computed_at: '2026-06-06T01:00:00.000Z' },
    { computed_at: '2026-06-06T00:00:00+00:00' },
    { scenario_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' },
  ])('never falls back to newest two for an unconfirmed identity: %j', (change) => {
    expect(run({ prior: { ...prior, ...change }, current })).toStrictEqual({ kind: 'none', reason: 'insufficient_runs' });
  });

  it('refuses unsuccessful and ambiguous matching records', () => {
    const failed = { ...facts[1]!, noop: true };
    expect(run({ prior, current }, [facts[0]!, failed])).toStrictEqual({ kind: 'none', reason: 'insufficient_runs' });
    expect(run({ prior, current }, [...facts, facts[1]!])).toStrictEqual({ kind: 'none', reason: 'insufficient_runs' });
  });

  it('keeps each selected Run’s own leader permission', () => {
    const built = run({ prior, current }, [recorded(current, 0.45, false), recorded(prior, 0.62)]);
    expect(built.kind).toBe('ok');
    if (built.kind !== 'ok') return;
    expect(built.delta.leader).not.toHaveProperty('current_leading_option_id');
    expect(built.delta.leader.prior_leading_option_id).toBe('opt-a');
    expect(built.delta.win_probabilities).toStrictEqual([]);
    expect(built.delta.leader.changed).toBe(false);
  });
});
