import { readFileSync } from 'node:fs';
import { admitCandidateModel } from './admit-model.js';
import { assessAnalysisAdmissibility } from './analysis-admissibility.js';
import { admitCandidateLinks, noUnmarkedMagnitudes } from './admit-candidate.js';
const base = new URL('./__tests__/fixtures/', import.meta.url);
const faithful = JSON.parse(readFileSync(new URL('faithful.json', base),'utf8'));
const widened = JSON.parse(readFileSync(new URL('widened.json', base),'utf8'));
const m = admitCandidateModel(faithful as any, widened as any);
console.log('nodes', m.nodes.length, 'edges', m.edges.length, 'defaulted', m.edges.filter(e=>e.defaulted===true).length, 'constraints', m.goal_constraints.length);
console.log('withheld', JSON.stringify(m.withheld.map(w=>[w.from,w.to,w.reason])));
const goal = m.nodes.find(n=>n.kind==='goal');
const into = m.edges.filter(e=>e.to===goal!.id);
console.log('goal', goal!.id, 'edgesIntoGoal', into.length, 'projectedIntoGoal', into.filter(e=>e.defaulted===true).length);
const r = assessAnalysisAdmissibility(m);
console.log('verdict', r.verdict, 'reasons', JSON.stringify(r.reasons.map(x=>x.code)));
const ai = admitCandidateLinks([{from:'a',to:'b',direction:'positive',provenance:'ai_proposed',strength_mean:0.83}]);
console.log('ai-authored edge:', JSON.stringify(ai.edges[0]));
console.log('noUnmarkedMagnitudes(ai-authored) =', noUnmarkedMagnitudes(ai), '<- doc: true when authored OR defaulted');
