/**
 * ⭐⭐ ROADMAP 2.1266 — the option-effect WRITE PATH resolver.
 *
 * ═══ WHY THIS FILE EXISTS ═══
 * On deployed `293da07` the product's repair copy advises, verbatim:
 *
 *   "Tell me what it changes, like this: Set the <option> option's effect on
 *    <factor> to 0.6"
 *
 * …and sending exactly that returns "…still has no effect value…" with nothing
 * written. No wire verb on the build could set an option's effect value: the
 * `system_event` types carry none, and the chat path depended on the edit LLM
 * emitting the sanctioned intervention `update_node` — which, on the witnessed
 * J4 t5 turn, it did not. P8 at its purest: the product asked a question it
 * could not accept the answer to.
 *
 * ⚠ THE CORPUS IS THE WIRE'S, NOT MINE (trap 22 / trap 16). Both the graph and
 * the two message shapes are the VERBATIM captures in
 * `__tests__/fixtures/witness-2026-08-17/j4-wrong-entity-write.json`
 * (deployed CEE `8be62df`, scenario 289c2690…). `wire.t4_chip_message` is the
 * product's OWN advised phrasing, generated by
 * `buildConfigureOptionAdvisedFormat` on a real turn — a self-authored fixture
 * would have encoded my model of the advised format rather than the product's.
 * Historic record: append, never edit (trap 14b).
 *
 * ⚠ EXTRACTOR-DELETION OBLIGATION (trap 19). Deleting the option-label
 * resolution in `matchLabels`, or the `EFFECT_FRAMED_TRIGGERS` gate, or the
 * `readOptionEffectValue` scale guard MUST turn assertions here RED. The
 * DISCRIMINATING PAIR at the bottom is the binding proof: renaming the option
 * the message names withdraws the write (RED-equivalent), while renaming a
 * DIFFERENT option leaves the verdict byte-identical (GREEN) — neither alone
 * shows identity binding, the pair does.
 */

import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';

import {
  OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS,
  OPTION_EFFECT_WRITE_KNOWN_DROPPED,
  buildOptionEffectRawOperation,
  formatOptionEffectWriteAck,
  linkedFactorsOf,
  readCommittedOptionEffect,
  readOptionEffectValue,
  resolveOptionEffectWrite,
} from '../option-effect-write.js';
import { detectConfigureOptionIntent, projectOptionLabels } from '../configure-option-intent.js';
import { GraphV3, type GraphV3T } from '../../../schemas/cee-v3.js';

// ── the witnessed bytes ────────────────────────────────────────────

interface WitnessFixture {
  readonly ids: {
    readonly option_id: string;
    readonly option_label: string;
    readonly factor_id: string;
    readonly factor_label: string;
  };
  readonly wire: { readonly t5_user_message: string; readonly t4_chip_message: string };
  readonly draft_graph: { nodes: Array<Record<string, unknown>>; edges: Array<Record<string, unknown>> };
}

const WITNESS = JSON.parse(
  readFileSync(
    new URL(
      '../../__tests__/fixtures/witness-2026-08-17/j4-wrong-entity-write.json',
      import.meta.url,
    ),
    'utf8',
  ),
) as WitnessFixture;

const OPTION_ID = WITNESS.ids.option_id;
const OPTION_LABEL = WITNESS.ids.option_label;
const FACTOR_ID = WITNESS.ids.factor_id;
const FACTOR_LABEL = WITNESS.ids.factor_label;

/** The SECOND option in the witnessed graph — a near-miss label, not a nest. */
const SIBLING_OPTION_ID = '862169d7';
const SIBLING_OPTION_LABEL = 'Subcontract inner-city runs to green courier';

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const graph = () => clone(WITNESS.draft_graph);

/** The product's own advised sentence, verbatim from the wire. */
const ADVISED_SENTENCE = WITNESS.wire.t4_chip_message;
/** The user's own effect request, verbatim from the wire. */
const USER_EFFECT_SENTENCE = WITNESS.wire.t5_user_message;

function instantiate(template: string, option = OPTION_LABEL, factor = FACTOR_LABEL): string {
  return template.replace(/\{option\}/g, option).replace(/\{factor\}/g, factor);
}

describe('2.1266 — the fixture is the wire it claims to be (positive control)', () => {
  it('the advised sentence is the product\'s own builder output, and it strict-parses as a graph', () => {
    // A fixture that had drifted from the advised format would make every
    // assertion below a statement about a sentence the product never emits.
    expect(ADVISED_SENTENCE).toContain(`${OPTION_LABEL} option's effect on ${FACTOR_LABEL}`);
    expect(ADVISED_SENTENCE).toContain('0.12');
    expect(GraphV3.safeParse(graph()).success).toBe(true);
    // The option is genuinely unconfigured and genuinely wired to the factor —
    // without both, a "the write landed" assertion proves nothing.
    const parsed = GraphV3.parse(graph()) as GraphV3T;
    const option = parsed.nodes.find((n) => n.id === OPTION_ID)!;
    expect((option as { interventions?: unknown }).interventions).toEqual({});
    expect(linkedFactorsOf(parsed, OPTION_ID).map((f) => f.id)).toEqual([FACTOR_ID]);
  });
});

describe('ACCEPTANCE 1 — the product\'s own advised sentence binds a write', () => {
  it('resolves the advised sentence to option, factor and value BY ID', () => {
    const resolution = resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() });
    expect(resolution).toEqual({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      optionLabel: OPTION_LABEL,
      factorId: FACTOR_ID,
      factorLabel: FACTOR_LABEL,
      value: 0.12,
    });
  });

  it('resolves the user\'s own wire-witnessed effect request the same way', () => {
    const resolution = resolveOptionEffectWrite({ message: USER_EFFECT_SENTENCE, graph: graph() });
    expect(resolution).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      factorId: FACTOR_ID,
      value: 0.12,
    });
  });

  it('the advised sentence with the copy\'s own example value (0.6) also binds', () => {
    const message = ADVISED_SENTENCE.replace('0.12', '0.6');
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({
      matched: true,
      kind: 'write',
      value: 0.6,
    });
  });

  it('composes the served prompt\'s EXAMPLE-2 operation vocabulary, bound to the ids', () => {
    const resolution = resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'write') throw new Error('expected a write');
    const raw = buildOptionEffectRawOperation(resolution);
    expect(raw.op).toBe('update_node');
    // The path is the producer's own: `src/prompts/edit-graph-v6.ts` EXAMPLE 2.
    expect(raw.path).toBe(`/nodes/${OPTION_ID}/data/interventions/${FACTOR_ID}`);
    expect(raw.value).toEqual({ value: 0.12 });
    expect(raw.old_value).toBeNull();
    // No user-scale trio: this writer performs no conversion (see the header).
    expect(Object.keys(raw.value as object)).toEqual(['value']);
  });
});

describe('ACCEPTANCE 3 — an explicit factor-BASELINE edit is NOT misrouted', () => {
  it('the W1 shape WITHOUT effect framing is not claimed (trigger option_value_set)', () => {
    // The guard's own W1 example, retargeted at the witnessed graph. It names
    // the option, names a factor the option IS wired to, and carries a value —
    // and asks for the factor's own value, not the option's effect on it.
    const message =
      `For the ${OPTION_LABEL} option, our ${FACTOR_LABEL} assumption is stale — `
      + `change ${FACTOR_LABEL} to 0.3.`;
    expect(detectConfigureOptionIntent(message, projectOptionLabels(graph().nodes))).toEqual({
      matched: true,
      trigger: 'option_value_set',
    });
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('the same shape saying "baseline" is not claimed even when effect-framed', () => {
    const message =
      `For the ${OPTION_LABEL} option, set the effect of ${FACTOR_LABEL} — `
      + `actually, change the ${FACTOR_LABEL} baseline to 0.3.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'baseline_framing',
    });
  });

  it('OPPOSITE-DIRECTION TWIN — the effect-framed sentence over the SAME pair IS claimed', () => {
    // Without this twin the two assertions above would pass on a resolver that
    // claims nothing at all.
    expect(
      resolveOptionEffectWrite({
        message: `Set the ${OPTION_LABEL} option's effect on ${FACTOR_LABEL} to 0.3.`,
        graph: graph(),
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: OPTION_ID, value: 0.3 });
  });

  it('the excluded-trigger set names every trigger it refuses, with a reason', () => {
    expect(OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS.map((e) => e.trigger).sort()).toEqual([
      'chip_prefix',
      'option_value_set',
    ]);
    for (const entry of OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS) {
      expect(entry.reason.length).toBeGreaterThan(20);
    }
  });

  it('the bare configure chip message is not claimed (no value to write)', () => {
    const message = `Help me configure ${OPTION_LABEL}.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    expect(resolution.matched).toBe(false);
  });
});

describe('ACCEPTANCE 4 — an unbindable request asks, and writes nothing', () => {
  it('TWO options named → ask which option, with a complete candidate per option', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect and the ${SIBLING_OPTION_LABEL} option's `
      + `effect on ${FACTOR_LABEL} to 0.4.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('option');
    expect(resolution.value).toBe(0.4);
    expect(resolution.optionLabels.sort()).toEqual([OPTION_LABEL, SIBLING_OPTION_LABEL].sort());
    expect(resolution.candidates.map((c) => c.optionId).sort()).toEqual(
      [OPTION_ID, SIBLING_OPTION_ID].sort(),
    );
    for (const candidate of resolution.candidates) {
      expect(candidate.factorId).toBe(FACTOR_ID);
    }
  });

  it('TWO of one option\'s linked factors named → ask which factor', () => {
    // The sibling option is wired to three factors; name two of them.
    const message =
      `Set the ${SIBLING_OPTION_LABEL} option's effect on ${FACTOR_LABEL} and `
      + `Annual clean-air charge burden to 0.4.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('factor');
    expect(resolution.candidates.map((c) => c.factorId).sort()).toEqual(
      [FACTOR_ID, '90246f0d'].sort(),
    );
    expect(resolution.candidates.every((c) => c.optionId === SIBLING_OPTION_ID)).toBe(true);
  });

  it('a NESTED label match is not an ambiguity — the longer phrase wins', () => {
    // "Expand" only matched because it is a prefix of "Expand to Leeds":
    // asking the user to choose between a phrase and part of itself would be
    // the ambiguity theatre this rule exists to avoid.
    const g = graph();
    g.nodes.push(
      { id: 'opt_expand', kind: 'option', label: 'Expand', interventions: {} },
      { id: 'opt_expand_leeds', kind: 'option', label: 'Expand to Leeds', interventions: {} },
      {
        id: 'fac_capex',
        kind: 'factor',
        label: 'Capital expenditure',
        observed_state: { value: 0.5 },
      },
    );
    g.edges.push({
      from: 'opt_expand_leeds',
      to: 'fac_capex',
      strength: { mean: 1, std: 0.01 },
      exists_probability: 1,
      effect_direction: 'positive',
    } as Record<string, unknown>);
    expect(GraphV3.safeParse(g).success).toBe(true);
    const resolution = resolveOptionEffectWrite({
      message: "Set the Expand to Leeds option's effect on Capital expenditure to 0.6.",
      graph: g,
    });
    expect(resolution).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: 'opt_expand_leeds',
      factorId: 'fac_capex',
    });
  });

  it('an option named with NO linked factor named DECLINES rather than asking', () => {
    // Deliberate: the edit LLM can paraphrase-match a factor name this exact
    // reader cannot, and can add a missing structural edge. Pre-empting it
    // would remove a capability, not add one.
    const message = `Set the ${OPTION_LABEL} option's effect to 0.4.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });

  it('a factor NOT wired to the named option DECLINES (the edit lane can wire it)', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect on Annual clean-air charge burden to 0.4.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });
});

describe('ACCEPTANCE 5 — a SURVIVING option configures after structural deletes', () => {
  /** Remove every option except the survivor, and every edge touching them. */
  function afterStructuralDeletes(survivorId: string) {
    const g = graph();
    const removed = new Set(
      g.nodes.filter((n) => n.kind === 'option' && n.id !== survivorId).map((n) => n.id as string),
    );
    g.nodes = g.nodes.filter((n) => !removed.has(n.id as string));
    g.edges = g.edges.filter(
      (e) => !removed.has(e.from as string) && !removed.has(e.to as string),
    );
    return g;
  }

  it('the advised sentence still binds, by the SAME ids, on the post-delete graph', () => {
    const g = afterStructuralDeletes(OPTION_ID);
    // Positive control: the deletes really happened.
    expect(g.nodes.filter((n) => n.kind === 'option')).toHaveLength(1);
    expect(g.nodes.some((n) => n.id === SIBLING_OPTION_ID)).toBe(false);
    expect(GraphV3.safeParse(g).success).toBe(true);

    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      optionLabel: OPTION_LABEL,
      factorId: FACTOR_ID,
      factorLabel: FACTOR_LABEL,
      value: 0.12,
    });
  });

  it('the now-ambiguous ask collapses to a write once the sibling option is deleted', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect and the ${SIBLING_OPTION_LABEL} option's `
      + `effect on ${FACTOR_LABEL} to 0.4.`;
    // Before: ambiguous.
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({ kind: 'ask' });
    // After the sibling is deleted, the only option the message can mean is
    // the survivor — resolved against the graph, never against a stale label
    // list.
    expect(
      resolveOptionEffectWrite({ message, graph: afterStructuralDeletes(OPTION_ID) }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: OPTION_ID, value: 0.4 });
  });
});

describe('ACCEPTANCE 6 — the DISCRIMINATING PAIR on the identity binding', () => {
  const BASELINE = {
    matched: true,
    kind: 'write',
    optionId: OPTION_ID,
    optionLabel: OPTION_LABEL,
    factorId: FACTOR_ID,
    factorLabel: FACTOR_LABEL,
    value: 0.12,
  };

  it('binds to the option the message NAMES', () => {
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() })).toEqual(
      BASELINE,
    );
  });

  it('RED HALF — rename THE NAMED option and the write withdraws', () => {
    // Nothing else changes: the same factor, the same edge, the same value,
    // and the graph still has exactly one unconfigured option wired to that
    // factor. A resolver bound by anything other than the option's own label→id
    // identity would still produce a write here.
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === OPTION_ID) node.label = 'A completely different courier plan';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'option_not_named',
    });
  });

  it('GREEN HALF — rename a DIFFERENT option and the verdict is byte-identical', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === SIBLING_OPTION_ID) node.label = 'A completely different courier plan';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual(BASELINE);
  });

  it('RED HALF (factor) — rename THE NAMED factor and the write withdraws', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === FACTOR_ID) node.label = 'Something else entirely';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });

  it('GREEN HALF (factor) — rename a factor the option is NOT wired to; verdict unchanged', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === '90246f0d') node.label = 'Something else entirely';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual(BASELINE);
  });

  it('REMOVING THE STRUCTURAL EDGE withdraws the write — "linked" is load-bearing', () => {
    const g = graph();
    g.edges = g.edges.filter((e) => !(e.from === OPTION_ID && e.to === FACTOR_ID));
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });
});

describe('the value grammar admits ONE model-unit number and nothing else', () => {
  it.each(OPTION_EFFECT_WRITE_KNOWN_DROPPED)('KNOWN-DROPPED: %s', (template) => {
    const message = instantiate(template);
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    expect(resolution.matched).toBe(false);
  });

  it('the KNOWN-DROPPED set is not vacuous — every member is effect-framed or baseline-framed', () => {
    // A member that failed the INTENT gate for an unrelated reason would be
    // pinning nothing about the value grammar.
    expect(OPTION_EFFECT_WRITE_KNOWN_DROPPED.length).toBeGreaterThanOrEqual(8);
    for (const template of OPTION_EFFECT_WRITE_KNOWN_DROPPED) {
      const message = instantiate(template);
      expect(message).toContain(OPTION_LABEL);
      expect(message).toContain(FACTOR_LABEL);
    }
  });

  it.each([
    ['0', 0],
    ['1', 1],
    ['0.6', 0.6],
    ['0.12', 0.12],
  ])('OPPOSITE-DIRECTION TWIN — "%s" is a model-unit value and IS claimed', (text, expected) => {
    const message = `Set the ${OPTION_LABEL} option's effect on ${FACTOR_LABEL} to ${text}.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({
      matched: true,
      kind: 'write',
      value: expected,
    });
  });

  it.each([
    ['a trailing full stop', 'to 0.6.', 0.6],
    ['an em-dash aside', 'to 0.12 — a share, no unit.', 0.12],
    ['a following clause', 'to 0.6 for now.', 0.6],
  ])('reads the value through %s', (_name, tail, expected) => {
    expect(readOptionEffectValue(`set the x option's effect on y ${tail}`)).toBe(expected);
  });

  it.each([
    ['currency', 'to £25000'],
    ['percent', 'to 12%'],
    // The class where the currency/percent guard is the ONLY thing standing:
    // both parse to an in-range, separator-free `1`. Added after the guard's
    // mutant SURVIVED against the original corpus.
    ['currency at a model-scale magnitude', 'to £1'],
    ['percent at a model-scale magnitude', 'to 1%'],
    ['a thousands separator', 'to 25,000'],
    ['an attached unit', 'to 0.6m'],
    ['above the model scale', 'to 40000'],
    ['a second assignment', 'to 0.6 and to 0.3'],
    ['no number at all', 'to high'],
  ])('refuses %s', (_name, tail) => {
    expect(readOptionEffectValue(`set the x option's effect on y ${tail}`)).toBeNull();
  });

  it('re-setting the value the model ALREADY holds declines rather than no-op-applying', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'value_already_set',
    });
    // Opposite-direction twin: a DIFFERENT value on the same, already-set pair
    // is a genuine revision and must still be claimed.
    expect(
      resolveOptionEffectWrite({ message: ADVISED_SENTENCE.replace('0.12', '0.7'), graph: g }),
    ).toMatchObject({ matched: true, kind: 'write', value: 0.7 });
  });

  it('an unparseable graph declines (the write must bind to real state)', () => {
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: { nodes: 'nope' } })).toEqual(
      { matched: false, reason: 'graph_unparseable' },
    );
  });
});

describe('the acknowledgement is read back from the COMMITTED graph (P5)', () => {
  it('reads the value the applied graph actually holds, through the shared reader', () => {
    const applied = graph();
    for (const node of applied.nodes) {
      if (node.id === OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(readCommittedOptionEffect(applied, OPTION_ID, FACTOR_ID)).toBe(0.12);
  });

  it('returns undefined when the write did not land — nothing may be claimed', () => {
    expect(readCommittedOptionEffect(graph(), OPTION_ID, FACTOR_ID)).toBeUndefined();
    expect(readCommittedOptionEffect(null, OPTION_ID, FACTOR_ID)).toBeUndefined();
    // The value landed on a DIFFERENT option — identity, not "a write landed".
    const elsewhere = graph();
    for (const node of elsewhere.nodes) {
      if (node.id === SIBLING_OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(readCommittedOptionEffect(elsewhere, OPTION_ID, FACTOR_ID)).toBeUndefined();
  });

  it('the acknowledgement states the committed value and makes no offer', () => {
    const ack = formatOptionEffectWriteAck({
      optionLabel: OPTION_LABEL,
      factorLabel: FACTOR_LABEL,
      committedValue: 0.12,
    });
    expect(ack).toContain(OPTION_LABEL);
    expect(ack).toContain(FACTOR_LABEL);
    expect(ack).toContain('0.12');
    // P8/P3: no promise about a run this module cannot derive.
    expect(ack.toLowerCase()).not.toContain('analys');
    expect(ack.toLowerCase()).not.toContain('rerun');
  });
});
