/**
 * ⭐⭐ ROADMAP 2.1266 — the option-effect WRITE PATH resolver.
 *
 * ═══ WHY THIS FILE EXISTS ═══
 * On deployed `293da07` the product's repair copy advises, verbatim:
 *
 *   "Tell me what it changes, like this: Set the <option> option's effect on
 *    <factor> to 0.6"
 *
 * …and sending exactly that returns "…still has no effect value…" with nothing
 * written. No wire verb on the build could set an option's effect value: the
 * `system_event` types carry none, and the chat path depended on the edit LLM
 * emitting the sanctioned intervention `update_node` — which, on the witnessed
 * J4 t5 turn, it did not. P8 at its purest: the product asked a question it
 * could not accept the answer to.
 *
 * ⚠ THE CORPUS IS THE WIRE'S, NOT MINE (trap 22 / trap 16). Both the graph and
 * the two message shapes are the VERBATIM captures in
 * `__tests__/fixtures/witness-2026-08-17/j4-wrong-entity-write.json`
 * (deployed CEE `8be62df`, scenario 289c2690…). `wire.t4_chip_message` is the
 * product's OWN advised phrasing, generated by
 * `buildConfigureOptionAdvisedFormat` on a real turn — a self-authored fixture
 * would have encoded my model of the advised format rather than the product's.
 * Historic record: append, never edit (trap 14b).
 *
 * ⚠ EXTRACTOR-DELETION OBLIGATION (trap 19). Deleting the option-label
 * resolution in `matchLabels`, or the `EFFECT_FRAMED_TRIGGERS` gate, or the
 * `readOptionEffectValue` scale guard MUST turn assertions here RED. The
 * DISCRIMINATING PAIR at the bottom is the binding proof: renaming the option
 * the message names withdraws the write (RED-equivalent), while renaming a
 * DIFFERENT option leaves the verdict byte-identical (GREEN) — neither alone
 * shows identity binding, the pair does.
 */

import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';

import {
  ANSWERED_ASK_KNOWN_DROPPED,
  ANSWERED_ASK_RESOLVED_LIMIT,
  OPTION_EFFECT_WRITE_ASK_RESOLVED_LIMIT,
  OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS,
  OPTION_EFFECT_WRITE_KNOWN_DROPPED,
  buildOptionEffectRawOperation,
  formatOptionEffectWriteAck,
  linkedFactorsOf,
  readCommittedOptionEffect,
  readOptionEffectValue,
  resolveOptionEffectWrite,
} from '../option-effect-write.js';
import { detectConfigureOptionIntent, projectOptionLabels } from '../configure-option-intent.js';
import { deriveAskedEffectPair, deriveMissingEffectPairs } from '../repair-value-binding.js';
import { readMissingValueAnswer } from '../missing-value-answer.js';
import { projectReadinessRecovery } from '../../coaching/readiness-recovery.js';
import { buildCanonicalAnalysisReadyFromGraph } from '../../../orchestrator/tools/analysis-ready-helper.js';
import { GraphV3, type GraphV3T } from '../../../schemas/cee-v3.js';

// ── the witnessed bytes ────────────────────────────────────────────

interface WitnessFixture {
  readonly ids: {
    readonly option_id: string;
    readonly option_label: string;
    readonly factor_id: string;
    readonly factor_label: string;
  };
  readonly wire: { readonly t5_user_message: string; readonly t4_chip_message: string };
  readonly draft_graph: { nodes: Array<Record<string, unknown>>; edges: Array<Record<string, unknown>> };
}

const WITNESS = JSON.parse(
  readFileSync(
    new URL(
      '../../__tests__/fixtures/witness-2026-08-17/j4-wrong-entity-write.json',
      import.meta.url,
    ),
    'utf8',
  ),
) as WitnessFixture;

const OPTION_ID = WITNESS.ids.option_id;
const OPTION_LABEL = WITNESS.ids.option_label;
const FACTOR_ID = WITNESS.ids.factor_id;
const FACTOR_LABEL = WITNESS.ids.factor_label;

/** The SECOND option in the witnessed graph — a near-miss label, not a nest. */
const SIBLING_OPTION_ID = '862169d7';
const SIBLING_OPTION_LABEL = 'Subcontract inner-city runs to green courier';

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const graph = () => clone(WITNESS.draft_graph);

/** The product's own advised sentence, verbatim from the wire. */
const ADVISED_SENTENCE = WITNESS.wire.t4_chip_message;
/** The user's own effect request, verbatim from the wire. */
const USER_EFFECT_SENTENCE = WITNESS.wire.t5_user_message;

function instantiate(template: string, option = OPTION_LABEL, factor = FACTOR_LABEL): string {
  return template.replace(/\{option\}/g, option).replace(/\{factor\}/g, factor);
}

describe('2.1266 — the fixture is the wire it claims to be (positive control)', () => {
  it('the advised sentence is the product\'s own builder output, and it strict-parses as a graph', () => {
    // A fixture that had drifted from the advised format would make every
    // assertion below a statement about a sentence the product never emits.
    expect(ADVISED_SENTENCE).toContain(`${OPTION_LABEL} option's effect on ${FACTOR_LABEL}`);
    expect(ADVISED_SENTENCE).toContain('0.12');
    expect(GraphV3.safeParse(graph()).success).toBe(true);
    // The option is genuinely unconfigured and genuinely wired to the factor —
    // without both, a "the write landed" assertion proves nothing.
    const parsed = GraphV3.parse(graph()) as GraphV3T;
    const option = parsed.nodes.find((n) => n.id === OPTION_ID)!;
    expect((option as { interventions?: unknown }).interventions).toEqual({});
    expect(linkedFactorsOf(parsed, OPTION_ID).map((f) => f.id)).toEqual([FACTOR_ID]);
  });
});

describe('ACCEPTANCE 1 — the product\'s own advised sentence binds a write', () => {
  it('resolves the advised sentence to option, factor and value BY ID', () => {
    const resolution = resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() });
    expect(resolution).toEqual({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      optionLabel: OPTION_LABEL,
      factorId: FACTOR_ID,
      factorLabel: FACTOR_LABEL,
      value: 0.12,
    });
  });

  it('resolves the user\'s own wire-witnessed effect request the same way', () => {
    const resolution = resolveOptionEffectWrite({ message: USER_EFFECT_SENTENCE, graph: graph() });
    expect(resolution).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      factorId: FACTOR_ID,
      value: 0.12,
    });
  });

  it('the advised sentence with the copy\'s own example value (0.6) also binds', () => {
    const message = ADVISED_SENTENCE.replace('0.12', '0.6');
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({
      matched: true,
      kind: 'write',
      value: 0.6,
    });
  });

  it('composes the served prompt\'s EXAMPLE-2 operation vocabulary, bound to the ids', () => {
    const resolution = resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'write') throw new Error('expected a write');
    const raw = buildOptionEffectRawOperation(resolution);
    expect(raw.op).toBe('update_node');
    // The path is the producer's own: `src/prompts/edit-graph-v6.ts` EXAMPLE 2.
    expect(raw.path).toBe(`/nodes/${OPTION_ID}/data/interventions/${FACTOR_ID}`);
    expect(raw.value).toEqual({ value: 0.12 });
    expect(raw.old_value).toBeNull();
    // No user-scale trio: this writer performs no conversion (see the header).
    expect(Object.keys(raw.value as object)).toEqual(['value']);
  });
});

describe('ACCEPTANCE 3 — an explicit factor-BASELINE edit is NOT misrouted', () => {
  it('the W1 shape WITHOUT effect framing is not claimed (trigger option_value_set)', () => {
    // The guard's own W1 example, retargeted at the witnessed graph. It names
    // the option, names a factor the option IS wired to, and carries a value —
    // and asks for the factor's own value, not the option's effect on it.
    const message =
      `For the ${OPTION_LABEL} option, our ${FACTOR_LABEL} assumption is stale — `
      + `change ${FACTOR_LABEL} to 0.3.`;
    expect(detectConfigureOptionIntent(message, projectOptionLabels(graph().nodes))).toEqual({
      matched: true,
      trigger: 'option_value_set',
    });
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('the same shape saying "baseline" is not claimed even when effect-framed', () => {
    const message =
      `For the ${OPTION_LABEL} option, set the effect of ${FACTOR_LABEL} — `
      + `actually, change the ${FACTOR_LABEL} baseline to 0.3.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'baseline_framing',
    });
  });

  it('OPPOSITE-DIRECTION TWIN — the effect-framed sentence over the SAME pair IS claimed', () => {
    // Without this twin the two assertions above would pass on a resolver that
    // claims nothing at all.
    expect(
      resolveOptionEffectWrite({
        message: `Set the ${OPTION_LABEL} option's effect on ${FACTOR_LABEL} to 0.3.`,
        graph: graph(),
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: OPTION_ID, value: 0.3 });
  });

  it('the excluded-trigger set names every trigger it refuses, with a reason', () => {
    expect(OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS.map((e) => e.trigger).sort()).toEqual([
      'chip_prefix',
      'option_value_set',
    ]);
    for (const entry of OPTION_EFFECT_WRITE_EXCLUDED_TRIGGERS) {
      expect(entry.reason.length).toBeGreaterThan(20);
    }
  });

  it('the bare configure chip message is not claimed (no value to write)', () => {
    const message = `Help me configure ${OPTION_LABEL}.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    expect(resolution.matched).toBe(false);
  });
});

describe('ACCEPTANCE 4 — an unbindable request asks, and writes nothing', () => {
  it('TWO options named → ask which option, with a complete candidate per option', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect and the ${SIBLING_OPTION_LABEL} option's `
      + `effect on ${FACTOR_LABEL} to 0.4.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('option');
    expect(resolution.value).toBe(0.4);
    // Copied before sorting: `optionLabels` is `readonly string[]`, and
    // `.sort()` on it is both a type error (caught only by the src+tests
    // Typecheck Drift ratchet, since `tsconfig.build.json` excludes tests) and
    // an in-place mutation of the resolver's own returned array.
    expect([...resolution.optionLabels].sort()).toEqual(
      [OPTION_LABEL, SIBLING_OPTION_LABEL].sort(),
    );
    expect(resolution.candidates.map((c) => c.optionId).sort()).toEqual(
      [OPTION_ID, SIBLING_OPTION_ID].sort(),
    );
    for (const candidate of resolution.candidates) {
      expect(candidate.factorId).toBe(FACTOR_ID);
    }
  });

  it('TWO of one option\'s linked factors named → ask which factor', () => {
    // The sibling option is wired to three factors; name two of them.
    const message =
      `Set the ${SIBLING_OPTION_LABEL} option's effect on ${FACTOR_LABEL} and `
      + `Annual clean-air charge burden to 0.4.`;
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('factor');
    expect(resolution.candidates.map((c) => c.factorId).sort()).toEqual(
      [FACTOR_ID, '90246f0d'].sort(),
    );
    expect(resolution.candidates.every((c) => c.optionId === SIBLING_OPTION_ID)).toBe(true);
  });

  it('a NESTED label match is not an ambiguity — the longer phrase wins', () => {
    // "Expand" only matched because it is a prefix of "Expand to Leeds":
    // asking the user to choose between a phrase and part of itself would be
    // the ambiguity theatre this rule exists to avoid.
    const g = graph();
    g.nodes.push(
      { id: 'opt_expand', kind: 'option', label: 'Expand', interventions: {} },
      { id: 'opt_expand_leeds', kind: 'option', label: 'Expand to Leeds', interventions: {} },
      {
        id: 'fac_capex',
        kind: 'factor',
        label: 'Capital expenditure',
        observed_state: { value: 0.5 },
      },
    );
    g.edges.push({
      from: 'opt_expand_leeds',
      to: 'fac_capex',
      strength: { mean: 1, std: 0.01 },
      exists_probability: 1,
      effect_direction: 'positive',
    } as Record<string, unknown>);
    expect(GraphV3.safeParse(g).success).toBe(true);
    const resolution = resolveOptionEffectWrite({
      message: "Set the Expand to Leeds option's effect on Capital expenditure to 0.6.",
      graph: g,
    });
    expect(resolution).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: 'opt_expand_leeds',
      factorId: 'fac_capex',
    });
  });

  it('an option named with NO linked factor named DECLINES rather than asking', () => {
    // Deliberate: the edit LLM can paraphrase-match a factor name this exact
    // reader cannot, and can add a missing structural edge. Pre-empting it
    // would remove a capability, not add one.
    const message = `Set the ${OPTION_LABEL} option's effect to 0.4.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });

  it('a factor NOT wired to the named option DECLINES (the edit lane can wire it)', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect on Annual clean-air charge burden to 0.4.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });
});

describe('ACCEPTANCE 5 — a SURVIVING option configures after structural deletes', () => {
  /** Remove every option except the survivor, and every edge touching them. */
  function afterStructuralDeletes(survivorId: string) {
    const g = graph();
    const removed = new Set(
      g.nodes.filter((n) => n.kind === 'option' && n.id !== survivorId).map((n) => n.id as string),
    );
    g.nodes = g.nodes.filter((n) => !removed.has(n.id as string));
    g.edges = g.edges.filter(
      (e) => !removed.has(e.from as string) && !removed.has(e.to as string),
    );
    return g;
  }

  it('the advised sentence still binds, by the SAME ids, on the post-delete graph', () => {
    const g = afterStructuralDeletes(OPTION_ID);
    // Positive control: the deletes really happened.
    expect(g.nodes.filter((n) => n.kind === 'option')).toHaveLength(1);
    expect(g.nodes.some((n) => n.id === SIBLING_OPTION_ID)).toBe(false);
    expect(GraphV3.safeParse(g).success).toBe(true);

    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: true,
      kind: 'write',
      optionId: OPTION_ID,
      optionLabel: OPTION_LABEL,
      factorId: FACTOR_ID,
      factorLabel: FACTOR_LABEL,
      value: 0.12,
    });
  });

  it('the now-ambiguous ask collapses to a write once the sibling option is deleted', () => {
    const message =
      `Set the ${OPTION_LABEL} option's effect and the ${SIBLING_OPTION_LABEL} option's `
      + `effect on ${FACTOR_LABEL} to 0.4.`;
    // Before: ambiguous.
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({ kind: 'ask' });
    // After the sibling is deleted, the only option the message can mean is
    // the survivor — resolved against the graph, never against a stale label
    // list.
    expect(
      resolveOptionEffectWrite({ message, graph: afterStructuralDeletes(OPTION_ID) }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: OPTION_ID, value: 0.4 });
  });
});

describe('ACCEPTANCE 6 — the DISCRIMINATING PAIR on the identity binding', () => {
  const BASELINE = {
    matched: true,
    kind: 'write',
    optionId: OPTION_ID,
    optionLabel: OPTION_LABEL,
    factorId: FACTOR_ID,
    factorLabel: FACTOR_LABEL,
    value: 0.12,
  };

  it('binds to the option the message NAMES', () => {
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: graph() })).toEqual(
      BASELINE,
    );
  });

  it('RED HALF — rename THE NAMED option and the write withdraws', () => {
    // Nothing else changes: the same factor, the same edge, the same value,
    // and the graph still has exactly one unconfigured option wired to that
    // factor. A resolver bound by anything other than the option's own label→id
    // identity would still produce a write here.
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === OPTION_ID) node.label = 'A completely different courier plan';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'option_not_named',
    });
  });

  it('GREEN HALF — rename a DIFFERENT option and the verdict is byte-identical', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === SIBLING_OPTION_ID) node.label = 'A completely different courier plan';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual(BASELINE);
  });

  it('RED HALF (factor) — rename THE NAMED factor and the write withdraws', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === FACTOR_ID) node.label = 'Something else entirely';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });

  it('GREEN HALF (factor) — rename a factor the option is NOT wired to; verdict unchanged', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === '90246f0d') node.label = 'Something else entirely';
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual(BASELINE);
  });

  it('REMOVING THE STRUCTURAL EDGE withdraws the write — "linked" is load-bearing', () => {
    const g = graph();
    g.edges = g.edges.filter((e) => !(e.from === OPTION_ID && e.to === FACTOR_ID));
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'factor_not_named',
    });
  });
});

describe('the value grammar admits ONE model-unit number and nothing else', () => {
  it.each(OPTION_EFFECT_WRITE_KNOWN_DROPPED)('KNOWN-DROPPED: %s', (template) => {
    const message = instantiate(template);
    const resolution = resolveOptionEffectWrite({ message, graph: graph() });
    expect(resolution.matched).toBe(false);
  });

  it('the KNOWN-DROPPED set is not vacuous — every member is effect-framed or baseline-framed', () => {
    // A member that failed the INTENT gate for an unrelated reason would be
    // pinning nothing about the value grammar.
    expect(OPTION_EFFECT_WRITE_KNOWN_DROPPED.length).toBeGreaterThanOrEqual(8);
    for (const template of OPTION_EFFECT_WRITE_KNOWN_DROPPED) {
      const message = instantiate(template);
      expect(message).toContain(OPTION_LABEL);
      expect(message).toContain(FACTOR_LABEL);
    }
  });

  it.each([
    ['0', 0],
    ['1', 1],
    ['0.6', 0.6],
    ['0.12', 0.12],
  ])('OPPOSITE-DIRECTION TWIN — "%s" is a model-unit value and IS claimed', (text, expected) => {
    const message = `Set the ${OPTION_LABEL} option's effect on ${FACTOR_LABEL} to ${text}.`;
    expect(resolveOptionEffectWrite({ message, graph: graph() })).toMatchObject({
      matched: true,
      kind: 'write',
      value: expected,
    });
  });

  it.each([
    ['a trailing full stop', 'to 0.6.', 0.6],
    ['an em-dash aside', 'to 0.12 — a share, no unit.', 0.12],
    ['a following clause', 'to 0.6 for now.', 0.6],
  ])('reads the value through %s', (_name, tail, expected) => {
    expect(readOptionEffectValue(`set the x option's effect on y ${tail}`)).toBe(expected);
  });

  it.each([
    ['currency', 'to £25000'],
    ['percent', 'to 12%'],
    // The class where the currency/percent guard is the ONLY thing standing:
    // both parse to an in-range, separator-free `1`. Added after the guard's
    // mutant SURVIVED against the original corpus.
    ['currency at a model-scale magnitude', 'to £1'],
    ['percent at a model-scale magnitude', 'to 1%'],
    ['a thousands separator', 'to 25,000'],
    ['an attached unit', 'to 0.6m'],
    ['above the model scale', 'to 40000'],
    ['a second assignment', 'to 0.6 and to 0.3'],
    ['no number at all', 'to high'],
  ])('refuses %s', (_name, tail) => {
    expect(readOptionEffectValue(`set the x option's effect on y ${tail}`)).toBeNull();
  });

  it('re-setting the value the model ALREADY holds declines rather than no-op-applying', () => {
    const g = graph();
    for (const node of g.nodes) {
      if (node.id === OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: g })).toEqual({
      matched: false,
      reason: 'value_already_set',
    });
    // Opposite-direction twin: a DIFFERENT value on the same, already-set pair
    // is a genuine revision and must still be claimed.
    expect(
      resolveOptionEffectWrite({ message: ADVISED_SENTENCE.replace('0.12', '0.7'), graph: g }),
    ).toMatchObject({ matched: true, kind: 'write', value: 0.7 });
  });

  it('an unparseable graph declines (the write must bind to real state)', () => {
    expect(resolveOptionEffectWrite({ message: ADVISED_SENTENCE, graph: { nodes: 'nope' } })).toEqual(
      { matched: false, reason: 'graph_unparseable' },
    );
  });
});

describe('the acknowledgement is read back from the COMMITTED graph (P5)', () => {
  it('reads the value the applied graph actually holds, through the shared reader', () => {
    const applied = graph();
    for (const node of applied.nodes) {
      if (node.id === OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(readCommittedOptionEffect(applied, OPTION_ID, FACTOR_ID)).toBe(0.12);
  });

  it('returns undefined when the write did not land — nothing may be claimed', () => {
    expect(readCommittedOptionEffect(graph(), OPTION_ID, FACTOR_ID)).toBeUndefined();
    expect(readCommittedOptionEffect(null, OPTION_ID, FACTOR_ID)).toBeUndefined();
    // The value landed on a DIFFERENT option — identity, not "a write landed".
    const elsewhere = graph();
    for (const node of elsewhere.nodes) {
      if (node.id === SIBLING_OPTION_ID) node.interventions = { [FACTOR_ID]: { value: 0.12 } };
    }
    expect(readCommittedOptionEffect(elsewhere, OPTION_ID, FACTOR_ID)).toBeUndefined();
  });

  it('the acknowledgement states the committed value and makes no offer', () => {
    const ack = formatOptionEffectWriteAck({
      optionLabel: OPTION_LABEL,
      factorLabel: FACTOR_LABEL,
      committedValue: 0.12,
    });
    expect(ack).toContain(OPTION_LABEL);
    expect(ack).toContain(FACTOR_LABEL);
    expect(ack).toContain('0.12');
    // P8/P3: no promise about a run this module cannot derive.
    expect(ack.toLowerCase()).not.toContain('analys');
    expect(ack.toLowerCase()).not.toContain('rerun');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// F1 — NESTING IS POSITIONAL. A label that is a phrase-substring of another
// label is a tokenisation artefact ONLY where it occurred INSIDE the longer
// one. Where the sentence names the short label somewhere else, both are
// genuinely named, and that is AMBIGUITY, not a nest.
//
// ⚠ THE DEFECT THIS BLOCK PINS, demonstrated by execution on `2d998fa5` by an
// independent adversarial reviewer: with options "Hire" and "Hire two
// engineers", the sentence
//
//   "Set the Hire option's effect on Payroll cost to 0.5 — not Hire two engineers."
//
// bound a WRITE to `opt_hire_two` — the option the user explicitly EXCLUDED —
// because `matchLabels` dropped the "Hire" match on the LABELS being nested
// without asking WHERE each occurred. A wrong-entity write inside the very
// feature that exists to prevent wrong-entity writes.
//
// The CONTROL that makes it a defect rather than a blanket refusal: the same
// sentence against a graph that does NOT carry the longer option binds
// correctly to "Hire". Both halves are asserted below, so a fix that simply
// stopped claiming these sentences would RED the control.
// ═══════════════════════════════════════════════════════════════════════════

/** Ids are the binding, never the labels (trap 19). */
const HIRE_ID = 'opt_hire';
const HIRE_TWO_ID = 'opt_hire_two';
const HIRE_THREE_ID = 'opt_hire_three';
const PAYROLL_ID = 'fac_payroll';

type MutableGraph = ReturnType<typeof graph>;

function optionNode(id: string, label: string): Record<string, unknown> {
  return { id, kind: 'option', label, interventions: {} };
}

function edgeTo(from: string, to: string): Record<string, unknown> {
  return {
    from,
    to,
    strength: { mean: 1, std: 0.01 },
    exists_probability: 1,
    effect_direction: 'positive',
  };
}

/**
 * The witnessed graph plus a nested option-label pair, both wired to the same
 * factor. `withLonger: false` is the reviewer's CONTROL graph.
 */
function hiringGraph(opts: { withLonger: boolean; withThird?: boolean }): MutableGraph {
  const g = graph();
  g.nodes.push(optionNode(HIRE_ID, 'Hire'));
  if (opts.withLonger) g.nodes.push(optionNode(HIRE_TWO_ID, 'Hire two engineers'));
  if (opts.withThird === true) g.nodes.push(optionNode(HIRE_THREE_ID, 'Hire three engineers'));
  g.nodes.push({
    id: PAYROLL_ID,
    kind: 'factor',
    label: 'Payroll cost',
    observed_state: { value: 0.5 },
  });
  g.edges.push(edgeTo(HIRE_ID, PAYROLL_ID) as never);
  if (opts.withLonger) g.edges.push(edgeTo(HIRE_TWO_ID, PAYROLL_ID) as never);
  if (opts.withThird === true) g.edges.push(edgeTo(HIRE_THREE_ID, PAYROLL_ID) as never);
  return g;
}

/** The reviewer's exact sentence. The user NAMES "Hire" and EXCLUDES the other. */
const EXCLUSION_SENTENCE =
  "Set the Hire option's effect on Payroll cost to 0.5 — not Hire two engineers.";

describe('F1 — a nested label is dropped only WHERE it is nested (position, not spelling)', () => {
  it('POSITIVE CONTROL — the two fixture graphs differ only by the longer option', () => {
    // Without this, a "the control still binds" assertion could be passing on
    // a graph that never carried the nesting pair at all.
    const withLonger = hiringGraph({ withLonger: true });
    const withoutLonger = hiringGraph({ withLonger: false });
    expect(GraphV3.safeParse(withLonger).success).toBe(true);
    expect(GraphV3.safeParse(withoutLonger).success).toBe(true);
    expect(withLonger.nodes.some((n) => n.id === HIRE_TWO_ID)).toBe(true);
    expect(withoutLonger.nodes.some((n) => n.id === HIRE_TWO_ID)).toBe(false);
    // Both options are genuinely wired to the same factor, so the wrong-entity
    // write is reachable rather than blocked by a missing edge.
    const parsed = GraphV3.parse(withLonger) as GraphV3T;
    expect(linkedFactorsOf(parsed, HIRE_ID).map((f) => f.id)).toEqual([PAYROLL_ID]);
    expect(linkedFactorsOf(parsed, HIRE_TWO_ID).map((f) => f.id)).toEqual([PAYROLL_ID]);
  });

  it('CONTROL — with the longer option absent, the sentence binds to "Hire" BY ID', () => {
    expect(
      resolveOptionEffectWrite({ message: EXCLUSION_SENTENCE, graph: hiringGraph({ withLonger: false }) }),
    ).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: HIRE_ID,
      factorId: PAYROLL_ID,
      value: 0.5,
    });
  });

  it('THE DEFECT — the EXCLUDED option must never be written; the turn ASKS', () => {
    const resolution = resolveOptionEffectWrite({
      message: EXCLUSION_SENTENCE,
      graph: hiringGraph({ withLonger: true }),
    });
    // The load-bearing assertion: no write to the excluded entity, ever.
    if (resolution.matched && resolution.kind === 'write') {
      expect(resolution.optionId).not.toBe(HIRE_TWO_ID);
    }
    // And the sentence genuinely names both, so the honest answer is a
    // question, not a winner (trap 22f — the ambiguity is the product).
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('option');
    expect(resolution.value).toBe(0.5);
    expect(resolution.candidates.map((c) => c.optionId).sort()).toEqual(
      [HIRE_ID, HIRE_TWO_ID].sort(),
    );
    for (const candidate of resolution.candidates) {
      expect(candidate.factorId).toBe(PAYROLL_ID);
    }
  });

  it('TWIN — a GENUINELY nested reference still resolves to the longer option', () => {
    // The whole point of the nesting rule. If this REDs, the fix has traded a
    // wrong write for a dead feature.
    expect(
      resolveOptionEffectWrite({
        message: "Set the Hire two engineers option's effect on Payroll cost to 0.5.",
        graph: hiringGraph({ withLonger: true }),
      }),
    ).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: HIRE_TWO_ID,
      factorId: PAYROLL_ID,
      value: 0.5,
    });
  });

  it.each([
    ['a trailing letter', 'hired'],
    ['a leading letter', 'rehire'],
  ])('BOTH word boundaries are load-bearing — "Hire" does not match %s', (_name, word) => {
    // ⚠ ADDED AFTER A SURVIVING MUTANT. Relaxing `boundedBefore &&
    // boundedAfter` to `||` in `phraseOccurrences` left the whole battery
    // GREEN: the pre-existing boundary spec contrasts "hire" with "hiring",
    // and "hire" is not a substring of "hiring" at all, so it never reached
    // the boundary test (trap 13b — a guard agreeing with itself). These two
    // words DO contain "hire", each with exactly one bounded side, so they
    // discriminate the AND from the OR.
    //
    // ⚠⚠ THE GRAPH AND THE EXPECTED VERDICT CHANGED WITH RULE 3b, AND THE
    // DISCRIMINATION IS SHARPER, NOT WEAKER — stated here rather than left for
    // a reader to reconstruct, because silently re-pointing a mutant-derived
    // guard is how this estate loses one.
    //
    // WHAT MOVED. Rule 3b resolves the option from the product's own
    // outstanding ask when the message names none, so on the ONE-option graph
    // this sentence now binds a write to "Hire" — and the `||` mutant binds the
    // same write, so the pair would no longer discriminate. On the TWO-option
    // graph the same factor is outstanding for both, so:
    //     pristine → `ask` (no option matched by label, two candidates)
    //     `||` mutant → "hire" matches inside "hired"/"rehire" → ONE option
    //                   matched by label → a WRITE
    // The verdicts now differ in KIND, which is a stronger signal than one
    // decline reason differing from another. Re-measured by execution: the
    // mutant bites this case on the two-option graph (`M4` in the lane's
    // battery).
    const resolution = resolveOptionEffectWrite({
      message: `Set the ${word} option's effect on Payroll cost to 0.5.`,
      graph: hiringGraph({ withLonger: true }),
    });
    // THE LOAD-BEARING HALF: the near-miss matched no option BY LABEL, so no
    // write may be produced from it.
    expect(resolution.matched && resolution.kind).toBe('ask');
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('unreachable');
    expect(resolution.optionSource).toBe('outstanding_ask');
    expect(new Set(resolution.candidates.map((c) => c.optionId))).toEqual(
      new Set([HIRE_ID, HIRE_TWO_ID]),
    );
  });

  it('TWIN — a SUFFIX-nested label is dropped too (the nest is not always a prefix)', () => {
    // "two engineers" ends exactly where "Hire two engineers" ends. A
    // containment test written with a strict upper bound would miss the whole
    // suffix class — and every other case in this block is a PREFIX nest, so
    // without this twin the corpus could not observe it (trap 22: check what
    // the corpus EXCLUDES).
    const g = hiringGraph({ withLonger: true });
    g.nodes.push(optionNode('opt_two_engineers', 'two engineers'));
    g.edges.push(edgeTo('opt_two_engineers', PAYROLL_ID) as never);
    expect(GraphV3.safeParse(g).success).toBe(true);

    expect(
      resolveOptionEffectWrite({
        message: "Set the Hire two engineers option's effect on Payroll cost to 0.5.",
        graph: g,
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: HIRE_TWO_ID, factorId: PAYROLL_ID });
  });

  it('TWIN — the SUFFIX label named on its OWN is still a candidate', () => {
    // Opposite direction of the twin above: dropping it everywhere would be a
    // dead feature rather than a fix.
    const g = hiringGraph({ withLonger: true });
    g.nodes.push(optionNode('opt_two_engineers', 'two engineers'));
    g.edges.push(edgeTo('opt_two_engineers', PAYROLL_ID) as never);

    expect(
      resolveOptionEffectWrite({
        message: "Set the two engineers option's effect on Payroll cost to 0.5.",
        graph: g,
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: 'opt_two_engineers' });
  });

  it('TWIN — naming only the SHORT label still resolves to the short option', () => {
    expect(
      resolveOptionEffectWrite({
        message: "Set the Hire option's effect on Payroll cost to 0.5.",
        graph: hiringGraph({ withLonger: true }),
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: HIRE_ID, factorId: PAYROLL_ID });
  });

  it('TWIN — the short label REPEATED, every occurrence nested, still resolves to the longer', () => {
    // Two occurrences, both inside an occurrence of the longer label. Nothing
    // here is a second candidate, so a write is still the honest answer — this
    // is the case a naive "more than one occurrence ⇒ ambiguous" rule would
    // break.
    expect(
      resolveOptionEffectWrite({
        message:
          "Hire two engineers — yes, Hire two engineers: set that option's effect on Payroll cost to 0.5.",
        graph: hiringGraph({ withLonger: true }),
      }),
    ).toMatchObject({ matched: true, kind: 'write', optionId: HIRE_TWO_ID });
  });

  it('TWIN — two DIFFERENT longer labels cover the short one; only the two longer are offered', () => {
    // "Hire" occurs twice, each occurrence inside a DIFFERENT longer label. No
    // single longer label covers both, but between them they cover every
    // occurrence — so "Hire" is nowhere named in its own right and must not be
    // offered as a third choice (a phrase and part of itself, the artefact the
    // nesting rule exists to remove).
    const resolution = resolveOptionEffectWrite({
      message:
        "Set the Hire two engineers option's effect and the Hire three engineers option's "
        + 'effect on Payroll cost to 0.5.',
      graph: hiringGraph({ withLonger: true, withThird: true }),
    });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.candidates.map((c) => c.optionId).sort()).toEqual(
      [HIRE_TWO_ID, HIRE_THREE_ID].sort(),
    );
    expect([...resolution.optionLabels].sort()).toEqual(
      ['Hire three engineers', 'Hire two engineers'].sort(),
    );
  });

  it('TWIN — the SAME exclusion shape on the FACTOR half also asks rather than writing', () => {
    // The nesting filter runs over factors too, so the defect had a factor-side
    // face: "…effect on Payroll cost to 0.5 — not Payroll cost overrun." would
    // have bound the overrun factor. One seam past the option half (P1).
    const g = hiringGraph({ withLonger: false });
    g.nodes.push({
      id: 'fac_payroll_overrun',
      kind: 'factor',
      label: 'Payroll cost overrun',
      observed_state: { value: 0.5 },
    });
    g.edges.push(edgeTo(HIRE_ID, 'fac_payroll_overrun') as never);
    expect(GraphV3.safeParse(g).success).toBe(true);

    const resolution = resolveOptionEffectWrite({
      message:
        "Set the Hire option's effect on Payroll cost to 0.5 — not Payroll cost overrun.",
      graph: g,
    });
    if (resolution.matched && resolution.kind === 'write') {
      expect(resolution.factorId).not.toBe('fac_payroll_overrun');
    }
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.ambiguity).toBe('factor');
    expect(resolution.candidates.map((c) => c.factorId).sort()).toEqual(
      [PAYROLL_ID, 'fac_payroll_overrun'].sort(),
    );
  });

  it('TWIN — two options carrying the SAME label are an ambiguity, not a mutual nest', () => {
    // The length ordering must be STRICT. Identical labels contain each other,
    // so a non-strict comparison drops BOTH and reports "no option named" —
    // turning a genuine ambiguity into a silent decline.
    const g = graph();
    g.nodes.push(optionNode(HIRE_ID, 'Hire'), optionNode('opt_hire_dup', 'Hire'));
    g.nodes.push({
      id: PAYROLL_ID,
      kind: 'factor',
      label: 'Payroll cost',
      observed_state: { value: 0.5 },
    });
    g.edges.push(edgeTo(HIRE_ID, PAYROLL_ID) as never);
    g.edges.push(edgeTo('opt_hire_dup', PAYROLL_ID) as never);
    expect(GraphV3.safeParse(g).success).toBe(true);

    const resolution = resolveOptionEffectWrite({
      message: "Set the Hire option's effect on Payroll cost to 0.5.",
      graph: g,
    });
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('expected an ask');
    expect(resolution.candidates.map((c) => c.optionId).sort()).toEqual(
      [HIRE_ID, 'opt_hire_dup'].sort(),
    );
  });

  it('TWIN (factor) — a genuinely nested FACTOR reference still resolves to the longer', () => {
    const g = hiringGraph({ withLonger: false });
    g.nodes.push({
      id: 'fac_payroll_overrun',
      kind: 'factor',
      label: 'Payroll cost overrun',
      observed_state: { value: 0.5 },
    });
    g.edges.push(edgeTo(HIRE_ID, 'fac_payroll_overrun') as never);
    expect(
      resolveOptionEffectWrite({
        message: "Set the Hire option's effect on Payroll cost overrun to 0.5.",
        graph: g,
      }),
    ).toMatchObject({
      matched: true,
      kind: 'write',
      optionId: HIRE_ID,
      factorId: 'fac_payroll_overrun',
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// W5 — RULE 3b: THE PRODUCT'S OWN OUTSTANDING ASK RESOLVES THE OPTION
//
// ⚠ PROVENANCE, stated before any assertion (trap 16-inverse). Every USER
// SENTENCE below is a VERBATIM capture from the 18 Aug 2026 composed
// model-compiler journey witness (deployed CEE `585f8dce` / UI `dd089a50`,
// fresh guest, real governed-corpus brief) — not a sentence composed here. The
// node IDENTITIES are captured too. The EDGES are RECONSTRUCTED, and the
// fixture's `__provenance__` says exactly which half is which and what that
// costs (a blocker COUNT from this fixture is not a wire figure; the pair
// IDENTITIES are).
//
// THE WITNESSED DEFECT. Olumi asked, on screen:
//   "Next, choose the missing effect value for "double down on enterprise
//    sales (higher…" on "Sales Headcount - Hybrid Maintained" …"
// The user answered it. The write landed on the FACTOR BASELINE instead:
// `interventions` stayed 0 on all four options, the MISSING_OPTION_VALUE
// blocker survived BY IDENTITY, and only the fabricated constant in the
// blocker copy moved, 0.5 → 0.8.
//
// ⭐ RED-FIRST SIGNATURES AT PRISTINE `b5f9aa2e` (measured, not predicted):
//   · "binds the user's verbatim answer to the product's own ask, BY IDENTITY"
//     → AssertionError: expected { matched: false, reason: 'option_not_named' }
//   · "the write lands as an OPTION INTERVENTION, not a factor baseline"
//     → Error: expected a write, got {"matched":false,"reason":"option_not_named"}
//   · "a factor two options are waiting on ASKS rather than guessing"
//     → AssertionError: expected 'option_not_named' to be 'ask'
// The three twins below (T6 baseline, full-label, plain factor edit) were GREEN
// at pristine and MUST STAY GREEN — they are the opposite-direction half.
// ═══════════════════════════════════════════════════════════════════════════

interface JourneyWitnessFixture {
  readonly ids: {
    readonly option_id: string;
    readonly option_label: string;
    readonly factor_id: string;
    readonly factor_label: string;
    readonly sibling_factor_id: string;
    readonly sibling_factor_label: string;
    readonly two_option_factor_id: string;
    readonly two_option_factor_label: string;
  };
  readonly wire: {
    readonly on_screen_ask: string;
    readonly t4_user_message: string;
    readonly t5_user_message: string;
    readonly t6_user_message: string;
  };
  readonly draft_graph: { nodes: Array<Record<string, unknown>>; edges: Array<Record<string, unknown>> };
}

const J18 = JSON.parse(
  readFileSync(
    new URL(
      '../../__tests__/fixtures/witness-2026-08-18/model-compiler-option-effect.json',
      import.meta.url,
    ),
    'utf8',
  ),
) as JourneyWitnessFixture;

const j18Graph = (): unknown => JSON.parse(JSON.stringify(J18.draft_graph)) as unknown;

describe('W5 — the fixture is what it claims to be (positive control)', () => {
  it('the captured pair IS outstanding on this graph, and the option label is untypeable', () => {
    // Without this the W5 assertions could pass on a graph that was never
    // blocked, or on a label short enough to make rule 3b pointless (trap 13:
    // an absence probe needs a presence first).
    const pairs = deriveMissingEffectPairs(buildCanonicalAnalysisReadyFromGraph(j18Graph()));
    expect(
      pairs.some((p) => p.optionId === J18.ids.option_id && p.factorId === J18.ids.factor_id),
    ).toBe(true);
    // EXACTLY ONE option is waiting on the captured factor — the conjunct that
    // makes rule 3b a resolution rather than a guess.
    expect(pairs.filter((p) => p.factorId === J18.ids.factor_id)).toHaveLength(1);
    // …and TWO are waiting on the other captured factor: the ask twin's
    // discriminator is a fact of this graph, not a shape invented for it.
    expect(pairs.filter((p) => p.factorId === J18.ids.two_option_factor_id)).toHaveLength(2);

    // The reason the user cannot take path (3): the label is a brief fragment
    // the product itself renders truncated.
    expect(J18.ids.option_label.length).toBeGreaterThan(80);
    expect(J18.wire.on_screen_ask).toContain('double down on enterprise sales (higher…');
    expect(J18.wire.t5_user_message).not.toContain(J18.ids.option_label);
  });
});

describe('W5 — ACCEPTANCE 1: the product\'s own asked-for answer binds', () => {
  it('binds the user\'s verbatim answer to the product\'s own ask, BY IDENTITY', () => {
    const resolution = resolveOptionEffectWrite({
      message: J18.wire.t5_user_message,
      graph: j18Graph(),
    });
    expect(resolution).toEqual({
      matched: true,
      kind: 'write',
      optionId: J18.ids.option_id,
      optionLabel: J18.ids.option_label,
      factorId: J18.ids.factor_id,
      factorLabel: J18.ids.factor_label,
      value: 0.8,
    });
  });

  it('the trigger gate is UNCHANGED — the sentence was always effect-framed; only identity failed', () => {
    // P7 / trap 21: this pins WHICH gate moved. The intent classifier already
    // said yes at pristine, so a later reader cannot mistake rule 3b for a
    // widening of the trigger set.
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(
      detectConfigureOptionIntent(J18.wire.t5_user_message, projectOptionLabels(parsed.nodes)),
    ).toEqual({ matched: true, trigger: 'effect_vocab' });
  });

  it('a factor two options are waiting on ASKS rather than guessing', () => {
    const message =
      `Set the option's effect on ${J18.ids.two_option_factor_label} to 0.4.`;
    const resolution = resolveOptionEffectWrite({ message, graph: j18Graph() });
    expect(resolution.matched && resolution.kind).toBe('ask');
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('unreachable');
    expect(resolution.ambiguity).toBe('option');
    expect(resolution.optionSource).toBe('outstanding_ask');
    expect(resolution.candidates).toHaveLength(2);
    // Bound by IDENTITY, not by count: every candidate is the SAME factor and a
    // DIFFERENT option, which is the only shape an option-ambiguity may take.
    expect(new Set(resolution.candidates.map((c) => c.factorId))).toEqual(
      new Set([J18.ids.two_option_factor_id]),
    );
    expect(new Set(resolution.candidates.map((c) => c.optionId)).size).toBe(2);
  });

  it('a factor the product is NOT asking about does not resolve an option', () => {
    // The conjunct that stops rule 3b reaching a pair nobody asked about. The
    // captured pair is satisfied first, so the ask no longer names it.
    const satisfied = GraphV3.parse(j18Graph()) as GraphV3T;
    const option = satisfied.nodes.find((n) => n.id === J18.ids.option_id) as Record<string, unknown>;
    option.interventions = { [J18.ids.factor_id]: 0.4 };
    const resolution = resolveOptionEffectWrite({
      message: J18.wire.t5_user_message,
      graph: satisfied,
    });
    expect(resolution).toEqual({ matched: false, reason: 'no_outstanding_ask_for_factor' });
  });
});

describe('W5 — OPPOSITE-DIRECTION TWINS: what must NOT change', () => {
  it('TWIN — the witnessed turn 6 says "baseline" and is STILL suppressed', () => {
    // Requirement 4: the W1 exclusion class stays excluded. This sentence is
    // the user's genuine option-effect intent and we still decline it, because
    // at the graph it is indistinguishable from a baseline edit.
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t6_user_message, graph: j18Graph() }),
    ).toEqual({ matched: false, reason: 'baseline_framing' });
  });

  it('TWIN — a plain factor-BASELINE edit still never reaches this module', () => {
    // Requirement 3, at its own seam: "Set <factor> to 0.3" is not
    // effect-framed, so `set_factor_value` keeps it, exactly as at pristine.
    const message = `Set ${J18.ids.sibling_factor_label} to 0.3`;
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(detectConfigureOptionIntent(message, projectOptionLabels(parsed.nodes)).matched).toBe(
      false,
    );
    expect(resolveOptionEffectWrite({ message, graph: j18Graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('TWIN — naming the option IN FULL still takes path (3), unchanged', () => {
    // Rule 3b must be unreachable when the message names an option. The pair
    // here is the SIBLING factor, so a fallback that fired anyway would bind a
    // different factor and this would go red.
    const message =
      `Set the ${J18.ids.option_label} option's effect on ${J18.ids.sibling_factor_label} to 0.2.`;
    const resolution = resolveOptionEffectWrite({ message, graph: j18Graph() });
    expect(resolution.matched && resolution.kind === 'write' && resolution.factorId).toBe(
      J18.ids.sibling_factor_id,
    );
  });

  it('DISCRIMINATING PAIR — rule 3b is bound to the ASKED factor, not to any factor', () => {
    // RED HALF: rename the factor the message names → the write withdraws.
    const renamed = GraphV3.parse(j18Graph()) as GraphV3T;
    const target = renamed.nodes.find((n) => n.id === J18.ids.factor_id) as Record<string, unknown>;
    target.label = 'Zzz Unrelated Factor Label';
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t5_user_message, graph: renamed }).matched,
    ).toBe(false);

    // GREEN HALF: rename a DIFFERENT factor → the verdict is byte-identical.
    const other = GraphV3.parse(j18Graph()) as GraphV3T;
    const bystander = other.nodes.find((n) => n.id === J18.ids.sibling_factor_id) as Record<string, unknown>;
    bystander.label = 'Zzz Unrelated Factor Label';
    expect(resolveOptionEffectWrite({ message: J18.wire.t5_user_message, graph: other })).toEqual(
      resolveOptionEffectWrite({ message: J18.wire.t5_user_message, graph: j18Graph() }),
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// A2 — RULE 3c: THE USER ANSWERED THE QUESTION THE PRODUCT ASKED
//
// ⚠⚠ THE PIN BELOW IS A FLIP, AND THE HONEST RECORD OF WHAT IT USED TO SAY IS
// PART OF THE EVIDENCE. Until this change the suite carried:
//
//   it('turn 4 (the prose answer) is STILL not claimed — and the record says why')
//     expect(resolveOptionEffectWrite({ message: t4, graph })).toEqual(
//       { matched: false, reason: 'not_effect_framed_intent' })
//
// It was true, it was measured, and it was the honest-gap protocol working as
// designed: the gap could not be claimed silently. Measured at pristine
// `3e15752e` it is still exactly what the resolver returns, and this block is
// the RED-first signature — the ONLY test in the 161-test routing slice that
// changes verdict.
//
// ⭐ WHY THE OLD PIN'S STATED REASON ("no change to THIS module can bind it")
// WAS RIGHT AND STILL IS. It could not be bound by widening rule 3b, because
// rule 3b runs only after `detectConfigureOptionIntent` has CLAIMED the
// sentence, and it never claims this one. Rule 3c does not widen the classifier
// — it is reached exactly where the classifier claimed NOTHING, which is what
// keeps every trigger exclusion intact by construction.
// ═══════════════════════════════════════════════════════════════════════════

describe('A2 — the fixture is what it claims to be (positive control)', () => {
  it('the product IS asking about the captured pair, and t4 names NEITHER entity in full', () => {
    // Without this, the acceptance below could pass on a graph where the pair
    // was resolvable by ordinary label matching (trap 13: prove the presence
    // before believing the absence).
    const readiness = buildCanonicalAnalysisReadyFromGraph(j18Graph());
    expect(deriveAskedEffectPair(readiness)).toEqual({
      optionId: J18.ids.option_id,
      optionLabel: J18.ids.option_label,
      factorId: J18.ids.factor_id,
      factorLabel: J18.ids.factor_label,
    });
    // NEITHER label appears in the answer — so nothing in it could have been
    // resolved by the word-bounded matcher that path (3) and rule 3b use.
    const t4 = J18.wire.t4_user_message.toLowerCase();
    expect(t4).not.toContain(J18.ids.option_label.toLowerCase());
    expect(t4).not.toContain(J18.ids.factor_label.toLowerCase());
    // …and the classifier genuinely declines it, so rule 3c's conjunct (a) is
    // a fact about this sentence and not an assumption (trap 13b).
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(
      detectConfigureOptionIntent(J18.wire.t4_user_message, projectOptionLabels(parsed.nodes))
        .matched,
    ).toBe(false);
  });

  it("the asked pair is the PRODUCER's, not this suite's — the recovery copy names it", () => {
    // P7. `readiness-recovery.ts` composes the on-screen question from
    // `blockers[0]`; `deriveAskedEffectPair` reads the same element. Driven
    // through the real composer so the agreement is executed, not asserted.
    //
    // ⚠ THE FIXTURE'S OWN STATUS IS `blocked`, NOT `needs_user_input` — an
    // artefact of its RECONSTRUCTED edges, which its `__provenance__` warns
    // about. So the payload handed to the composer carries the fixture's
    // CAPTURED blockers with the status the live turn had. The blockers are the
    // captured half; the status is stated, not smuggled.
    const readiness = buildCanonicalAnalysisReadyFromGraph(j18Graph()) as {
      readonly blockers?: unknown;
    };
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    const projected = projectReadinessRecovery(
      { status: 'needs_user_input', blockers: readiness.blockers } as never,
      parsed.nodes as never,
    );
    expect(projected.kind).toBe('provide_value');
    const asked = deriveAskedEffectPair(readiness)!;
    // BY IDENTITY on both halves of the pair, through the composer's own
    // (truncating) label projection.
    expect(projected.nextStep).toContain(`"${projected.optionLabel}"`);
    expect(asked.optionLabel.startsWith(projected.optionLabel!.replace(/…$/, ''))).toBe(true);
    expect(projected.factorLabel).toBe(asked.factorLabel);
  });
});

describe('A2 — ACCEPTANCE: an ordinary answer binds the pair the product asked about', () => {
  it('the witnessed prose answer resolves the EXACT outstanding pair, BY IDENTITY', () => {
    // ⭐ RED AT PRISTINE `3e15752e`, measured:
    //   AssertionError: expected { matched: false, reason: 'not_effect_framed_intent' }
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t4_user_message, graph: j18Graph() }),
    ).toEqual({
      matched: true,
      kind: 'write',
      optionId: J18.ids.option_id,
      optionLabel: J18.ids.option_label,
      factorId: J18.ids.factor_id,
      factorLabel: J18.ids.factor_label,
      value: 0.8,
    });
  });

  it('the answer reading carries the CONTEXT, and the bare form keeps its own owner', () => {
    // The two shapes, and the field that tells them apart (trap 21).
    expect(readMissingValueAnswer(J18.wire.t4_user_message)).toEqual({
      kind: 'numeric',
      valueText: '0.8',
      referent: 'it',
      leadingContext: 'doubling down on enterprise sales would push sales headcount up a lot',
    });
    // A whole-message bare answer is NOT claimed by this module: it already has
    // an owner in `resolveRepairValueBinding`, and two owners for one shape is
    // the defect, not the coverage.
    expect(resolveOptionEffectWrite({ message: 'Set it to 0.8.', graph: j18Graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('DISCRIMINATING PAIR — the write follows the ASK, not the sentence', () => {
    // RED HALF: make the product ask about a DIFFERENT pair (satisfy the head
    // blocker) and the SAME sentence binds the pair the product now asks about.
    const moved = GraphV3.parse(j18Graph()) as GraphV3T;
    const option = moved.nodes.find((n) => n.id === J18.ids.option_id) as Record<string, unknown>;
    option.interventions = { [J18.ids.factor_id]: 0.4 };
    const after = resolveOptionEffectWrite({ message: J18.wire.t4_user_message, graph: moved });
    expect(after.matched && after.kind === 'write' && after.factorId).toBe(
      J18.ids.sibling_factor_id,
    );

    // GREEN HALF: satisfying an UNRELATED option's pair leaves the verdict
    // byte-identical. Neither half alone shows the binding; the pair does.
    const bystander = GraphV3.parse(j18Graph()) as GraphV3T;
    const other = bystander.nodes.find((n) => n.id === 'e755ec33') as Record<string, unknown>;
    other.interventions = { '16f4cf02': 0.4 };
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t4_user_message, graph: bystander }),
    ).toEqual(resolveOptionEffectWrite({ message: J18.wire.t4_user_message, graph: j18Graph() }));
  });

  it('no outstanding effect-value ask ⇒ nothing to answer, and nothing is written', () => {
    // Every option satisfied on every linked factor: the recovery copy is no
    // longer asking for an effect value, so the answer has no antecedent.
    const satisfied = GraphV3.parse(j18Graph()) as GraphV3T;
    for (const node of satisfied.nodes) {
      if (node.kind !== 'option') continue;
      const targets = satisfied.edges.filter((e) => e.from === node.id).map((e) => e.to);
      (node as Record<string, unknown>).interventions = Object.fromEntries(
        targets.map((t) => [t, 0.4]),
      );
    }
    expect(deriveAskedEffectPair(buildCanonicalAnalysisReadyFromGraph(satisfied))).toBeNull();
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t4_user_message, graph: satisfied }),
    ).toEqual({ matched: false, reason: 'no_answered_ask' });
  });
});

describe('A2 — NEVER GUESS BETWEEN ENTITIES: pointing elsewhere withdraws the claim', () => {
  it('prose naming a DIFFERENT option declines — the ask is not the authority on it', () => {
    // "invest heavily in a self-serve product…" is option e755ec33; the product
    // is asking about 4abad64d. Bound by identity: not a write, and specifically
    // not a write to the asked pair.
    const resolution = resolveOptionEffectWrite({
      message: 'Investing heavily in self-serve is the real driver here - set it to 0.4.',
      graph: j18Graph(),
    });
    expect(resolution).toEqual({ matched: false, reason: 'answer_points_elsewhere' });
  });

  it('prose naming a DIFFERENT factor IN FULL declines', () => {
    const resolution = resolveOptionEffectWrite({
      message: `${J18.ids.sibling_factor_label} is the one that matters - set it to 0.4.`,
      graph: j18Graph(),
    });
    expect(resolution).toEqual({ matched: false, reason: 'answer_points_elsewhere' });
  });

  it('OPPOSITE-DIRECTION TWIN — naming the ASKED factor in full still binds', () => {
    // The twin that stops the guard above being written as "any label at all
    // declines", which would make the whole rule unreachable in prose that
    // happens to be precise.
    const resolution = resolveOptionEffectWrite({
      message: `${J18.ids.factor_label} is what I mean - set it to 0.4.`,
      graph: j18Graph(),
    });
    expect(resolution.matched && resolution.kind === 'write' && resolution.factorId).toBe(
      J18.ids.factor_id,
    );
  });

  it('TWO options both outstanding on the asked factor ASK, and pick NEITHER', () => {
    // The ambiguity is made the product (trap 22f). Built by giving a SECOND
    // option an unvalued edge to the asked factor, so both are genuinely
    // outstanding on it — the precondition is pinned in-test (trap 13b).
    const twoWay = GraphV3.parse(j18Graph()) as GraphV3T;
    twoWay.edges.push({
      from: '939d4630',
      to: J18.ids.factor_id,
      strength: { mean: 1, std: 0.01 },
      exists_probability: 1,
      effect_direction: 'positive',
    } as never);
    const outstanding = deriveMissingEffectPairs(buildCanonicalAnalysisReadyFromGraph(twoWay));
    expect(outstanding.filter((p) => p.factorId === J18.ids.factor_id)).toHaveLength(2);

    const resolution = resolveOptionEffectWrite({
      message: 'Doubling down, or the phased approach - set it to 0.4.',
      graph: twoWay,
    });
    expect(resolution.matched && resolution.kind).toBe('ask');
    if (!resolution.matched || resolution.kind !== 'ask') throw new Error('unreachable');
    expect(resolution.ambiguity).toBe('option');
    expect(resolution.optionSource).toBe('outstanding_ask');
    expect(new Set(resolution.candidates.map((c) => c.optionId))).toEqual(
      new Set([J18.ids.option_id, '939d4630']),
    );
    expect(new Set(resolution.candidates.map((c) => c.factorId))).toEqual(
      new Set([J18.ids.factor_id]),
    );
  });
});

describe('A2 — OPPOSITE-DIRECTION TWINS: the exclusions that must NOT move', () => {
  it('TWIN — the `option_value_set` exclusion is untouched (W1 class still declines)', () => {
    // Requirement 4. A sentence the classifier CLAIMS never reaches rule 3c, so
    // this decline is the pre-existing one, unchanged.
    const message =
      `It would push it up a lot - set it to 0.8 for the ${J18.ids.option_label} option.`;
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(
      detectConfigureOptionIntent(message, projectOptionLabels(parsed.nodes)),
    ).toEqual({ matched: true, trigger: 'option_value_set' });
    expect(resolveOptionEffectWrite({ message, graph: j18Graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('⭐ TWIN — a CONTEXT-BEARING answer that the classifier CLAIMS still declines', () => {
    // ⚠ ADDED FROM A SURVIVING MUTANT, not from imagination (trap 22). The
    // battery mutated conjunct (a) to admit `option_value_set` into rule 3c and
    // all 215 tests stayed GREEN — because the W1 twin below ends in a trailing
    // clause, so the answer reading refused it for an unrelated reason and the
    // conjunct was never exercised. This sentence IS a well-formed
    // context-bearing answer AND classifies `option_value_set`, so it reaches
    // conjunct (a) and nothing else. Under the mutant it BINDS.
    const message = `For the ${J18.ids.option_label} option this matters - set it to 0.8.`;
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    // Both preconditions pinned in-test, or the decline could be either gate's
    // (trap 13b — a guard must pin its own precondition).
    expect(detectConfigureOptionIntent(message, projectOptionLabels(parsed.nodes))).toEqual({
      matched: true,
      trigger: 'option_value_set',
    });
    expect(readMissingValueAnswer(message)?.kind).toBe('numeric');
    expect(resolveOptionEffectWrite({ message, graph: j18Graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('TWIN — the `baseline` suppressor still fires on a context-bearing answer', () => {
    expect(
      resolveOptionEffectWrite({
        message: `The team disagrees - set the ${J18.ids.factor_label} baseline to 0.8.`,
        graph: j18Graph(),
      }),
    ).toEqual({ matched: false, reason: 'baseline_framing' });
  });

  it('TWIN — a genuine factor-BASELINE request still writes the factor baseline', () => {
    // The opposite-direction requirement, at its own seam: this sentence must
    // stay OUT of the option-effect writer entirely so `set_factor_value` keeps
    // it, exactly as at pristine.
    const message = `Set ${J18.ids.sibling_factor_label} to 0.3`;
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(
      detectConfigureOptionIntent(message, projectOptionLabels(parsed.nodes)).matched,
    ).toBe(false);
    expect(resolveOptionEffectWrite({ message, graph: j18Graph() })).toEqual({
      matched: false,
      reason: 'not_effect_framed_intent',
    });
  });

  it('⭐ the pinned known-dropped set declines, each for its stated reason', () => {
    // Trap 22f's honest-gap protocol: REDs if the claim widens to swallow one.
    expect(ANSWERED_ASK_KNOWN_DROPPED.length).toBeGreaterThanOrEqual(5);
    for (const dropped of ANSWERED_ASK_KNOWN_DROPPED) {
      const message = dropped.message
        .replace('{option}', J18.ids.option_label)
        .replace('{factor}', J18.ids.factor_label);
      const resolution = resolveOptionEffectWrite({ message, graph: j18Graph() });
      expect(resolution.matched, `${message} :: ${dropped.why}`).toBe(false);
      expect(dropped.why.length).toBeGreaterThan(20);
    }
  });

  it('a context-bearing answer reads the WHOLE value, and reads it as numeric', () => {
    // ⚠ ASSERTED AS A WHOLE OBJECT, not through `?.valueText`. The reading is a
    // UNION and only its numeric arm carries a value, so a field access narrows
    // nothing and does not typecheck under the full `tsc --noEmit` the drift
    // ratchet runs (the named local gate excludes tests and cannot see it).
    // Asserting the object also binds the KIND, which the field access did not:
    // a qualitative reading with no value at all would have satisfied it.
    //
    // ⚠ AND THE TITLE CHANGED WITH IT. It used to say "the value is 0.8, never
    // 8", crediting the digit lookarounds; measured, the `\s+` requirement
    // already prevents a split inside a decimal. The lookarounds' real killing
    // case lives in `missing-value-answer.test.ts`.
    expect(readMissingValueAnswer('It matters a lot - set it to 0.8.')).toStrictEqual({
      kind: 'numeric',
      valueText: '0.8',
      referent: 'it',
      leadingContext: 'it matters a lot',
    });
  });

  it('the stated residual is real behaviour, and the ack makes it VISIBLE', () => {
    expect(ANSWERED_ASK_RESOLVED_LIMIT.behaviour).toContain('names it in the acknowledgement');
    const resolution = resolveOptionEffectWrite({
      message: 'The burn rate is what worries me - set it to 0.4.',
      graph: j18Graph(),
    });
    if (!resolution.matched || resolution.kind !== 'write') throw new Error('unreachable');
    expect(resolution.optionId).toBe(J18.ids.option_id);
    expect(
      formatOptionEffectWriteAck({
        optionLabel: resolution.optionLabel,
        factorLabel: resolution.factorLabel,
        committedValue: resolution.value,
      }),
    ).toContain(J18.ids.factor_label);
  });
});

describe('W5 — the residual is STATED, not papered over', () => {

  it('the stated limit is real behaviour, and the acknowledgement makes it VISIBLE', () => {
    // An option reference this reader cannot resolve, next to a factor the
    // product IS asking about for a different option. It binds to the
    // outstanding one — and the ack NAMES that option, so the user reads which
    // entity moved. The witnessed defect was the opposite: a wrong entity
    // written while the reply said nothing had changed.
    expect(OPTION_EFFECT_WRITE_ASK_RESOLVED_LIMIT.behaviour).toContain('names it in the acknowledgement');
    const message = `For the hybrid option, set the effect on ${J18.ids.factor_label} to 0.8.`;
    const resolution = resolveOptionEffectWrite({ message, graph: j18Graph() });
    expect(resolution.matched && resolution.kind === 'write' && resolution.optionId).toBe(
      J18.ids.option_id,
    );
    if (!resolution.matched || resolution.kind !== 'write') throw new Error('unreachable');
    expect(
      formatOptionEffectWriteAck({
        optionLabel: resolution.optionLabel,
        factorLabel: resolution.factorLabel,
        committedValue: resolution.value,
      }),
    ).toContain(J18.ids.option_label);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// W5 — THE FACTOR AXIS OF "NEVER GUESS BETWEEN AMBIGUOUS ENTITIES"
//
// ⚠ ADDED FROM A SURVIVING MUTANT, not from imagination. The battery mutated
// rule 3b's `factorMatches.length !== 1` to `< 1` and the whole 132-test slice
// stayed GREEN — so nothing pinned what happens when the message names TWO
// factors the product is currently asking about. Under that mutant rule 3b
// silently takes `factorMatches[0]`: the product PICKS one of two entities the
// user might have meant, which is the wrong-entity class this seam exists to
// remove, arriving on the factor axis instead of the option axis.
//
// The option axis was already covered — two outstanding options on one factor
// ASK. This is its opposite-direction twin on the other half of the pair.
// ═══════════════════════════════════════════════════════════════════════════
describe('W5 — rule 3b never picks between two factors the product is asking about', () => {
  it('two ASKED-ABOUT factors and no option named → declines, and picks NEITHER', () => {
    // Both factors are genuinely outstanding on this graph — the positive
    // control, so a decline cannot pass by the factors being absent.
    const pairs = deriveMissingEffectPairs(buildCanonicalAnalysisReadyFromGraph(j18Graph()));
    const asked = new Set(pairs.map((p) => p.factorId));
    expect(asked.has(J18.ids.factor_id)).toBe(true);
    expect(asked.has(J18.ids.sibling_factor_id)).toBe(true);

    const message =
      `I meant the option's effect — set ${J18.ids.factor_label} and `
      + `${J18.ids.sibling_factor_label} to 0.8.`;
    // The trigger gate still says yes, so the decline is rule 3b's own decision
    // and not an intent miss (trap 13b — pin the precondition in-test).
    const parsed = GraphV3.parse(j18Graph()) as GraphV3T;
    expect(
      detectConfigureOptionIntent(message, projectOptionLabels(parsed.nodes)).matched,
    ).toBe(true);

    const resolution = resolveOptionEffectWrite({ message, graph: j18Graph() });
    // BY IDENTITY, both halves: no write at all, and specifically not a write
    // to either candidate factor.
    expect(resolution).toEqual({ matched: false, reason: 'no_outstanding_ask_for_factor' });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// W5 — THE OTHER SURVIVING MUTANT, DEMONSTRATED EQUIVALENT RATHER THAN PINNED.
//
// `messageCarriesOptionCue`'s `optionLabels.length === 0 → false` was mutated
// to `true` and survived. It is EQUIVALENT, and this is the demonstration
// rather than the assertion (trap 13c: a survivor is a claim either way).
// Caller 1, `impliesOptionInterventionEdit`, short-circuits on the same
// condition before it can call. Caller 2 is rule 3b, and on an option-less
// graph BOTH readings decline `option_not_named` — the mutant directly, the
// original because the outstanding-ask set is necessarily empty.
// ═══════════════════════════════════════════════════════════════════════════
describe('W5 — an option-less graph declines by BOTH routes (equivalence demonstration)', () => {
  it('no options ⇒ no outstanding pairs ⇒ `option_not_named`, whichever branch is taken', () => {
    const optionless = GraphV3.parse(j18Graph()) as GraphV3T;
    const optionIds = new Set(
      optionless.nodes.filter((n) => n.kind === 'option').map((n) => n.id),
    );
    expect(optionIds.size).toBe(4);
    const stripped = {
      ...optionless,
      nodes: optionless.nodes.filter((n) => !optionIds.has(n.id)),
      edges: optionless.edges.filter((e) => !optionIds.has(e.from) && !optionIds.has(e.to)),
    };
    // The second branch's premise, measured: with no options there is nothing
    // for the product to be asking about.
    expect(
      deriveMissingEffectPairs(buildCanonicalAnalysisReadyFromGraph(stripped)),
    ).toEqual([]);
    expect(
      resolveOptionEffectWrite({ message: J18.wire.t5_user_message, graph: stripped }),
    ).toEqual({ matched: false, reason: 'option_not_named' });
  });
});
