/**
 * V5 Golden Journey benchmark prep — unit tests for the P0 journey
 * assertions, the DGAI result-state extractor, the public-surface leak
 * scanners, and the #277 flip-honesty regexes.
 *
 * All fixtures are plain `FetchResult`-shaped objects ({status, body,
 * elapsed_ms}) called directly against the assertions — no network.
 */

import { describe, it, expect } from 'vitest';

import {
  assertAddOption,
  assertAddOptionDefer,
  assertDgaiResultState,
  assertEditOptionContainment,
  assertWhatWouldFlipChip,
  assertWhatWouldFlipStale,
  collectLeakFindings,
  extractDgaiState,
} from '../../../tools/v5-journey-replay/assertions.js';
import {
  findEnrichmentLeakCarriers,
  FLIP_NO_TIPPING_POINT_RE,
  FLIP_COULD_FLIP_CLAIM_RE,
} from '../../../tools/v5-journey-replay/forbidden-terms.js';
import type { FetchResult } from '../../../tools/v5-journey-replay/client.js';

function res(body: unknown, status = 200, elapsed = 100): FetchResult {
  return { status, body: body as never, elapsed_ms: elapsed };
}

const ANALYSIS_RESULT_BLOCK = {
  type: 'analysis_result',
  summary: 'Hire Two Senior Engineers Locally leads at about 63%.',
  leading_option_id: 'opt_hire',
  win_probabilities: { opt_hire: 0.63, opt_offshore: 0.37 },
};

// ---------------------------------------------------------------------------
// extractDgaiState
// ---------------------------------------------------------------------------
describe('extractDgaiState', () => {
  it('returns present:false when no analysis_result block', () => {
    expect(extractDgaiState({ blocks: [{ type: 'coaching' }] } as never)).toEqual({ present: false });
  });

  it('extracts leading option + win count (object-keyed) + summary/enrichment flags', () => {
    const d = extractDgaiState({
      blocks: [{ ...ANALYSIS_RESULT_BLOCK, enrichment: { results: {} } }],
    } as never);
    expect(d.present).toBe(true);
    expect(d.leading_option_id).toBe('opt_hire');
    expect(d.win_probability_count).toBe(2);
    expect(d.has_summary).toBe(true);
    expect(d.has_enrichment).toBe(true);
  });

  it('counts array-shaped win_probabilities', () => {
    const d = extractDgaiState({
      blocks: [{ type: 'analysis_result', leading_option_id: 'o1', win_probabilities: [0.6, 0.4] }],
    } as never);
    expect(d.win_probability_count).toBe(2);
  });
});

// ---------------------------------------------------------------------------
// assertDgaiResultState
// ---------------------------------------------------------------------------
describe('assertDgaiResultState', () => {
  it('passes on a populated analysis_result block', () => {
    const r = assertDgaiResultState(res({ assistant_text: 'ok', blocks: [ANALYSIS_RESULT_BLOCK] }));
    expect(r.ok).toBe(true);
  });

  it('fails when the analysis_result block is absent', () => {
    const r = assertDgaiResultState(res({ assistant_text: 'ok', blocks: [] }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('dgai_result_state_absent');
  });

  it('fails when leading_option_id missing', () => {
    const r = assertDgaiResultState(
      res({ assistant_text: 'ok', blocks: [{ type: 'analysis_result', win_probabilities: { a: 0.6, b: 0.4 } }] }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('dgai_leading_option_missing');
  });

  it('fails when fewer than 2 win probabilities', () => {
    const r = assertDgaiResultState(
      res({ assistant_text: 'ok', blocks: [{ type: 'analysis_result', leading_option_id: 'o1', win_probabilities: { o1: 1 } }] }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('dgai_win_probabilities_too_few');
  });

  it('fails on a catastrophic leak in the summary (raw id)', () => {
    const r = assertDgaiResultState(
      res({
        assistant_text: 'ok',
        blocks: [{ ...ANALYSIS_RESULT_BLOCK, summary: 'Leading option is opt_hire by margin.' }],
      }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('dgai_summary_catastrophic_leak');
  });
});

// ---------------------------------------------------------------------------
// findEnrichmentLeakCarriers + collectLeakFindings (public surfaces only)
// ---------------------------------------------------------------------------
describe('findEnrichmentLeakCarriers (#277 carriers)', () => {
  it('detects carrier keys and value markers at depth', () => {
    const enrichment = {
      results: { report: {} },
      _meta: { seed: 1 },
      factor_sensitivity: [{ interpretation: 'fine' }],
      // `isl_engine` is carried as a string VALUE (per #277, inside m1_coaching),
      // and `[REDACTED]` is a redaction sentinel that survived on a kept field.
      decision_review: { note: '[REDACTED]', engine: 'generated by isl_engine' },
    };
    const findings = findEnrichmentLeakCarriers(enrichment);
    const details = findings.map((f) => `${f.kind}:${f.detail}`);
    expect(details).toContain('carrier_key:_meta');
    expect(details).toContain('carrier_key:seed');
    expect(details).toContain('value_marker:isl_engine');
    expect(details).toContain('value_marker:[REDACTED]');
  });

  it('returns nothing for a clean kept-field enrichment', () => {
    const enrichment = {
      results: { report: { option_probabilities: { win_probability: 0.6 } } },
      option_comparison: {},
      factor_sensitivity: [{ interpretation: 'Engineering Capacity is the top driver.' }],
      robustness: { band: 'stable' },
    };
    expect(findEnrichmentLeakCarriers(enrichment)).toHaveLength(0);
  });
});

describe('collectLeakFindings', () => {
  it('scans assistant_text, chips, and analysis_result.summary (prose) always', () => {
    const findings = collectLeakFindings(
      {
        assistant_text: 'The set_factor_value handler ran.',
        suggested_actions: [{ id: 'c1', label: 'opt_hire', message: 'ok' }],
        blocks: [{ type: 'analysis_result', summary: 'graph_hash leaked' }],
      } as never,
      { scanEnrichment: false },
    );
    const surfaces = findings.map((f) => f.surface);
    expect(surfaces).toContain('assistant_text');
    expect(surfaces).toContain('chip');
    expect(surfaces).toContain('analysis_result_summary');
    // Enrichment NOT scanned when scanEnrichment is false.
    expect(surfaces).not.toContain('enrichment');
  });

  it('scans public enrichment only when scanEnrichment is true', () => {
    const body = {
      assistant_text: 'clean',
      blocks: [{ type: 'analysis_result', summary: 'clean', enrichment: { _meta: { x: 1 } } }],
    } as never;
    expect(collectLeakFindings(body, { scanEnrichment: false }).some((f) => f.surface === 'enrichment')).toBe(false);
    expect(collectLeakFindings(body, { scanEnrichment: true }).some((f) => f.surface === 'enrichment')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// #277 flip-honesty regexes
// ---------------------------------------------------------------------------
describe('flip honesty regexes', () => {
  const HONEST =
    'Within the tested range, no single factor on its own reached a tipping point that would change which option leads.';
  const DISHONEST =
    'The picture appears fragile, so even small adjustments to the strongest drivers could shift which option leads.';

  it('honest marker matches the no-tipping-point copy, not the dishonest one', () => {
    expect(FLIP_NO_TIPPING_POINT_RE.test(HONEST)).toBe(true);
  });

  it('could-flip claim matches the dishonest copy, not the honest one', () => {
    expect(FLIP_COULD_FLIP_CLAIM_RE.test(DISHONEST)).toBe(true);
    expect(FLIP_COULD_FLIP_CLAIM_RE.test(HONEST)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// assertAddOption / assertAddOptionDefer
// ---------------------------------------------------------------------------
describe('assertAddOption (#278 Gate 1 cappable add)', () => {
  it('passes when the add is acknowledged', () => {
    const r = assertAddOption(res({ assistant_text: 'Added a new option to the decision.', suggested_actions: [] }));
    expect(r.ok).toBe(true);
  });
  it('fails when the cappable add is deferred', () => {
    const r = assertAddOption(res({ assistant_text: "I wasn't able to make that change safely.", suggested_actions: [] }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('add_option_unexpected_defer');
  });
  it('fails when the response clarifies instead of adding', () => {
    const r = assertAddOption(res({ assistant_text: 'Did you mean the offshore option?', suggested_actions: [] }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('add_option_clarification_back_no_apply');
  });
  it('fails when nothing is acknowledged', () => {
    const r = assertAddOption(res({ assistant_text: 'Here is your decision model overview.', suggested_actions: [] }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('add_option_no_acknowledgement');
  });
});

describe('assertAddOptionDefer (#278 Gate 3 unencodable add)', () => {
  it('passes on a safe defer with no false success', () => {
    const r = assertAddOptionDefer(res({ assistant_text: "I wasn't able to make that change safely." }));
    expect(r.ok).toBe(true);
  });
  it('fails when no defer copy is present', () => {
    const r = assertAddOptionDefer(res({ assistant_text: 'Option A leads at 60%.' }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('add_option_defer_missing_defer_copy');
  });
  it('fails when the defer path falsely claims the option was added', () => {
    const r = assertAddOptionDefer(
      res({ assistant_text: "I couldn't apply that, but I added a new option anyway." }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('add_option_defer_false_success_claim');
  });
});

// ---------------------------------------------------------------------------
// assertEditOptionContainment (#278 Gate 2 — CONTAINMENT-PASS)
// ---------------------------------------------------------------------------
describe('assertEditOptionContainment (#278 Gate 2 containment)', () => {
  const ctx = { factorLabel: 'Annual Cost', step1OptionLabels: ['Engage an offshore partner', 'Hire locally'] };

  it('PASS — safe defer (graph unchanged)', () => {
    const r = assertEditOptionContainment(res({ assistant_text: "I wasn't able to make that change safely." }), ctx);
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/path=defer/);
  });

  it('PASS — clarification back', () => {
    const r = assertEditOptionContainment(res({ assistant_text: 'Which option do you mean?' }), ctx);
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/path=clarify/);
  });

  it('PASS — clean apply that references the option (strict path working)', () => {
    const r = assertEditOptionContainment(
      res({ assistant_text: 'Updated the Engage an offshore partner option as requested.' }),
      ctx,
    );
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/path=applied_option_ref/);
  });

  it('FAIL — value-parse leak ("You gave unknown")', () => {
    const r = assertEditOptionContainment(res({ assistant_text: 'You gave unknown for the value.' }), ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('edit_option_value_parse_leak');
  });

  it('FAIL — misapplied as a factor-value update', () => {
    const r = assertEditOptionContainment(
      res({ assistant_text: 'Updated Annual Cost to 0.9.' }),
      ctx,
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('edit_option_misapplied_as_factor');
  });

  it('FAIL — unverifiable apply claim (references neither option nor factor)', () => {
    const r = assertEditOptionContainment(res({ assistant_text: 'Updated the value as requested.' }), ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('edit_option_unverifiable_apply_claim');
  });

  // Review comment 1 — option labels unavailable.
  it('FAIL (precondition) — missing option labels + mutation acknowledgement', () => {
    // No step1OptionLabels in ctx: an acknowledged edit cannot be verified for
    // containment → explicit precondition failure, NOT a silent pass and NOT a
    // misleading unverifiable_apply_claim.
    const r = assertEditOptionContainment(
      res({ assistant_text: 'Updated the option as requested.' }),
      { factorLabel: 'Annual Cost' },
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('edit_option_missing_option_labels');
  });

  it('PASS — missing option labels + safe defer (graph unchanged, no leak)', () => {
    // With no mutation acknowledgement, a safe defer is valid containment even
    // when option labels are unavailable — labels are only required to verify
    // an apply-claim.
    const r = assertEditOptionContainment(
      res({ assistant_text: "I wasn't able to make that change safely." }),
      undefined,
    );
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/path=defer/);
  });
});

// ---------------------------------------------------------------------------
// assertWhatWouldFlipChip (#277 fresh chip-click)
// ---------------------------------------------------------------------------
describe('assertWhatWouldFlipChip (#277 fresh)', () => {
  const goodBody = {
    assistant_text:
      'Within the tested range, no single factor on its own reached a tipping point that would change which option leads.',
    blocks: [ANALYSIS_RESULT_BLOCK],
    suggested_actions: [{ id: 'c1', label: 'Explore drivers', message: 'see drivers' }],
  };

  it('PASS — non-empty, honest, dispatch not capturable (no _timings)', () => {
    const r = assertWhatWouldFlipChip(res(goodBody));
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/dispatch=not_capturable/);
  });

  it('PASS — deterministic dispatch proven via _timings (llm_calls=0)', () => {
    const r = assertWhatWouldFlipChip(
      res({ ...goodBody, _timings: { turn: { handler_id: 'what_would_flip', llm_calls_used: 0 } } }),
    );
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.evidence).toMatch(/dispatch=deterministic/);
  });

  it('FAIL — empty blocks AND actions', () => {
    const r = assertWhatWouldFlipChip(res({ assistant_text: 'text only', blocks: [], suggested_actions: [] }));
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_chip_empty_blocks_actions');
  });

  it('FAIL — routed through the LLM (llm_calls > 0)', () => {
    const r = assertWhatWouldFlipChip(
      res({ ...goodBody, _timings: { turn: { handler_id: 'what_would_flip', llm_calls_used: 1 } } }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_chip_routed_through_llm');
  });

  it('FAIL — wrong handler id', () => {
    const r = assertWhatWouldFlipChip(
      res({ ...goodBody, _timings: { turn: { handler_id: 'explain_results', llm_calls_used: 0 } } }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_chip_unexpected_handler');
  });

  it('FAIL — dishonest contradiction (no tipping point AND could flip)', () => {
    const r = assertWhatWouldFlipChip(
      res({
        ...goodBody,
        assistant_text:
          'No single factor on its own reached a tipping point. The picture appears fragile, so even small adjustments could shift which option leads.',
      }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_chip_contradiction_no_flip_but_could_flip');
  });
});

// ---------------------------------------------------------------------------
// assertWhatWouldFlipStale (#277 stale follow-up)
// ---------------------------------------------------------------------------
describe('assertWhatWouldFlipStale (#277 stale)', () => {
  it('PASS — steers to rerun, no executable flip chip', () => {
    const r = assertWhatWouldFlipStale(
      res({
        assistant_text: 'The model changed since the analysis ran — please re-run analysis.',
        suggested_actions: [{ id: 'c1', label: 'Rerun analysis', message: 'Rerun analysis now.', action_type: 'run_analysis' }],
      }),
    );
    expect(r.ok).toBe(true);
  });

  it('FAIL — offers an executable what_would_flip chip while stale', () => {
    const r = assertWhatWouldFlipStale(
      res({
        assistant_text: 'The analysis is stale.',
        suggested_actions: [{ id: 'c1', label: 'What would flip?', message: 'flip', action_type: 'what_would_flip' }],
      }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_stale_executable_flip_chip_present');
  });

  it('FAIL — no rerun/staleness steer at all', () => {
    const r = assertWhatWouldFlipStale(
      res({ assistant_text: 'Option A still leads comfortably.', suggested_actions: [] }),
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.failing_contract).toBe('wwf_stale_no_rerun_steer');
  });
});
