/**
 * Compose a successful OlumiResponse for A2 turn classes.
 *
 * Per Pre-impl A and Paul's constraint 6: OlumiResponse is strictly the 6
 * schema-required fields — no `updated_session_state`, no extra keys. The
 * schema requires arrays so we emit [] for `blocks`, `suggested_actions`,
 * `insights`.
 *
 * A2 adds `composeClarifyResponse`. Its output is structurally identical to
 * `composeDirectAnswerResponse` (text-only). A2 emits no chips, no blocks —
 * widening to chips lands in E2.
 */

import type { OlumiResponse, StageType } from '@talchain/schemas/boundary';
import type { HandlerFact, RunAnalysisHandlerFact } from '@talchain/schemas/orchestrator';

import type { FreshnessDerivation } from './context/freshness.js';
import { TelemetryEvents, emit } from '../utils/telemetry.js';
import type { SuggestedAction } from './compose/types.js';
import {
  buildCoachingBlocks,
  buildEvidenceBlocks,
  buildFactorConfidenceLookup,
  buildGraphNodeLookup,
  buildReviewCardBlocks,
  buildStaleRerunCoachingBlock,
  type BlockBuildCtx,
} from './compose/phase3-blocks.js';

export interface ComposeInput {
  assistant_text: string;
  stage: StageType;
  /**
   * V5 Task 2.1: optional deterministic chip set. Pre-generated by the
   * chip-generator helper with stage + handler-facts + analysis context.
   * Undefined / empty keeps the pre-Task-2.1 behaviour of emitting `[]`.
   * Every chip must already conform to the boundary `ActionSchema`.
   */
  suggested_actions?: readonly SuggestedAction[];
}

// V5 finaliser contract: no composer in this file may set `analysis_ready`.
// The response-finaliser stamps it from the dispatch path's pre-computed
// payload after composition, before egress validation. See
// src/orchestrator-v5/response-finaliser.ts and the grep gate in
// scripts/check-no-direct-analysis-ready.sh.

export function composeDirectAnswerResponse(input: ComposeInput): OlumiResponse {
  return {
    response_version: 2,
    assistant_text: input.assistant_text,
    blocks: [],
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

export function composeClarifyResponse(input: ComposeInput): OlumiResponse {
  return {
    response_version: 2,
    assistant_text: input.assistant_text,
    blocks: [],
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

/**
 * V5 Phase 1 — composeToolCallResponse.
 *
 * Assembles the final OlumiResponse from three deterministic inputs on an
 * execute turn (spec §4.1 step 6):
 *
 *  - orientation: pre-action text from Sonnet (context, not outcomes)
 *  - confirmation: deterministic "what happened" text rendered from the
 *                  handler outcome via the handler's registered
 *                  confirmationTemplate (brief correction 5)
 *  - coaching: null stub for Phase 1a (spec step 5 is a no-op in this brief)
 *
 * Output shape is identical to composeDirectAnswerResponse — only the
 * assistant_text composition differs. Text fragments are joined with a
 * single blank line when both orientation and confirmation are non-empty;
 * otherwise the non-empty one stands alone.
 */
export interface ComposeToolCallInput {
  readonly orientation: string;
  readonly confirmation: string;
  readonly coaching: string | null;
  readonly stage: StageType;
  /**
   * V5 Group 1 Task B: when the turn's handler facts include a run_analysis
   * fact, compose emits an `analysis_result` block carrying the minimal
   * result fields plus the opaque enrichment (which may carry
   * `decision_review` under enrichment when the auto-fire completed).
   * Undefined for handler turns that do not produce this fact shape.
   */
  readonly handlerFacts?: readonly HandlerFact[];
  /**
   * V5 Task 2.1: pre-generated deterministic chips. See `ComposeInput`.
   */
  readonly suggested_actions?: readonly SuggestedAction[];
  /**
   * V5 Phase 3A PR 3 — block lifecycle context. When supplied AND the
   * current turn's `handlerFacts` carries NO `run_analysis` fact, the
   * composer walks `priorFacts` for the canonical prior fact (selected
   * by the freshness derivation upstream) and emits Phase 3 blocks
   * tagged by the freshness verdict:
   *   - 'fresh' → rebuild ReviewCard / Coaching / Evidence blocks from
   *               the prior fact (graph hash matches current → safe to
   *               present as live insights).
   *   - 'stale' → emit ONLY the stale-safe rerun CoachingBlock; suppress
   *               every other Phase 3 block (graph diverged → original
   *               insights are no longer trustworthy).
   *   - 'unknown' / 'none' → suppress emission entirely.
   *
   * Required context fields:
   *   - `priorFacts`: typically `EnrichedTurnContext.prior_facts`.
   *   - `freshness`: the `FreshnessDerivation` already computed by the
   *                  dispatcher's pre-handler step.
   *   - `requestId` + `scenarioId`: telemetry-only identifiers for
   *                                 `v5.phase3.block_lifecycle`.
   *
   * Omitting `lifecycle` preserves PR #178/180 behaviour: Phase 3
   * blocks emit ONLY when the current turn's `handlerFacts` contains a
   * run_analysis fact.
   */
  readonly lifecycle?: {
    readonly priorFacts: readonly HandlerFact[];
    readonly freshness: FreshnessDerivation;
    readonly requestId: string;
    readonly scenarioId: string;
  };
}

export function composeToolCallResponse(input: ComposeToolCallInput): OlumiResponse {
  const pieces: string[] = [];
  const trimmedOrientation = input.orientation.trim();
  const trimmedConfirmation = input.confirmation.trim();
  if (trimmedOrientation) pieces.push(trimmedOrientation);
  if (trimmedConfirmation) pieces.push(trimmedConfirmation);
  if (input.coaching) pieces.push(input.coaching.trim());

  const blocks = buildBlocksFromFacts(input.handlerFacts ?? [], input.lifecycle);

  return {
    response_version: 2,
    assistant_text: pieces.join('\n\n'),
    blocks,
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

/**
 * Map recognised handler facts to OlumiResponse blocks. Emitted shapes:
 *  - run_analysis fact → `analysis_result` block + Phase 3 lifecycle blocks
 *    (fresh review_card / coaching / evidence — see lifecycle decision tree
 *    below).
 *  - set_factor_value / add_constraint / adjust_edge_strength facts →
 *    `graph_patch` block (status, operation, target_id, before, after).
 *    The boundary GraphPatchBlock operation enum mirrors these three D1
 *    fact_types one-for-one so the mapping is direct.
 *
 * Phase 3 lifecycle decision tree (PR 3 — 2026-05-17):
 *
 *   1. Current turn contains a run_analysis fact with `graph_hash_at_run`:
 *      → emit `analysis_result` (existing) AND fresh Phase 3 blocks rebuilt
 *        from the current-turn fact's `enrichment.decision_review`.
 *        Lifecycle telemetry: `emitted_fresh`, reason='current_turn_fact'.
 *
 *   2. No current-turn run_analysis fact, but lifecycle context supplied
 *      AND prior_facts contains the selected run_analysis fact at
 *      `freshness.selected_fact_index`:
 *      a. freshness.freshness === 'fresh' → rebuild Phase 3 blocks fresh
 *         from the prior fact (graph hash matches current → safe).
 *         Lifecycle: `emitted_fresh`, reason='prior_fact_fresh'.
 *      b. freshness.freshness === 'stale' → emit ONLY the stale-safe
 *         rerun CoachingBlock; suppress every other Phase 3 block.
 *         Lifecycle: `emitted_stale`, stale_coaching_emitted=true.
 *      c. freshness.freshness === 'unknown' → suppress Phase 3 entirely
 *         (per spec: 'pending' implies in-flight generation, which is
 *         not the case here).
 *         Lifecycle: `skipped_unknown`.
 *      d. freshness.freshness === 'none' → no prior fact to derive from;
 *         skip Phase 3.
 *         Lifecycle: `skipped_none`.
 *
 *   3. No current-turn run_analysis fact AND no lifecycle context →
 *      preserve PR #178/180 behaviour: no Phase 3 emission, no telemetry.
 */
function buildBlocksFromFacts(
  facts: readonly HandlerFact[],
  lifecycle?: ComposeToolCallInput['lifecycle'],
): OlumiResponse['blocks'] {
  const blocks: OlumiResponse['blocks'] = [];
  let currentTurnRunAnalysisHandled = false;

  for (const fact of facts) {
    if (fact.fact_type === 'run_analysis') {
      currentTurnRunAnalysisHandled = true;
      blocks.push(buildAnalysisResultBlock(fact));

      // PR 3 lifecycle branch 1 — fresh blocks from current-turn fact.
      const graphHash = fact.result.graph_hash_at_run;
      if (typeof graphHash === 'string' && graphHash.length > 0) {
        const freshBlocks = rebuildPhase3BlocksFresh(fact, graphHash);
        blocks.push(...freshBlocks);
        if (lifecycle !== undefined) {
          emitLifecycle(lifecycle, {
            lifecycle_state: 'emitted_fresh',
            selected_fact_index: -1,  // -1 sentinel = current-turn fact
            graph_hash_at_run: graphHash,
            current_graph_hash: graphHash,
            reason: 'current_turn_fact',
            block_count: freshBlocks.length,
            stale_coaching_emitted: false,
          });
        }
      }
    } else if (
      fact.fact_type === 'set_factor_value' ||
      fact.fact_type === 'add_constraint' ||
      fact.fact_type === 'adjust_edge_strength'
    ) {
      // V5 product-state continuity (foamy-bee tranche) — DEFERRED
      // CONTRACT GAP: the wire `graph_patch` block emits raw `before`
      // and `after` records that carry structural identifiers
      // (`constraint_id`, `node_id`, edge IDs, `provenance`,
      // `operator` characters). The Phase 0 finding called for a
      // clean human-readable display field (`display` / `summary` /
      // `applied_summary`) so the UI doesn't have to render raw
      // structural fields by default.
      //
      // The fix requires widening the boundary `GraphPatchBlockSchema`
      // (currently `.strict()` and rejecting unknown fields) — a
      // coordinated change to the vendored schemas package, out of
      // scope for this tranche. The UI handoff brief
      // [Docs/v5/foamy-bee-ui-handoff.md] documents the deferral and
      // the renderer-side workaround (use `assistant_text` as the
      // primary display source). The deferred contract is pinned as
      // `it.todo` in
      // `compose/__tests__/graph-patch-clean-payload.test.ts`; flip
      // those to real assertions when the schemas package change
      // lands.
      const { target_id, status, before, after } = fact.result;
      blocks.push({
        type: 'graph_patch',
        status,
        operation: fact.fact_type,
        target_id,
        before,
        after,
      });
    }
  }

  // PR 3 lifecycle branch 2 — no current-turn run_analysis fact AND
  // lifecycle context supplied. Walk prior_facts using the freshness
  // verdict to select the canonical source fact and decide emission.
  if (!currentTurnRunAnalysisHandled && lifecycle !== undefined) {
    blocks.push(...buildLifecycleBlocksFromPrior(lifecycle));
  }

  return blocks;
}

/**
 * Pure helper: build the `analysis_result` block from a run_analysis fact's
 * result (summary + leading option + win probabilities + opaque enrichment).
 * Shared by branch-1 (current-turn fact) and the prior-fact FRESH lifecycle
 * branch so the UI gets a non-empty, structured result summary even when
 * `decision_review` is absent (autofire off) and the Phase 3 cards are empty.
 * Enrichment is sanitised downstream by the response-finaliser before egress.
 */
function buildAnalysisResultBlock(
  fact: RunAnalysisHandlerFact,
): OlumiResponse['blocks'][number] {
  const { leading_option_id, summary, win_probabilities, enrichment } = fact.result;
  return {
    type: 'analysis_result',
    summary,
    leading_option_id,
    ...(win_probabilities !== undefined ? { win_probabilities } : {}),
    ...(enrichment !== undefined ? { enrichment } : {}),
  };
}

/**
 * PR 3 — pure helper: rebuild the three Phase 3 builder outputs from a
 * single run_analysis fact at a known graph hash. Used by both the
 * current-turn fresh path and the prior-fact fresh path so they share
 * deterministic block construction.
 */
function rebuildPhase3BlocksFresh(
  fact: RunAnalysisHandlerFact,
  graphHash: string,
  freshness: 'fresh' | 'stale' = 'fresh',
): OlumiResponse['blocks'] {
  const ctx: BlockBuildCtx = {
    created_at: new Date().toISOString(),
    graph_hash_at_generation: graphHash,
    freshness,
  };
  const lookup = buildGraphNodeLookup(fact);
  const confidenceLookup = buildFactorConfidenceLookup(fact);
  return [
    ...buildReviewCardBlocks(fact, lookup, ctx),
    ...buildCoachingBlocks(fact, lookup, ctx),
    ...buildEvidenceBlocks(fact, lookup, confidenceLookup, ctx),
  ];
}

/**
 * PR 3 — branch 2 of the lifecycle decision tree. Fires only when the
 * current turn produced no run_analysis fact. Uses the
 * `FreshnessDerivation` already computed upstream to choose the
 * canonical prior fact and tag the emission.
 *
 * Freshness verdict → emission:
 *   fresh   → rebuild Phase 3 blocks fresh from the prior fact.
 *   stale   → emit ONLY the stale-safe rerun CoachingBlock, suppress
 *             everything else (per spec: stale graph means cached
 *             insights are no longer trustworthy).
 *   unknown → suppress; emit `skipped_unknown` telemetry.
 *   none    → suppress; emit `skipped_none` telemetry.
 */
function buildLifecycleBlocksFromPrior(
  lifecycle: NonNullable<ComposeToolCallInput['lifecycle']>,
): OlumiResponse['blocks'] {
  const { freshness, priorFacts } = lifecycle;
  const verdict = freshness.freshness;

  if (verdict === 'unknown') {
    emitLifecycle(lifecycle, {
      lifecycle_state: 'skipped_unknown',
      selected_fact_index: freshness.selected_fact_index,
      graph_hash_at_run: freshness.graph_hash_at_run,
      current_graph_hash: freshness.current_graph_hash,
      reason: freshness.reason,
      block_count: 0,
      stale_coaching_emitted: false,
    });
    return [];
  }
  if (verdict === 'none') {
    emitLifecycle(lifecycle, {
      lifecycle_state: 'skipped_none',
      selected_fact_index: freshness.selected_fact_index,
      graph_hash_at_run: freshness.graph_hash_at_run,
      current_graph_hash: freshness.current_graph_hash,
      reason: freshness.reason,
      block_count: 0,
      stale_coaching_emitted: false,
    });
    return [];
  }

  const priorFact = selectPriorRunAnalysisFact(priorFacts, freshness.selected_fact_index);
  if (priorFact === null) {
    emitLifecycle(lifecycle, {
      lifecycle_state: 'rebuild_failed',
      selected_fact_index: freshness.selected_fact_index,
      graph_hash_at_run: freshness.graph_hash_at_run,
      current_graph_hash: freshness.current_graph_hash,
      reason: 'selected_fact_unavailable',
      block_count: 0,
      stale_coaching_emitted: false,
    });
    return [];
  }

  const sourceGraphHash = priorFact.result.graph_hash_at_run;
  if (typeof sourceGraphHash !== 'string' || sourceGraphHash.length === 0) {
    // Defensive: freshness derivation should have rejected this fact
    // as 'unknown' or 'none' upstream. If it slipped through, do not
    // emit blocks without a verifiable graph hash.
    emitLifecycle(lifecycle, {
      lifecycle_state: 'rebuild_failed',
      selected_fact_index: freshness.selected_fact_index,
      graph_hash_at_run: freshness.graph_hash_at_run,
      current_graph_hash: freshness.current_graph_hash,
      reason: 'source_graph_hash_missing',
      block_count: 0,
      stale_coaching_emitted: false,
    });
    return [];
  }

  if (verdict === 'stale') {
    const staleBlock = buildStaleRerunCoachingBlock({
      created_at: new Date().toISOString(),
      graph_hash_at_generation: sourceGraphHash,
    });
    const blocks: OlumiResponse['blocks'] = staleBlock ? [staleBlock] : [];
    emitLifecycle(lifecycle, {
      lifecycle_state: 'emitted_stale',
      selected_fact_index: freshness.selected_fact_index,
      graph_hash_at_run: freshness.graph_hash_at_run,
      current_graph_hash: freshness.current_graph_hash,
      reason: freshness.reason,
      block_count: blocks.length,
      stale_coaching_emitted: staleBlock !== null,
    });
    return blocks;
  }

  // verdict === 'fresh' — emit the result summary block PLUS rebuilt Phase 3
  // blocks from the prior fact.
  //
  // V5 P0-B: the `analysis_result` block (result summary / win probabilities /
  // enrichment) gives the UI a non-empty, structured answer on a
  // what_would_flip / explain chip-click even when `decision_review` is absent
  // (autofire off) and the Phase 3 cards come back empty. This is emitted on
  // the FRESH verdict ONLY — the graph hash still matches the source fact, so
  // it is safe to present as live. The 'stale' branch above returns before
  // reaching here, so a diverged graph never surfaces a result block (only the
  // stale-safe rerun coaching block). Enrichment is sanitised by the
  // response-finaliser before egress.
  const analysisResultBlock = buildAnalysisResultBlock(priorFact);
  const phase3Blocks = rebuildPhase3BlocksFresh(priorFact, sourceGraphHash);
  const freshBlocks: OlumiResponse['blocks'] = [analysisResultBlock, ...phase3Blocks];
  emitLifecycle(lifecycle, {
    lifecycle_state: 'emitted_fresh',
    selected_fact_index: freshness.selected_fact_index,
    graph_hash_at_run: freshness.graph_hash_at_run,
    current_graph_hash: freshness.current_graph_hash,
    reason: 'prior_fact_fresh',
    block_count: freshBlocks.length,
    stale_coaching_emitted: false,
  });
  return freshBlocks;
}

/**
 * Resolve the canonical prior run_analysis fact using the index already
 * picked by the upstream freshness derivation. Falls back to "most
 * recent run_analysis fact in prior_facts" only when the index is null
 * (e.g. legacy callers that did not pre-compute one).
 */
function selectPriorRunAnalysisFact(
  priorFacts: readonly HandlerFact[],
  selectedFactIndex: number | null,
): RunAnalysisHandlerFact | null {
  if (selectedFactIndex !== null) {
    const fact = priorFacts[selectedFactIndex];
    if (fact !== undefined && fact.fact_type === 'run_analysis') {
      return fact;
    }
    return null;
  }
  // Defensive fallback — newest first per build-turn-context loader.
  for (const fact of priorFacts) {
    if (fact.fact_type === 'run_analysis') return fact;
  }
  return null;
}

interface LifecycleTelemetryPayload {
  readonly lifecycle_state:
    | 'emitted_fresh'
    | 'emitted_stale'
    | 'skipped_unknown'
    | 'skipped_none'
    | 'rebuild_failed';
  readonly selected_fact_index: number | null;
  readonly graph_hash_at_run: string | null;
  readonly current_graph_hash: string | null;
  readonly reason: string;
  readonly block_count: number;
  readonly stale_coaching_emitted: boolean;
}

function emitLifecycle(
  lifecycle: NonNullable<ComposeToolCallInput['lifecycle']>,
  payload: LifecycleTelemetryPayload,
): void {
  emit(TelemetryEvents.V5Phase3BlockLifecycle, {
    request_id: lifecycle.requestId,
    scenario_id: lifecycle.scenarioId,
    ...payload,
  });
}
