/**
 * Compose a successful OlumiResponse for A2 turn classes.
 *
 * Per Pre-impl A and Paul's constraint 6: OlumiResponse is strictly the 6
 * schema-required fields — no `updated_session_state`, no extra keys. The
 * schema requires arrays so we emit [] for `blocks`, `suggested_actions`,
 * `insights`.
 *
 * A2 adds `composeClarifyResponse`. Its output is structurally identical to
 * `composeDirectAnswerResponse` (text-only). A2 emits no chips, no blocks —
 * widening to chips lands in E2.
 */

import type { OlumiResponse, StageType } from '@talchain/schemas/boundary';
import type { HandlerFact } from '@talchain/schemas/orchestrator';

import type { SuggestedAction } from './compose/types.js';
import {
  buildCoachingBlocks,
  buildEvidenceBlocks,
  buildFactorConfidenceLookup,
  buildGraphNodeLookup,
  buildReviewCardBlocks,
  type BlockBuildCtx,
} from './compose/phase3-blocks.js';

export interface ComposeInput {
  assistant_text: string;
  stage: StageType;
  /**
   * V5 Task 2.1: optional deterministic chip set. Pre-generated by the
   * chip-generator helper with stage + handler-facts + analysis context.
   * Undefined / empty keeps the pre-Task-2.1 behaviour of emitting `[]`.
   * Every chip must already conform to the boundary `ActionSchema`.
   */
  suggested_actions?: readonly SuggestedAction[];
}

// V5 finaliser contract: no composer in this file may set `analysis_ready`.
// The response-finaliser stamps it from the dispatch path's pre-computed
// payload after composition, before egress validation. See
// src/orchestrator-v5/response-finaliser.ts and the grep gate in
// scripts/check-no-direct-analysis-ready.sh.

export function composeDirectAnswerResponse(input: ComposeInput): OlumiResponse {
  return {
    response_version: 2,
    assistant_text: input.assistant_text,
    blocks: [],
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

export function composeClarifyResponse(input: ComposeInput): OlumiResponse {
  return {
    response_version: 2,
    assistant_text: input.assistant_text,
    blocks: [],
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

/**
 * V5 Phase 1 — composeToolCallResponse.
 *
 * Assembles the final OlumiResponse from three deterministic inputs on an
 * execute turn (spec §4.1 step 6):
 *
 *  - orientation: pre-action text from Sonnet (context, not outcomes)
 *  - confirmation: deterministic "what happened" text rendered from the
 *                  handler outcome via the handler's registered
 *                  confirmationTemplate (brief correction 5)
 *  - coaching: null stub for Phase 1a (spec step 5 is a no-op in this brief)
 *
 * Output shape is identical to composeDirectAnswerResponse — only the
 * assistant_text composition differs. Text fragments are joined with a
 * single blank line when both orientation and confirmation are non-empty;
 * otherwise the non-empty one stands alone.
 */
export interface ComposeToolCallInput {
  readonly orientation: string;
  readonly confirmation: string;
  readonly coaching: string | null;
  readonly stage: StageType;
  /**
   * V5 Group 1 Task B: when the turn's handler facts include a run_analysis
   * fact, compose emits an `analysis_result` block carrying the minimal
   * result fields plus the opaque enrichment (which may carry
   * `decision_review` under enrichment when the auto-fire completed).
   * Undefined for handler turns that do not produce this fact shape.
   */
  readonly handlerFacts?: readonly HandlerFact[];
  /**
   * V5 Task 2.1: pre-generated deterministic chips. See `ComposeInput`.
   */
  readonly suggested_actions?: readonly SuggestedAction[];
}

export function composeToolCallResponse(input: ComposeToolCallInput): OlumiResponse {
  const pieces: string[] = [];
  const trimmedOrientation = input.orientation.trim();
  const trimmedConfirmation = input.confirmation.trim();
  if (trimmedOrientation) pieces.push(trimmedOrientation);
  if (trimmedConfirmation) pieces.push(trimmedConfirmation);
  if (input.coaching) pieces.push(input.coaching.trim());

  const blocks = input.handlerFacts ? buildBlocksFromFacts(input.handlerFacts) : [];

  return {
    response_version: 2,
    assistant_text: pieces.join('\n\n'),
    blocks,
    suggested_actions: [...(input.suggested_actions ?? [])],
    insights: [],
    stage_indicator: input.stage,
  };
}

/**
 * Map recognised handler facts to OlumiResponse blocks. Emitted shapes:
 *  - run_analysis fact → `analysis_result` block.
 *  - set_factor_value / add_constraint / adjust_edge_strength facts →
 *    `graph_patch` block (status, operation, target_id, before, after).
 *    The boundary GraphPatchBlock operation enum mirrors these three D1
 *    fact_types one-for-one so the mapping is direct.
 */
function buildBlocksFromFacts(
  facts: readonly HandlerFact[],
): OlumiResponse['blocks'] {
  const blocks: OlumiResponse['blocks'] = [];
  for (const fact of facts) {
    if (fact.fact_type === 'run_analysis') {
      const { leading_option_id, summary, win_probabilities, enrichment } = fact.result;
      blocks.push({
        type: 'analysis_result',
        summary,
        leading_option_id,
        ...(win_probabilities !== undefined ? { win_probabilities } : {}),
        ...(enrichment !== undefined ? { enrichment } : {}),
      });

      // V5 Phase 3A — emit structured ReviewCard / Coaching / Evidence
      // blocks from `enrichment.decision_review` when it's present and
      // the fact carries a graph hash (proof of freshness — per Codex
      // correction #4, PR 2 only emits Phase 3 blocks on a verifiable-
      // fresh fact; PR 3 owns persistence-by-graph-hash + stale
      // rendering). Builders are pure; each candidate is `safeParse`-
      // validated and dropped on failure.
      const graphHash = fact.result.graph_hash_at_run;
      if (typeof graphHash === 'string' && graphHash.length > 0) {
        const ctx: BlockBuildCtx = {
          created_at: new Date().toISOString(),
          graph_hash_at_generation: graphHash,
        };
        const lookup = buildGraphNodeLookup(fact);
        const confidenceLookup = buildFactorConfidenceLookup(fact);
        blocks.push(...buildReviewCardBlocks(fact, lookup, ctx));
        blocks.push(...buildCoachingBlocks(fact, lookup, ctx));
        blocks.push(
          ...buildEvidenceBlocks(fact, lookup, confidenceLookup, ctx),
        );
      }
    } else if (
      fact.fact_type === 'set_factor_value' ||
      fact.fact_type === 'add_constraint' ||
      fact.fact_type === 'adjust_edge_strength'
    ) {
      // V5 product-state continuity (foamy-bee tranche) — DEFERRED
      // CONTRACT GAP: the wire `graph_patch` block emits raw `before`
      // and `after` records that carry structural identifiers
      // (`constraint_id`, `node_id`, edge IDs, `provenance`,
      // `operator` characters). The Phase 0 finding called for a
      // clean human-readable display field (`display` / `summary` /
      // `applied_summary`) so the UI doesn't have to render raw
      // structural fields by default.
      //
      // The fix requires widening the boundary `GraphPatchBlockSchema`
      // (currently `.strict()` and rejecting unknown fields) — a
      // coordinated change to the vendored schemas package, out of
      // scope for this tranche. The UI handoff brief
      // [Docs/v5/foamy-bee-ui-handoff.md] documents the deferral and
      // the renderer-side workaround (use `assistant_text` as the
      // primary display source). The deferred contract is pinned as
      // `it.todo` in
      // `compose/__tests__/graph-patch-clean-payload.test.ts`; flip
      // those to real assertions when the schemas package change
      // lands.
      const { target_id, status, before, after } = fact.result;
      blocks.push({
        type: 'graph_patch',
        status,
        operation: fact.fact_type,
        target_id,
        before,
        after,
      });
    }
  }
  return blocks;
}
